### ISSUE TITLE
Forget PHP 5.6 compatibility

### ISSUE THREAD

**Issue by AdamPerkins** [scssphp/scssphp#10]
scssphp is compatible to PHP 5.6.

Therefore a lot of good features of PHP 7.x can't be used. I recommend a minimum requirement of PHP 7.0.

Anyway, nobody (really nobody) should use PHP 5.6 in 2019.

**Comment by Cerdic** [comment]
I know it's always nice to use PHP modern features, but I'm also concerned in avoiding as much as possible to help in the big planned obsolescence and the perpetual fast-forward fleeing.

This compiler is not a standalone tool but is aimed to be involved in a complete publishing workflow that could include some other tools still offering a PHP 5.6 compat and not necessarly used by tech-people aware of constant upgrades
(typically the one I'm using and contributing to, besides this compiler)

So as long as keeping a PHP 5.6 compat doesn't cost too much I would really be happy to stick on that :)

**Comment by AdamPerkins** [comment]
Well, sorry for speaking free, but administrators and developers that was not able to update theirs systems OVER YEARS should burn in hell ;-)

Everybody knows that PHP5.6 shouldn't be used since 2016 and EOL incl. security fixes came for 5.6 AND 7.0 at the end of 2018. Even 7.1 has no active support anymore.

But there is IMHO another point. As we know the development leafo/scssphp was sleeping for a longer period. And mainly thanks your and @robocoder phantastic work and effort since some months scssphp got working again with modern CSS frameworks like Bootstrap 4.

What I wanted to pointed out: I can't believe that there are a lot of active big projects that are using atm sccsphp but need php5.6.

Web development, CMS, frameworks etc. are very dynamic projects and needs mostly the newest hot stuff. I can't believe big active projects are really supporting 5.6 anymore.

On the other hand, you as a professional PHP programmer are bound on old PHP code syntax which may make your life unnecessarily heavy.

**Comment by robocoder** [comment]
I agree in general with dropping support for PHP 5.6 but you're ignoring the fact that scssphp is a part of much larger projects and ecosystems. Dropping PHP 5.6 and 7.0 support will happen; it simply isn't urgent.

Generally, I use Ubuntu LTS releases as my reference. So, as an example, Ubuntu 14.04.x LTS ships with PHP 5.5.x; its EOL is April 2022.

**Comment by robocoder** [comment]
This will probably come up again, so I've immortalized my thoughts here:
* [Supported PHP Versions](https://github.com/scssphp/scssphp/wiki/Supported-PHP-Versions)

**Comment by mahagr** [comment]
I'm kind of with @robocoder here. Unless you want to maintain multiple versions of your library like Symfony does, you should keep supporting older versions of PHP in order to keep projects which cannot afford to go to later PHP versions because of their huge customer/user base.

Personally I would always go for the latest PHP version and keep the constraints tight but unfortunately, if you maintain a project with hundreds of thousands of installations, it is not that easy to do that.

**Comment by robocoder** [comment]
@mahagr Since you asked nicely...

**Comment by robocoder** [comment]
Don't hold your breath for packagist.org to update (the last scan was 2019-05-16 for v0.8.2) but I downgraded the PHP requirements and tagged v0.8.4 on the old leafo/scssphp repo.

Thanks for the suggestion.

**Comment by mahagr** [comment]
@robocoder Unfortunately you missed compatibility fixes in:

https://github.com/leafo/scssphp/blob/v0.8.1/src/Compiler.php#L1493
https://github.com/leafo/scssphp/blob/v0.8.1/src/Compiler.php#L2141

Basically you need to use `'Leafo\ScssPhp\Block'` instead of `Block::class` to make it work in PHP 5.4. :)

**Comment by mahagr** [comment]
@robocoder Thanks a lot, I can use that in older version of the project still supporting PHP 5.4.

It looks like the release is identical to 1.0, is that true?

**Comment by robocoder** [comment]
Functionally equivalent to 1.0 but not identical due to changes in PHP namespace, composer/packagist package name, and PHP version dependencies.

**Comment by Cerdic** [comment]
I think this Ubuntu LTS EOL is a good guideline, thank you @robocoder

**Comment by robocoder** [comment]
FYI packagist finally indexed 0.8.4 of `leafo/scssphp`
