### ISSUE TITLE
Sass-spec should be updated to use the official source

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#102]
According to the readme, the sass-spec being used for the testsuite is taken from the libsass repo.
The official source is at https://github.com/sass/sass-spec so I think it would make sense to take them from there instead (and maybe reference them as a git submodule or install them with a composer inline package repository rather than copying them in the repo).

**Comment by Cerdic** [comment]
Indeed copying it was the easier way for me to make it available, but we can use another way as long as we are able to point on a fixed version. This is already a lot of work to try to close the gap, it would be unhelpful to have to deal with an evolving spec.
A the moment we are refering to https://github.com/sass/sass-spec/releases/tag/libsass-3.6.0

My mind is that as long we are not fullfilling this version of the spec and don't want to update the spec we are refering to, this is not a critical point.

However feel free to solve this issue - I would tend to pick the solution with an inline composer package, this seems more consistent with what we are doing for the others components.

**Comment by stof** [comment]
While trying this, I discovered that the sass-spec folder is not *exactly the imported one. It contains 1980 hrx files, while the original one contains 1981 files...

**Comment by Cerdic** [comment]
indeed https://github.com/scssphp/scssphp/pull/127#issuecomment-674922440
same problem with `composer install` on mac os

This is an issue mainly because the exclude fail list includes the order and total number of each test, which is helping for debug but should be just an help.

**Comment by Cerdic** [comment]
Finaly fixed, thanks again!
