### ISSUE TITLE
Arguments selector issue 

### ISSUE THREAD

**Issue by stempora** [scssphp/scssphp#105]
Differences between the node compiler and the php compiler

The follwoing mixin will throw an error:
@mixin context($old-context, $new-context) {
	@at-root #{selector-replace(**&**, $old-context, $new-context)} {
		@content;
	}
}

Fatal error: Uncaught ScssPhp\ScssPhp\Exception\CompilerException: selector-replace() invalid arguments:

Seems the problem is from using the "**&**" as a parameter;

I tried to have a intermediary variable that receives the & 

@mixin context($old-context, $new-context) {
	$parent : & ;
	@at-root #{selector-replace($parent, $old-context, $new-context)} {
		@content;
	}
}

In node compiler will work fine both cases. The second case will compile in php but with a different result ...

SCSS Code: 

.par1 {
    .par2 {
	@include context('.par1', '.par1 .int1 .int2') {
            .final & {
                width: 5.4rem;
            }
        }
    }
}

Node results: ( correct one ) 

.final .par1 .int1 .int2 .par2 {
  width: 5.4rem;
}

Php results: 

.final .par1 .par2 {
  width: 5.4rem; }

Same problem i have with selector-unify also.

Thanks!

**Comment by stempora** [comment]
Here is an example of something similar what i was trying to achive, but its not compiling.

https://stackoverflow.com/questions/28593476/modifying-the-middle-of-a-selector-in-sass-adding-removing-classes-etc

**Comment by stempora** [comment]
After some more testing seems the problem is when i have this case:

$parent : &;
selector-replace($parent , ".par1", ".par1 .test .test2");

this works fine:
selector-replace($parent , ".par1", ".test .test2");

Seems the problem is when i try to "append a couple classes". if "par1" exists in both search & replace it wont work.

**Comment by stempora** [comment]
Any thoughts about this?

**Comment by Cerdic** [comment]
the `selector-replace` function is using the `@extend` selector logic, and this is really a tricky part.

As you can see here 
https://github.com/scssphp/scssphp/blob/master/tests/specs/sass-spec-exclude.txt#L254
there is still a lot of case we are not matching fully the spec and at the moment I'm not able to say if we can reach this goal fixing the existing logic or if this need a more important refactoring/rebuilding (maybe trying to start from a copy from the internal logic of libsass, if possible)

For a full test case  
```
.class .par1 {
  $parent : &;
  content: selector-replace($parent , ".par1", ".par1 .test .test2");
}

.class .par1 {
  $parent : &;
  content: selector-replace($parent , ".par1", ".test .test2");
}
```

Sassmeister result : 
```
.class .par1 {
  content: .class .par1 .test .test2, .par1 .test .class .test2;
}

.class .par1 {
  content: .class .test .test2, .test .class .test2;
}
```

scssphp result : 
```
.class .par1 {
  content: .class .par1; }

.class .par1 {
  content: .class .test .test2, .test .class .test2; }
```

It's indeed not working here, and i guess this is because of some anti-infinite recursion trick.

And for the initial point, indeed
```
.class .par1 {
        @at-root #{selector-replace(&, ".par1", ".par1 .test .test2")} {
                color:red;
        }
}
```

is not compiling at all.
That's 2 bugs then :)

**Comment by stempora** [comment]
@Cerdic Thanks for the response,

Any ideea if there is any work around i could use and to be compatible with it ?

Like to give more control to registerFunction and to have access to the entire node tree and manipulate it custom in php ?

**Comment by Cerdic** [comment]
@stempora  a60825a6 is fixing the case where the replacement includes the replaced part

**Comment by stempora** [comment]
@Cerdic Thanks a lot thats great news !

**Comment by Cerdic** [comment]
This is fully fixed now, including the usage of `&` in selector-replace when in a `@at-root` directive
