### ISSUE TITLE
The ability to run server via pscss.

### ISSUE THREAD

**Issue by indrakaw** [scssphp/scssphp#106]

**Comment by robocoder** [comment]
`bin/pscss` is intended for command-line use.

If you want a "server", consider adapting https://github.com/scssphp/server for your use.

**Comment by indrakaw** [comment]
Updated the title.

Watch is basically watching changes on directory or file, then it complies automatically. Way better than having to point to a external resource HTTP server or run via CLI every single time.

**Comment by robocoder** [comment]
Take a look at `entr` or `fswatch`.
