### ISSUE TITLE
error in calculations

### ISSUE THREAD

**Issue by jszczypk** [scssphp/scssphp#108]
Hi,

The code below:
```
a {
  width: (14px / 1440px) * 100vw;
  height: 14px * 100vw / 1440px;
}
```
is compiled as:
```
a {
  width: 0.9722222222vw;
  height: 0.0101273148vw;
}
```

while the expected result is:
```
a {
  width: 0.9722222222vw;
  height: 0.9722222222vw;
}
```

I have just switched to scssphp from original ruby scss compiler and found this.
I am using current version - 1.1.0.

Best regards,
Janusz

**Comment by robocoder** [comment]
This is a regression introduced by 1d7cc4f113ccd76f362ad06ad385b96c95facac7
