### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by jljr222** [scssphp/scssphp#11]
Hi Guys,

Having a problem with implementing scssphp for my project. I am requiring these two files like so:

```
require_once __DIR__ . '/lib/scssphp/scss.inc.php';
require_once __DIR__ . '/lib/scssphp/example/Server.php';
```
Getting no errors and the files are being loaded appropriately. Followed that with these:

```
use ScssPhp\ScssPhp\Compiler;
use ScssPhp\ScssPhp\Server;
```

Then I did a quick test to ensure the classes are working:

`$scss = new Compiler();`

Which returns:

> Error: Class 'ScssPhp\ScssPhp\Compiler' not found

I ran a get_declared_classes() function to see if it's not in the array it spits out...and sure enough, it's missing. The odd part is that the class "ScssPhp\ScssPhp\Server" shows up just fine. I am not sure why that would be case. Any ideas?

**Comment by jljr222** [comment]
Sorry, this was due to a configuration issue with an app I'm using to handle my file uploads. Was filtering out the wrong folder.

**Comment by mahagr** [comment]
@jljr222 Sidenote, why cannot you just use composer to autoload the classes? :)

**Comment by jljr222** [comment]
@mahagr Sorry, but I am still diving into development with PHP and I am not familiar with how to use composer.

**Comment by mahagr** [comment]
It is really easy to set up and it really helps to manage your dependencies:

https://getcomposer.org/doc/00-intro.md
