### ISSUE TITLE
What is the precedence of injected variables?

### ISSUE THREAD

**Issue by dleffler** [scssphp/scssphp#110]
I use the ->setVariables() call to try to set some variables when compiling Twitter Bootstrap 4 such as the $enable-responsive-font-sizes flag. While the compiler picks up the other variables which are only used in my custom stylesheets, the variables which have been set as !default in the Bootstrap stylesheets seem to override the passed variables.

**Comment by robocoder** [comment]
Can you provide a test case?

Assuming bootstrap is imported last, the observed precedence is expected to be:

`setVariables()` > vars set in your stylesheets > !default

**Comment by dleffler** [comment]
I am now unable to reproduce this under the v1.1.1 release.
