### ISSUE TITLE
Wrong result when working with extend and class concatenation

### ISSUE THREAD

**Issue by develth** [scssphp/scssphp#111]
Hello,

i recognized wrong results when using extend inside a class concatenatoin after updating from 1.0.5 to 1.0.6:

I have following scss:

```
%tc {
  &:before {
    display: inline-block;
  }
}

.parent {
  &-sub {
    &:hover {
      @extend %tc;
    }
  }
}
```

When running it in local scss / sass compiler, i get this result:

```
.parent-sub:hover:before {
	display: inline-block;
}
```

When running it with scssphp, i get this result:

```
.parent:hover-sub:before {
  display: inline-block; }
```

Best Regards
Thomas

**Comment by Cerdic** [comment]
I can reproduce with the last version of scssphp an confirm this is working with sassmeister

**Comment by Cerdic** [comment]
This is fixed now :)

**Comment by develth** [comment]
Thanks!
