### ISSUE TITLE
Reformat css without recompiling again entire scss

### ISSUE THREAD

**Issue by Arsavin** [scssphp/scssphp#116]
```
$scss = new ScssPhp();

$scss->setFormatter('ScssPhp\\ScssPhp\\Formatter\\Expanded');
$scss->compile($css);

$scss->setFormatter('ScssPhp\\ScssPhp\\Formatter\\Crunched');
$scss->compile($css);
```

Hello. That's my code.

I need my scss code in both `expanded` and `crunched` formats. How can I achieve that without recompiling again entire scss?

**Comment by robocoder** [comment]
Subclass the Compiler class and write a compile() method that does that.

Or submit a PR that refactors the compile() method, so there's a new method that returns only the compiled tree, and another that formats it (taking the tree as a parameter).

**Comment by Arsavin** [comment]
Thanks for reply @robocoder. I don't know so much about ScssPhp. I am also a beginner in PHP.
Is it hard what you mean I should do? Can you help me please?

**Comment by robocoder** [comment]
Sorry, I took a deeper look at this and this isn't feasible without a significant refactoring because of how tightly coupled the internal representation is to the formatter.
