### ISSUE TITLE
variables in css vars not replaced

### ISSUE THREAD

**Issue by mokraemer** [scssphp/scssphp#118]
having the following example:
`$test: #777777;
:root{
	--body: $test;
	}
body{
	color: $test;
	}`

$test is not replaced after --body

Even if this might not be useful, all occurrences of scss vars should be replaced

**Comment by Cerdic** [comment]
Doesn't sounds like a bug according to sassmeister:
https://www.sassmeister.com/

<img width="825" alt="Capture d’écran 2020-06-30 à 15 30 08" src="https://user-images.githubusercontent.com/342805/86132027-a7485000-bae6-11ea-9783-fb5acaa573d4.png">

**Comment by mokraemer** [comment]
maybe sassmeister does not take css variables into account too?

why not apply scss variables to a css variable?

**Comment by mokraemer** [comment]
it would be nice not to close an issue if it is not "resolved". as I can't reopen issues that are not resolved.
It would be nice to wait at least for some time so I can reply to your comment.

**Comment by robocoder** [comment]
It's not a bug if it's the same behaviour in dart sass.

**Comment by Cerdic** [comment]
The purpose of ScssPHP is to implement the sass-lang specification and to allow to compile the same scss files as well with dart-sass, libsass or scssphp.

At the moment we still have a lot of work to be fully compliant with the base specification, I don't think it would be a useful idea to fork on the supported syntax because we find it better.

If this a real issue, it should be opened to the sass-lang specification group https://sass-lang.com/

**Comment by Cerdic** [comment]
(by the way, the same question was already discussed in #91)

**Comment by mokraemer** [comment]
ok, opened an issue on dart-sass. let's see, if they think it is an bug.
I think they just didn't take new css syntax into account.

But let's wait for the reply.

**Comment by Cerdic** [comment]
@mokraemer maybe just reading the documentation could be helpful: https://sass-lang.com/documentation/breaking-changes/css-vars

**Comment by mokraemer** [comment]
I've checked the variables section on the documentation, there is no hint about css variables. The section "breaking changes" was not very obvious to search that information.
It is quite hard to keep up with all changes that are wide spread around.
Since you are not responsible for the language itself, I will not argue about that. The syntax "--xxx: {$yyy};" is not obvious.
