### ISSUE TITLE
variables in css vars not replaced

### ISSUE THREAD

**Issue by mokraemer** [scssphp/scssphp#119]
having the following example:
$test: #777777; :root{ --body: $test; } body{ color: $test; }

$test is not replaced after --body

Even if this might not be useful, all occurrences of scss vars should be replaced

------

maybe sassmeister does not take css variables into account too?

why not apply scss variables to a css variable?

**Comment by Cerdic** [comment]
I don't think opening multiples issues for the same question is a really nice way to make progress on the subject.
Let's keep the discussion on #118
