### ISSUE TITLE
Compiling Multiple Files

### ISSUE THREAD

**Issue by jljr222** [scssphp/scssphp#12]
Hello,

I am using this library in a module that allows users to customize a theme I've created. I'm using the server example to read my SCSS files and compile the stylesheet(s). That works without issue, but I've noticed it sometimes will timeout for multiple files. Right now, I have four different SCSS files, all of the same size. They are separated via "light/dark" and "RTL/LTR."

Is there a best practice for setting up a compilation of multiple files? If I put all four compile requests into the same try catch, it times out with an infinite loop error. So I separated the RTL and LTR styles into different try catches which eliminated that issue.  Should I have a try catch for each SCSS file I'm trying to compile?

**Comment by LrntL** [comment]
Hi!

I have a similar problem. See https://github.com/scssphp/scssphp/issues/20
Users can create a theme file containing variables (like colors) to overwrite the default value.

I need to import this theme file with a dynamic path (based on the domain name). Do you know how can I import this file with a (PHP?) variable to specify its location ?

Thanks ;)

**Comment by robocoder** [comment]
Are the "timeouts" due to compilation time exceeding the PHP time limit, or an infinite loop? I don't believe try..catch handles either of those, so if an exception is being thrown, it's likely due to invalid scss.

Long compilation times suggest you should be compiling offline instead of using the Server class.

If you have multiple files, then imho a separate try...catch for each compiled file is ok if you're willing to accept that some files may not have been (re)compiled.

**Comment by robocoder** [comment]
See also: https://www.php.net/manual/en/function.set-time-limit.php

**Comment by LrntL** [comment]
Thank you.

For my case, I am just trying to define the path of just one scss file (theme.scss) in my main scss file.
So, I am going to continue this here : https://github.com/scssphp/scssphp/issues/20 to avoid duplicate.

**Comment by jljr222** [comment]
The SCSS is valid since it compiles fine when using Prepros or other SCSS compilers. It simply takes a long time using the server class. I was just curious if there is a way to speed up the process in which in compiles?

**Comment by robocoder** [comment]
* Use the latest scssphp version. (Cerdic added a cache to the Compiler class.)
* Disable source maps if not needed.
* Upgrade your php version if possible. (Potential BC issues here, so I mention it last.)

One of the perceived slowdowns was switching from arrays to a class/object for numbers. That was to increase code readability/maintainability. I can't find my profiling results but IIRC it was more pronounced in PHP 5.x than with PHP 7.x.

**Comment by jljr222** [comment]
Thanks!

How exactly would I setup the cache and disable source maps?

Here is an example:
```
    $sourceDir = dirname( __FILE__ ) . '/theme/scss/';
    $cacheDir = dirname( __FILE__ ) . '/theme/scss_cache/';
    $compileDir = dirname( dirname( dirname( dirname( __FILE__ ) ) ) ) . '/templates/allure/css';
    $cssFormat = 'ScssPhp\ScssPhp\Formatter\Crunched';
    $importPath = dirname( __FILE__ ) . '/theme/scss/';

    $scss = new Compiler();
    $scss->setVariables( $scssVariables );
    $scss->setFormatter( $cssFormat );
    $scss->setImportPaths( $importPath );
    $server = new Server( $sourceDir, $cacheDir, $scss );
    $server->compileFile( $sourceDir . '/theme.scss', $compileDir . '/theme.min.css' );
```
I've set the cache folder, but it's always empty when it compiles...

**Comment by robocoder** [comment]
By default, there are no source maps, and caching is automatically enabled.

If there are no cached files, then you have a filesystem permissions issue. That's out-of-scope in terms of our ability to support. I'm guessing your web server runs under a different UID than your shell account.

**Comment by jljr222** [comment]
My web server setup seems fairly straight-forward. It's a CentOS 7 VPS with cPanel/WHM running on LiteSpeed. I checked to ensure that the folder has write permissions for my application. Is there no error generated by SCSSPHP when it cannot write cache files?

**Comment by robocoder** [comment]
I thought it might be using `@` but it isn't. Strange that there's no cached file generation.

**Comment by jljr222** [comment]
I updated to 1.0.2 just to ensure that I was running the latest version. I rendered another compilation from my application and it did not create any cache files. Not sure if my setup is incorrect?

**Comment by jljr222** [comment]
I tried using "cachedCompile" vs "compileFile" to generate my CSS files and it did not make a difference. Any ideas?

**Comment by robocoder** [comment]
Can you see copies of the generated .css and .meta files?

**Comment by jljr222** [comment]
I do see those files if I use "checkedCachedCompile". Should I be using that instead?

**Comment by robocoder** [comment]
Well, until you figure out why it's not writing to the cache directory, you can  go with `checkedCachedCompile()`, but you'll also be responsible for the request/response headers (currently done for you in `serve()`).

I still think offline compilation might be a better route, using a separate process (such as cron) or an async library (such as ReachPHP).

**Comment by jljr222** [comment]
I'm using this in a project that allows anyone to customize specific sections of my theme. So offline compilation is not an option. The compilation is only triggered when changes are noticed with specific variables.

I am not sure how I would figure out why it's not writing to the cache directory. If my setup is not wrong then it makes no sense. I would hope for some assistance here because clearly it's not working.

**Comment by robocoder** [comment]
Nothing comes to mind but it's pretty much environment-specific at this point.

**Comment by jljr222** [comment]
I was able to figure this out. The reason the scss_cache was not generating files was due to the fact I was not serving the SCSS. I was using the compile file function which does not appear to cache anything. My project generates a CSS file that's about 400kb in size. It takes about 21 seconds to compile, is that a normal run-time for a CSS file that size?

**Comment by robocoder** [comment]
I can't say if that's normal or not. Compile time is dependent on what preprocessing is performed and the underlying system (e.g., hardware or VM).

You should instead ask if the compile-time compared with ruby or dart sass is acceptable?
