### ISSUE TITLE
compiled file path has no effect on include path

### ISSUE THREAD

**Issue by lalop** [scssphp/scssphp#122]
Hello, 

When we compile a file that is in a subfolder, the import process for relative path is broken even if the compiled file path is given to the compile method.

In my test I can compile a scss that imports relative.scss if it's in the include root folder, but I can't compile the content of this file.
So the include context is not handled for import that is in the main file as they are in imported ones.

I created a test to explain my point https://github.com/lalop/scssphp/commit/de386b8416fed00a29e9df4636edbc4334a9db54

**Comment by robocoder** [comment]
Import paths should be absolute paths unless you want them to be relative to the current directory (which varies depending on where you execute the bin/pscss script from, or where the current directory has been set to when the scssphp library is invoked).

**Comment by lalop** [comment]
The relative path shouldn't be relative to the file containing the import path ?

**Comment by robocoder** [comment]
The library isn't going to guess where relative paths are relative to.

Try using something like:
```
$scss->addImportPath(dirname($myScssFile));
```
