### ISSUE TITLE
Get all variables that are being processed during compilation

### ISSUE THREAD

**Issue by juek** [scssphp/scssphp#123]
I'm looking for a way to get all the Scss variables and their ultimate values that occur during compilation. Not only the ones set using setVariables() but also the ones from all the sources. 

From checking the docs and code, I think this could be possible with registerFunction(), but I haven't tried it yet.

So my question is: Has anyone already done this or can someone point me in the right direction? Thanks in advance!

**Comment by robocoder** [comment]
Variables aren't tied to sources.

Your best option is to subclass (extend) the Compiler class.
