### ISSUE TITLE
CRITICAL Allowed memory size

### ISSUE THREAD

**Issue by STV11C** [scssphp/scssphp#124]
Hi guys,

I've been using SCSS PHP for a while now and just started getting this error which happens about 90% of the time on a Save/Compile. After a page refresh is Saves/Compilers successfully.

`CRITICAL Allowed memory size of 67108864 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/wp-content/themes/gutenize/vendor/scssphp-1.1.1/src/Compiler.php on line 477`

Please see screenshot attached of Console error in Chrome. It may not actually be SCSS PHP but thought to check.

Also just wanted to say thanks for maintaining this great project! :) Cheers.

<img width="663" alt="Capture" src="https://user-images.githubusercontent.com/5532744/87870334-38c22800-c9ea-11ea-968f-00382a0107fc.PNG">

**Comment by robocoder** [comment]
You'll want to see if you can increase the max memory limit. You might be able to lower the WordPress memory footprint by disabling/uninstalling unused plugins.

**Comment by STV11C** [comment]
Hi @robocoder - yes you are correct that it was the max memory limit. I added a few extra variables which seems to tip it over.
Besides increasing the memory on the server, do you have any tips/suggestions to reduce the mem usage on a Save/Compile when using SCSS PHP? Cheers
