### ISSUE TITLE
[RFC] Drop the old ScssTest running the ruby tests

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#133]
While trying to improve the compatibility of the parsing of comments with sass-spec, I found out that my change was making some test from ScssTest failing.
ScssTest is running tests extracted from ruby-sass (at an unknown revision, but probably the latest stable as it was updated in https://github.com/scssphp/scssphp/commit/2e5e474b0495fbd3b7e44781460cfdd53b3142f2 after the archival of the repository). Given that ruby-sass is no longer the reference implementation, and is not even maintained, I'm wondering whether it still makes sense to use its testsuite.

**Comment by Cerdic** [comment]
Note that (at least a part of) old tests are included in Sass-spec in https://github.com/sass/sass-spec/tree/master/spec/non_conformant/scss-tests

**Comment by stof** [comment]
yeah, of course. That's also a reason to avoid running that twice, especially given that the ruby tests are not maintained anymore and so they might diverge if sass-spec evolves.
