### ISSUE TITLE
Travis status is not reported anymore on PRs

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#136]
Looking at Travis, builds are running properly, so the webhook is still configured.
From my experience, this looks like an authentication issue forbidding Travis from using the Github API to set the status. To solve that, a maintainer should login on Travis again so that they get a fresh API token.

**Comment by robocoder** [comment]
Probably because it's using the Travis-CI legacy integration rather than the webhook. I've added the Github App for Travis-CI but it's spinning on the redirect page... I'll sort this out later tonight.

**Comment by robocoder** [comment]
Thank you. Looks like it's working.
