### ISSUE TITLE
nested imports - @import statements wont work

### ISSUE THREAD

**Issue by nattyluke** [scssphp/scssphp#14]
First of all thanks for your great work.
I noticed @import rules dont get interpreted. Is this not possible, or am i doing something wrong?
Thanks for the information.

**Comment by robocoder** [comment]
You have to `addImportPath()` or `setImportPaths()`. If `scssphp` can't find the file, the `@import` can't be interpreted.

**Comment by nattyluke** [comment]
not working. importing style like
echo $scss->compile('
  @import "style"
');
is working but my import statements in the file style.scss are not interpreted

**Comment by Cerdic** [comment]
You need to give some more information, like an larger extract of code or a reproductible sample.

`@import` is working nicely as far as I know, and the unit tesing that includes some `@import` parts is fulfilled 
https://github.com/scssphp/scssphp/blob/master/tests/inputs/import.scss
https://github.com/scssphp/scssphp/blob/master/tests/outputs/import.css

**Comment by nattyluke** [comment]
my style.php looks like this:
`
$scss = new Compiler();
$scss->addImportPath("../../scss");
$formatterName = 'ScssPhp\ScssPhp\Formatter\Crunched';
$scss->setFormatter($formatterName);

echo $scss->compile('
  @import "style"
');
`

which loads my style.scss from my folder "../../scss"
in my style.scss i want to load _vars.scss from the same directory.
But the compiled css just prints the import statement:
@import "vars"

**Comment by nattyluke** [comment]
oh my problem i forget the semicolon ';' sorry for bothering

**Comment by emil-totev** [comment]
I think that if the imported file cannot be found, that should normally produce a fatal error. The cases when an import should be left unprocessed are defined in the SASS [documentation](https://sass-lang.com/documentation/at-rules/import#plain-css-imports).
It would be also nice to be able to omit the file extension or the '_' prefix for partials, as described there. Also relative imports (in the directory of the currently processed file) could be made easier.

**Comment by emil-totev** [comment]
OK I was partially wrong - the partials and extension-less imports obviously work OK. The problem remains however with the logic to "pass through"  the import directive when the file is not found.  Except in the cases in the document linked above, 'file not found' must be a fatal error.
