### ISSUE TITLE
[RFC] Drop support for configuring the number precision

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#141]
The number precision is currently configurable, but this involves some global state shared between all compiler instances (while the API hides that).
I looked at dart-sass, and it does not actually support configuring the precision. It is hardcoded to `10`, which is high enough to avoid rounding issues in all browsers (contrary to libsass which used to default to `5`, even though they changed it 2 years ago when dart-sass became the reference).

To me, the easiest way to get rid of the shared global state would actually be to drop support for this configuration:
- create a `Number::PRECISION` constant
- mark the public property `Number::$precision` as deprecated and stop using it (using the constant instead)
- turn `\ScssPhp\ScssPhp\Compiler::setNumberPrecision` into a no-op and deprecated it.

what do you think @Cerdic ?

**Comment by robocoder** [comment]
+1 Being able to set precision came from Ruby sass.
