### ISSUE TITLE
The handling of / is not spec compliant

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#146]
Lots of specs are failing because `/` always computes a division, while it should not be the case (and both libsass and dart-sass agree on this)

**Comment by Cerdic** [comment]
Yes we use some empirical rule instead of the sasslang heuristic 
https://sass-lang.com/documentation/operators/numeric#slash-separated-values

**Comment by navindex** [comment]
For example the media query `@media (min-aspect-ratio: 5/8)` will be translated  to `@media (min-aspect-ratio: 0.625)` and it will be completely ignored by Chrome.

**Comment by navindex** [comment]
For those who have a similar issue: `@media (unquote("#{5}/#{8}"))` workaround helped. I expected the `#{5}/#{8}` expression will be translated to `5/8`, however, it didn't work.

**Comment by stof** [comment]
> I expected the `#{5}/#{8}` expression will be translated to `5/8`, however, it didn't work.

yeah, because our implementation of interpolation is not spec compliant either...
