### ISSUE TITLE
The handling of escape sequences is not spec compliant

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#149]
Currently, they are stored in the string representation directly rather than being parsed. This causes several issues:

- double escaping in some cases
- missing escaping in the output in some cases
- wrong interpolation in some cases
- wrong result for string-manipulating functions

**Comment by stof** [comment]
I have an in-progress refactoring solving many of these cases, but it currently breaks `basic/06_nesting_and_comments` and `basic/42_css_imports`

**Comment by Cerdic** [comment]
Seems fixed thanks to your refactoring and somme additional fixes
5a8b113d 04948e20 f810ddcc 84b8a009 d301b16f 95ef07d8 11247dd9
