### ISSUE TITLE
[RFC] Remove the ignoreErrors feature

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#154]
The compiler currently has a `ignoreErrors` flag (disabled by default), which will silently ignore any error and continue the processing.
In practice, this can have several outcomes:
- you get a PHP error (ranging from a notice to a fatal error depending on the cases) on one of the following PHP statements, which will still break things for your but without any context about how to solve things, as this gets reported as an error in the compiler, not as an error in your source
- you still get some output, but without any guarantee about what it is (or whether it is even valid CSS syntax)
- I think it is even possible to make the compiler enter into an infinite loop for some of these places, but I haven't tried it to be sure.
We should also note that the behavior when ignoring errors is totally untested (on purpose, as it is actually impossible to make guarantees on the behavior as the Sass spec does not have such error recovery mechanism).

This flag could actually be named `runTotallyBrokenUntestedCompiler` instead, which would better reflect its reality.

Neither `dart-sass` nor `libsass` nor `ruby-sass` have an equivalent feature (and that's quite logical in the case of `dart-sass`, as such code would not even compile).

This feature also has a cost for maintenance IMO: any call to `$this->throwError()` still has to account for what happens when it does not actually throw an error (totally confusing given its name).

It also makes it impossible to try using static analysis on such code (not that the rest of the code is ready for that either, with the usage of arrays everywhere anyway, but that does not help), as any static analyser (be it PHPStan, Psalm, your IDE or the XDebug path/branch coverage) will then report about the buggy code path happening when disabling errors (and even if we remove the `ignoreErrors` flag, the analyser might not always be smart enough to recognise it always throw). A common pattern I saw in parser wanting to centralize the instantiation of errors is to rely on a factory method *returning* the exception instead of throwing it. `$this->throwError($args);` would then be replaced with `throw $this->error($args)`, which solves all the path analysis issues about know that this code path throws and ends there. But this replacement API is incompatible with the `ignoreErrors` which should be removed first.

To me, `ignoreErrors` should be removed (the setter might be kept as deprecated if needed, but it should be a noop). what do you think ?

**Comment by Cerdic** [comment]
I think this `ignoreErrors` flag is a legacy thing that definitely can be removed.

Now the main interrest of the `throwError()` function is to forge the error message including the location of error and the trace, but I guess this could be achieved as you are proposing with a 
`throw $this->error("Error")`

so go for it!
