### ISSUE TITLE
Color math should be deprecated

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#161]
see https://github.com/sass/sass/issues/2144

We might want to first report a deprecation warning in a release, and actually remove it only in the next one, but that's to be discussed.

**Comment by stof** [comment]
See https://github.com/sass/sass/issues/2501#issuecomment-501016036 for an example of why color math was removed due to being confusing.

**Comment by stof** [comment]
@Cerdic @robocoder what is your opinion on this ? Should we keep it with a warning at first or directly go for the removal ?

**Comment by Cerdic** [comment]
As this is breaking compatibility I don't think it should be removed immediately, and we should at least start with a deprecation warning

**Comment by robocoder** [comment]
deprecation warning
