### ISSUE TITLE
[RFC] Deprecate formatters other than expanded and compressed

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#162]
dart-sass only supports the `expanded` and `compressed` output styles.
If we refactor the library based on the architecture of dart-sass in the future (to work towards modules), it might be a lot easier if we don't have to deal with customizable formatters either.

The default formatter should also be changed from `nested` to `expanded`

**Comment by robocoder** [comment]
I'm ok with deprecating the other formatters.

**Comment by stof** [comment]
Proposal here: deprecate `Compiler::setFormatter` in favor of a simpler `Compiler::setCompressed(bool)` or `Compiler::setOutputStyle(OutputStyle::EXPANDED | OutputStyle::COMPRESSED)` API.
the current `setFormatter` API does not only allow to choose among our other (to-be-deprecated) formatters but also to inject custom ones, which actually means that the messy `OutputBlock` datastructure is kind-of public API.

**Comment by stof** [comment]
@robocoder @Cerdic any preference between `setCompressed` and `setOutputStyle` ?

**Comment by robocoder** [comment]
I prefer setOutputStyle().

**Comment by stof** [comment]
Advantage of `setOutputStyle`: it is more consistent with the dart-sass API.

**Comment by mahagr** [comment]
I'm good, too. You really just need one format for development and another for production.
