### ISSUE TITLE
PHP 7.4.x issues

### ISSUE THREAD

**Issue by robocoder** [scssphp/scssphp#163]
I was looking at updating travis from the 7.4-nightly and noticed a couple of recent regressions.
* https://travis-ci.org/github/scssphp/scssphp/jobs/721396651

These appear to be the source commits:
* eed25c20 introduced 60 errors and 2 failures
* 665d78b0 introduced 46 errors

**Comment by Cerdic** [comment]
ah shit sorry on that :/
I will try to dig in that and fix it before it's worse

**Comment by Cerdic** [comment]
ok got it, hopefuly was not a big deal :)

**Comment by robocoder** [comment]
Thanks. =)
