### ISSUE TITLE
Double backslash in CSS output

### ISSUE THREAD

**Issue by STV11C** [scssphp/scssphp#164]
Hi guys, I just downloaded the latest v1.2 and noticed that there are two slashes rendered now for the following:
**SCSS**
`content: "#{$opt-sidebar-list-icon}";`
**Output**
`content: "\\f105";`

Regards
Stephan

**Comment by Cerdic** [comment]
Hi! 
Can you provide a full test case? 
I mean with the variable initialisation

**Comment by STV11C** [comment]
Hi @Cerdic 

Thanks for getting back to me so quickly.

I am using the Redux Framework to get the value (e.g. '\f105'), then storing it in a variable (e.g. $opt-sidebar-list-icon), then compiling the SCSSPHP on the Redux Framework Save function.

It has worked fine on all previous versions of SCSSPHP except for this latest version. I hope that helps.

Regards
Stephan

**Comment by Cerdic** [comment]
Je ne reproduis pas le problème : 

* Sur SassMeister https://www.sassmeister.com/
```
$opt-sidebar-list-icon : '\01F354';
.test {
  content: "#{$opt-sidebar-list-icon}";
}
```

me donne bien le burger

<img width="347" alt="Capture d’écran 2020-08-28 à 17 07 32" src="https://user-images.githubusercontent.com/342805/91583114-04c71480-e951-11ea-9f13-21473bc4ab51.png">

Et avec Scssphp, en ligne de commande : 

```
$ cat t/t164.scss
$opt-sidebar-list-icon : '\01F354';
.test {
  content: "#{$opt-sidebar-list-icon}";
}
```

```
$ ./bin/pscss t/t164.scss
.test {
  content: "🍔"; }
```

J'ai aussi le burger bien encodé

**Comment by robocoder** [comment]
@STV11C scssphp 1.2 fixed some escaping issues, so your code now has to store the value in double-quoted string.

**Comment by Cerdic** [comment]
(sorry I anwsered in french cause doing 2 things in the same time)

**Comment by STV11C** [comment]
Hi @Cerdic and @robocoder 
I was able to successfully produce the hamburger icon test by placing the variable inside the SCSS as done by @Cerdic .

See below for how I am storing my FontAwesome unicodes using an array.
I assume this is the problem here?
I'm just trying to work out why the extra slash is being placed and where I need to fix it.
Any help would be appreciated as I'd like to keep up to date with your releases. Thanks
```
function fontawesome_free_5_list_unicode() {
  return array(
    '\f103' => 'fas fa-angle-double-down'
  )
}
```

**Comment by Cerdic** [comment]
Hi!
I’m not fully understanding what you are doing and how to reproduce your issue.

Again having a simple test case that allow to reproduce is already half of the problem solved, so that would be really helpful

**Comment by STV11C** [comment]
Hi, I will try to get a simple test case without needing Redux Framework etc so you can test properly, but I will try to explain my case.

A user selects an icon from a dropdown menu in my Redux Framework theme options, which the dropdown options are populated from a function which includes an array - like the example in the function in my previous message.

The array value is stored in a variable (e.g. $opt-sidebar-list-icon) which is used to compiled using SCSSPHP.

Does that help?

**Comment by Cerdic** [comment]
Variables passed to the compiler are parsed as is, the same way it would as if written in the plain scss.file.

So if you are initializing you variable like this in the PHP part:
```
$scss->SetVariables( ['opt-sidebar-list-icon' => '\f103']);
```
then this is equivalent as writting 
```
$opt-sidebar-list-icon: \f103;
```
and thus parsed as a keyword, not as a string, and the ouput will have a double `\\` indeed.

But if you are writting the right way:
```
$scss->SetVariables( ['opt-sidebar-list-icon' => '"\f103"']);
```
this will be parsed as a string and have the right format at the end.

I think you should dig in that direction. 
If this is the cause of your issue, you was just lucky it worked before because of a wrong escaping management in the parser&compiler :)

**Comment by STV11C** [comment]
@Cerdic Thank you for the detailed description and I think you are correct. I will attempt the fix shortly and confirmed all worked. Cheers!

**Comment by Cerdic** [comment]
Making some additional tests for #166 I can see that

```
.test{
  content: \f103;
  content: "\f103";
}
```

is producing the same result (besides the quotes) on https://www.sassmeister.com/ : 

```
@charset "UTF-8";
.test {
  content: ;
  content: "";
}
```

whereas scss is returnin
```
.test {
  content: \f103;
  content: ""; }
```

So looks like the parsing as a keyword vs string is now making a difference, which should not happen and could explain your issue, because of some keyword to string conversion in between.

**Comment by STV11C** [comment]
Hi @Cerdic, just checking if you are planning of fixing this soon? Thanks

**Comment by Cerdic** [comment]
@STV11C sorry no fix to be expected in the near future. I had a quick look and the issue is more complicated than expected as the escaping we processing on strings is not fully compliant and thus apllying it to keywords breaks a lot of test cases.
So this is a work in progress for now

**Comment by Cerdic** [comment]
Hi, this issue is finaly solved for the ScssPHP part.
The compilation of
```
.test{
  content: \f103;
  content: "\f103";
}
```
now gives the expected
```
@charset "UTF-8";
.test {
  content: ;
  content: ""; 
}
```

this is linked to the commits a82475a0 403678a0 f895919a 22c5a68c dffb7e74 3f47ffb4 f7910e62 445117b8 efcc3343
