### ISSUE TITLE
Escape sequence not working in 1.2

### ISSUE THREAD

**Issue by greew** [scssphp/scssphp#166]
Hi all!

First of all, this problem might be related to #164 and the refactoring of escape sequences. 

After upgrading from 1.1.1 to 1.2, our custom icons doesn't work anymore.

A quick scss file:
```
.test {
	content: "\e604"; 
}
```

In 1.1.1, the output was:
```
/* compiled by scssphp 1.1.1 on Mon, 31 Aug 2020 11:53:56 +0000 (0.0141s) */

.test{content:"\e604"}
```

But in 1.2 the output now is:
```
/* compiled by scssphp 1.2 on Mon, 31 Aug 2020 11:49:41 +0000 (0.006s) */

.test{content:"î˜„"}
```

The new content is output as plain text and not as an escape sequence as intended, hence the browser cannot find the correct icon.

If this is not an error, but an intended use case, can you please point me in the right direction of how to use escaped sequences in SCSS and parse them directly to CSS without manipulating them.

Best regards
/Jesper

**Comment by Cerdic** [comment]
Hi! did you have a look at #164?

**Comment by Cerdic** [comment]
Sorry, I mean more specificaly https://github.com/scssphp/scssphp/issues/164#issuecomment-683656387

**Comment by Cerdic** [comment]
With you test case I'm getting
```
.test {
  content: ""; }
```

which is the same result as the one you can get with https://www.sassmeister.com/ and the expected result according to the spec

**Comment by greew** [comment]
Hi @Cerdic 

Thank you for your input! :+1: 

I did read #164, but didn't find any help there.

Which might be because of a totally other problem: The system I'm trying to fix, is a legacy system running with charset: Windows-1252. 

No matter how much I try, that will not be fixed by your library ;)

I'll find another way around - thanks for you time! :)

/Jesper
