### ISSUE TITLE
scssphp causing Mobile-Friendly Test and Search Console Errors

### ISSUE THREAD

**Issue by andrewatduckpin** [scssphp/scssphp#17]
We're using scssphp in production and are finding that the sites using it are getting errors in Google Search Console and Google Mobile-Friendly Test. When viewing the Google Search Console screenshot, the page appears to be missing the stylesheet entirely.

Mobile-Friendly Test reports the following error:
URL: mysitehere.com/assets/styles/style.php/style.scss
Error: Redirection Error

It looks like Google Bot doesn't like the "style.php" in the stylesheet url, leaving Google bot to view the site without a stylesheet at all. 

Any workarounds for this?

**Comment by robocoder** [comment]
I find the Googlebot smartphone screenshot isn't even close to what my live sites look like on a real Android device. (This is independent of whether or not the site uses `scssphp`.)

I don't know what your `style.php` script does. If it's based on the `Server.php` example, then it's unlikely the cause since it never returns a redirect response.

What you could do is compile your `style.scss` from the command-line, and then try to serve it statically, e.g.,

> URL: mysitehere.com/assets/styles/style.css

**Comment by andrewatduckpin** [comment]
> I find the Googlebot smartphone screenshot isn't even close to what my live sites look like on a real Android device. (This is independent of whether or not the site uses scssphp.)

I agree, but if Google is using this as part of it's ranking algorithm, we're taking a hit due to being considered "not mobile friendly". We're only experiencing these issues on sites using scssphp.

> I don't know what your style.php script does. If it's based on the Server.php example, then it's unlikely the cause since it never returns a redirect response.

See below:
```
require_once("../../../../../wp-load.php");
$init_main_color = !empty(site_ops_brand_color(false)) ? site_ops_brand_color(false) : '#d93';
$init_heading_font = !empty(site_ops_heading_font(false)) ? site_ops_heading_font(false) : 'Raleway';
$init_body_font = !empty(site_ops_body_font(false)) ? site_ops_body_font(false) : 'Karla';
$init_button_style = !empty(site_ops_buttons_style(false)) ? site_ops_buttons_style(false) : '3px';
$init_headline_case = !empty(site_ops_headline_case(false)) ? site_ops_headline_case(false) : 'uppercase';

require_once  __DIR__ . '/../../inc/libs/scssphp/scss.inc.php';
require_once  __DIR__ . '/../../inc/libs/scssphp/example/Server.php';
use Leafo\ScssPhp\Compiler;
use Leafo\ScssPhp\Server;
$directory = __DIR__ ;

$scss = new Compiler();
$scss->setVariables(array(
    'main-color' => $init_main_color,
    'heading-font' => $init_heading_font,
    'body-font' => $init_body_font,
    'buttons-style' => $init_button_style,
    'headline-case' => $init_headline_case,
));
$scss->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
$scss->setImportPaths($directory);
$scss->setLineNumberStyle(Compiler::LINE_COMMENTS);

$server = new Server($directory, null, $scss);
$server->serve();
```

> What you could do is compile your style.scss from the command-line, and then try to serve it statically

The reason we are using this is to pull site options from the mySQL db and "inject" them into the stylesheet. The site options are controlled by the customer, which is why we're not just compiling locally.

Would it be possible to trigger this to re-compile each time site options are updated by our customer? Then compile to a specific directory, where we'd use a typical stylesheet path?

**Comment by robocoder** [comment]
>I agree, but if Google is using this as part of it's ranking algorithm, we're taking a hit due to being considered "not mobile friendly". We're only experiencing these issues on sites using scssphp.

Check to see if you have rewrite rules that would account for the redirect.

Also, try to `tail` your web server access log and in Search Console, enter the stylesheet URL for URL inspection, to troubleshoot what's happening in the request/response.

>Would it be possible to trigger this to re-compile each time site options are updated by our customer? Then compile to a specific directory, where we'd use a typical stylesheet path?

You're welcome to customize the `Server.php` example to suit your needs. The plan is to spin this off to its own repo, so we're not accepting any feature PRs to that class for the time being.

**Comment by robocoder** [comment]
It looks like the Googlebot also fetches `robots.txt`. You might want to make sure that `mysitehere.com/assets/styles/` Disallowed.
