### ISSUE TITLE
Windows directories with backslashes break compile function

### ISSUE THREAD

**Issue by Der-Alex** [scssphp/scssphp#171]
Hi. We have some developers that use Windows systems. Two weeks ago, we changed the leafo/scssphp library with scssphp/scssphp and things began to break on the Windows machines. 

After some debugging, I realized that it has something to do with backslashes inside the Windows folder structure. In our project we generate the path to our scss files and use the `DIRECTORY_SEPARATOR` constant, that uses "\\" on Windows systems. That path will be written as an @import statement inside a main.scss file. When that file gets compiled with the `$scss->compile(...)` function, we get the following error: 

```php 
Fatal error:  Uncaught ScssPhp\ScssPhp\Exception\CompilerException: `componentsh1.scss` file not found for @import: main.scss on line 1, at column 0
Call Stack:
#0 import main.scss (unknown file) on line 1 in \vendor\scssphp\scssphp\src\Compiler.php:5081
```
I guess that scssphp internally uses single quotes when compiling the content inside the scss files. 
To reproduce the error I created a small repo. You can clone it and follow the instructions at the readme file. 

https://github.com/Der-Alex/scssphp-backslash-test

Right now, we simply fix the error by replacing the backslashes with forward slashes. But I guess it would be great, if this can also be fixed inside the library as well. 

If more info is needed, then please let me know.

**Comment by Cerdic** [comment]
I think it's just because in a string `\` should be escaped like this:
```
@import "component\\h1";
```

The escaping in string was not well handled until recently, so I guess it was just luckily working in leafo/scssphp, but not compliant with sass string handling, so no more working in scssphp neither

**Comment by Cerdic** [comment]
I'm closing the issue as no more information
