### ISSUE TITLE
Support of CSS4 (?) `/foo/` selector?

### ISSUE THREAD

**Issue by Cerdic** [scssphp/scssphp#178]
Following #175 
the line
https://github.com/scssphp/scssphp/blob/master/src/Parser.php#L3390

is only useful for handling the selector `E /foo/ F`
https://github.com/scssphp/scssphp/blame/master/tests/inputs/selectors.scss#L88
added by 95d1871d01c506444aded4fc3489a4f181918ca2

But I cannot find any documentation about this CSS4 selector. 
I have the feeling it is coming from a past future specification.

Should we keep this support, or simply delete it?
FYI Sassmeister is refusing to handle this selector `E /foo/ F`  considering this is an error.

**Comment by stof** [comment]
this is indeed part of an older version of the spec. The shadow-piercing combinator was dropped from the draft spec in 2015 and from Chrome in 2017: https://developers.google.com/web/updates/2017/10/remove-shadow-piercing

**Comment by stof** [comment]
IMO, if the official sass does not support such selectors, we should drop support too.

**Comment by Cerdic** [comment]
This is fixed. It's even worse than said as there is a test in the sass-spec ensuring the parser will throw an error on this selector, which is now happening :)
