### ISSUE TITLE
[RFC] Deprecate line number in favor of source maps

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#180]
The library currently implements support for line numbers, rendered either as comments or a `@media -sass-debug-info` (for the old unmaintained and incompatible FireSass Firefox addon). This is coming from features of the old ruby-sass before sourcemaps became a thing in browsers.
Today, it does not make sense to use these features. All browsers have native support for source maps, and Scssphp is able to provide source maps too. And dart-sass does not have support for them either.

My suggestion is to deprecate them (throwing a deprecation warning in `Compiler::setLineNumberStyle`) and then remove the feature entirely.
An alternative to simplify the code could even be to drop the feature immediately, keeping only the deprecated setter but ignoring any line number style being set (similar to what we did for the configurable number precision, which was removed immediately in favor of using the high precision used by dart-sass).

**Comment by robocoder** [comment]
+1 for the alternative
