### ISSUE TITLE
Scssphp defines a non-standard spaceship operator

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#187]
The `<=>` operator does not exist in dart-sass and does not appear anywhere in sass-spec.
Scssphp implements such an operator on numbers.

**Comment by stof** [comment]
For reference, it has been added in https://github.com/scssphp/scssphp/commit/c9fdc3d0945b76ea77e90b0ef590ea6dc55ac68e

**Comment by robocoder** [comment]
Experimental commit. Can be removed since they chose not to implement in ruby sass.

**Comment by stof** [comment]
I'll work on it once #188 is merged, to avoid conflicts.
