### ISSUE TITLE
Tests fail on Travis (PHP 5.6 and 7.2) on charset and null char

### ISSUE THREAD

**Issue by Cerdic** [scssphp/scssphp#189]
Related to https://github.com/scssphp/scssphp/pull/184#issuecomment-716968118

Sorry for the inconvenience @stof I could indeed have used a PR here as I fully worked on a branch. 
I'm running the test with PHP 7.2 on my dev env and this is clearly working. 

It looks definitely like a weird edge case - maybe two in facts as errors in Travis PHP 5.6 seems related to charset, whereas errors on PHP 7.2 seems related to null char.

In addition the strange thing is that I had no notification from Travis to warn me of this failure, otherwise I would have had a look asap.

**Comment by stof** [comment]
for the charset failure on PHP 5.6, there is a weird thing going on. the output actually looks like that:

```
content: "\\u{FFFD}";
```

Notice the double `\`. So this might be an escaping issue rather than a charset issue.

**Comment by stof** [comment]
And the failing tests on PHP 7.4 builds are also related to escaping

**Comment by stof** [comment]
The issue on PHP 5.6 is caused by https://3v4l.org/f2q5N
The change in https://github.com/scssphp/scssphp/commit/f7910e624a9325c227a749a8cdb921ca25e88393 only made this bug happen in a case covered by sass-spec

**Comment by Cerdic** [comment]
hopefully solved by @stof with #196 and #197
