### ISSUE TITLE
Array passed to substr() in Formatter/Expanded.php on Line 57

### ISSUE THREAD

**Issue by fabsn182** [scssphp/scssphp#19]
In rare edge-cases, the Expanded Formatter Class failes because the variable `$line` contains an array, not a string:

```
substr() expects parameter 1 to be string, array given
Filename: Formatter/Expanded.php
Line Number: 57
```

This happened after I added block comments to remove a part of my code inside the Jacket-Mixin (https://github.com/at-import/jacket/blob/master/stylesheets/_jacket.scss)

SCSS:
```
/*.LinkLabel {
	position:absolute;
	right:0;
	bottom:#{$gi_element_padding_vertical}px;
	left:0;
	z-index:4;

	@include transition(bottom .3s ease-in-out);

	@extend %LinkIcon;
}*/
```

Dumped Array:
```
array(3) {
  [0]=>
  string(6) "string"
  [1]=>
  string(0) ""
  [2]=>
  array(3) {
    [0]=>
    string(62) "/*.LinkLabel {
				position:absolute;
				right:0;
				bottom:"
    [1]=>
    array(4) {
      [0]=>
      string(11) "interpolate"
      [1]=>
      array(2) {
        [0]=>
        string(3) "var"
        [1]=>
        string(27) "gi_element_padding_vertical"
      }
      [2]=>
      string(0) ""
      [3]=>
      string(0) ""
    }
    [2]=>
    string(111) "px;
				left:0;
				z-index:4;

				@include transition(bottom .3s ease-in-out);

				@extend %LinkIcon;
			}*/"
  }
}
```

I quickly added a check on line 57 but had no time to investigate any further:
```php
if (!is_string($line)) continue;
```

**Comment by Cerdic** [comment]
This seems linked to https://github.com/leafo/scssphp/pull/702 and interpolation in comments
I guess I forgot the evaluation in some cases - would be nice to have a minimal test case to trace where this is happening

**Comment by fabsn182** [comment]
Testcase:

foo.scss
```scss
$foo:10;
@import 'test';
```

_test.scss
```scss
.class {
	/*.foo {
		font-size:#{$foo}px;
	}*/
}
```

This only happens when 
- the block comment is at least in level 2 -- moving the comment out of .class will not cause this error

AND
- the block comment contains a variable, formatted using `#{}` -- removing the braces will not cause this error

**Comment by Cerdic** [comment]
Sorry I was not able to look on before!
As a matter of fact, even without `@import` it was failing:
```
$foo:10;
.class {
	/*.foo {
		font-size:#{$foo}px;
	}*/
}
```

This is now fixed :)
