### ISSUE TITLE
LibSass is Deprecated

### ISSUE THREAD

**Issue by astridx** [scssphp/scssphp#191]
As I saw [this](https://github.com/scssphp/scssphp/blob/243a16a35f404dd2c546192f5cd9d184a8a26d34/src/Compiler.php#L5828) I wonder, if the depreciation of LibSass has impact of this repo?
https://sass-lang.com/blog/libsass-is-deprecated

Thank you for this repo that has often helped me. Now I have a question

**Comment by stof** [comment]
This repo does not rely on libsass, so it is not directly impacted.
And the discussion in #145 shows that there is still an interest in a pure PHP implementation of sass so it is not planned to deprecate scssphp.
Lots of work is happening right now to increase the spec compliance of Scssphp to bring it closer to dart-sass (support for Sass modules will take a long time to happen though, as lots of other things need to be done first and it is a huge work. Follow #55 to track this)

**Comment by astridx** [comment]
Thank you very much for your answer.
