### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#192]
Travis CI is in the process of deprecating the travis-ci.org infrastructure in favor of running public repositories on travis-ci.com as well.
A few days ago, they reduced the capacity of travis-ci.org, leading to jobs waiting longer in the queue.

It would be great to migrate to get less wait time. The instructions are at https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg

**Comment by stof** [comment]
See the changes in backlog at https://www.traviscistatus.com/#month:

![image](https://user-images.githubusercontent.com/439401/97296395-e4341180-1850-11eb-9081-f552e9341930.png)

**Comment by robocoder** [comment]
I kicked off the migration. It's supposedly transparent and doesn't require any .travis.yml changes. Will check on status after I get the confirmation email.

**Comment by stof** [comment]
yeah, the only change we'll need is updating the badge in the readme.
