### ISSUE TITLE
[RFC] Move the website doc to the main branch

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#199]
Currently, https://scssphp.github.io/scssphp/ is deployed based on the `gh-pages` branch. This makes this documentation less visible to contributors and easy to forget when doing changes. It also means that it has to be updated in separate PRs.

Given that GitHub now supports deploying pages from a `docs` folder in the default branch of the repository, I suggest migrating to that approach (excluding the folder from git archives) to make it easier to contribute to the doc.

**Comment by robocoder** [comment]
Sure.
