### ISSUE TITLE
Refactor (example) Server class

### ISSUE THREAD

**Issue by robocoder** [scssphp/scssphp#2]
Copied from: https://github.com/leafo/scssphp/issues/333

Rationale:
- the Server class is getting bloated
- the Server class has too many public functions:
  - compileFile() - always recompiles
  - checkedCompile() - compiles scss if cache doesn't exist
  - checkCachedCompile() - recompiles if necessary
  - serve() - the original purpose of this class

Identified candidate cache implementations:
- never - no caching; always (re)compiles
- read - read only if cache exists; doesn't create
- once - compiles only if cache doesn't exist
- surface/shallow - recompile if main .scss file changes (note: this has no current API equivalent)
- deep - recompile if main .scss file or any of its imports changes

Technical considerations:
- bust up the Server class
- Cache/*.php implementations
- "deep" should detect changes in setVariables() and setImportPaths()

Other changes:
- make Compiler cache aware (also, see existing importCache)
- stale file detection using algorithm instead of metadata leafo/scssphp#321
- parse tree cache leafo/scssphp#328
- register custom error handler leafo/scssphp#330
- register custom input finder leafo/scssphp#329
- option to set/override or remove comment "compiled by scssphp..." leafo/scssphp#477
- option to compress (gzip) output leafo/scssphp#483

**Comment by robocoder** [comment]
Now that we have a new organization, we can also move the example Server class to its own repo (and package? e.g., scssphp/server)

That'll allow it to have its own composer.json and a dependency on scssphp/scssphp package.

**Comment by nicolasricci** [comment]
Hi @robocoder,

First of all thanks for creating this great project! 

Do you have any sort of time-frame for the release of a standalone package for the Server class?

Keep up the good work!

**Comment by robocoder** [comment]
Repo:
* https://github.com/scssphp/server

Packagist:
* https://packagist.org/packages/scssphp/server
