### ISSUE TITLE
Import SCSS file with dynamic path using Server Class

### ISSUE THREAD

**Issue by LrntL** [scssphp/scssphp#20]
Hi !

Here is my  problem. I use Server Class to import and compile all my css files, like this:
```
include $_SERVER['DOCUMENT_ROOT'].'/../inc/inc.php';
include_once DIR_ROOT.'/vendor/autoload.php';
require_once "./Server.php";
use Leafo\ScssPhp\Server;

$directory = $_SERVER['DOCUMENT_ROOT']."/css";

$server = new Server($directory);
$server->serve();
```

Through my back office, I create a file with custom variables values (eg. Text color, etc.)
This file is stored in a dynamic folder (domain name in $_SERVER['DOCUMENT_ROOT']."/data/domain.tld/theme/theme.scss").

So I have a main scss file with all the files to import and compiles.
Is there a way to telle in this file to import the "dynamic" theme.scss file ?

Example of what I am trying to do in my main scss file:
```
[...]
@import "aos.css";
@import "variables";
@import "../../data/[[HERE_MY_DOMAIN]]/theme/theme";
@import "framework";
[...]
```

As you can imagine, I have multiple domain and each has a custom theme file containing variables. These variables overwrite the default values.

Note: it is working if I write the full path of this theme file, I just need to use a (PHP?) variable to set [[HERE_MY_DOMAIN]] dynamically in my main scss file

Hope all this is understandable...
Thank you for your help.

Lrnt

**Comment by robocoder** [comment]
Have you tried setImportPath and/or setVariables?

**Comment by LrntL** [comment]
Thank you @robocoder !

I have this path in a PHP variable.
I need to do, in my main scss file, something like :
`@import "<?php echo $pathToMyFile?>/theme.scss";`

I don't know how to use `setVariable()` to do this :/
Or where to write `setVariable()`...

For the details:

- I  use `scss.php?p=styles.scss`
- In `styles.scss`, I have got this:
```
[...]
@import "aos.css";
@import "variables";
@import "framework";
[...]
```
- I need to include `theme.scss` after `@import "variables";` with something similar to this:
`@import <?php echo $dynamicPathDefinedEarlier; ?>"/theme/theme";`

I don't know if I can do this directly in my main `styles.scss` file.
As you can see, I put the content of `scss.php` in my first post.

**Comment by LrntL** [comment]
I tried to use setVariables().
According to my code, I tried this in `scss_server_class.php`:

```
protected function compile($in, $out)
{
     $start   = microtime(true);
     $this->scss->setVariables(array('themePath' => "my/custom/path")); // <-- I added this
		
     $css     = $this->scss->compile(file_get_contents($in), $in);
     [...]
     return [$css, $etag];
}
```

And what? It is "working"!
I can use @import "#{$themePath}/theme/theme"; in my styles.scss files!

But as you can imagine, I can not let the line `$this->scss->setVariables(array('themePath' => "my/custom/path"))`; in `protected function compile($in, $out)` of `scss_server_class.php`

Is it possible to define this variable in my `scss.php` file or elsewhere?

**Comment by LrntL** [comment]
Note: If I set `$scss` as `public `instead of `private `in `scss_server_class.php`
I can use:
```
$server = new Server($directory);
$server->scss->setVariables(array('themePath' => "../../data/zazi.combo.dev")); 
$server->serve();
```

Is that a problem to set `$scss` as `public ` in `scss_server_class.php`?

**Comment by robocoder** [comment]
The easiest approach is to instantiate the Compiler object (`$scss`), setVariable, and then pass it to the Server object via its constructor (3rd parameter).

**Comment by LrntL** [comment]
As you can see, I'm not really familiar with classes...

And as you are a hero with that, can you please give me an example  to instantiate the Compiler object ($scss), setVariable?

**Comment by robocoder** [comment]
```
use ScssPhp\ScssPhp\Compiler;
use ScssPhp\ScssPhp\Server;

$scss = new Compiler;
$scss->setVariables(array('themePath' => "../../data/zazi.combo.dev"));

$server = new Server($directory, null, $scss);
$server->serve();
```

**Comment by LrntL** [comment]
Thank you! You're genius @robocoder
You made my day! No my week! No my entire year!

**Comment by LrntL** [comment]
I know it's closed but now, when compiling, I have this error:
`Parse error: Undefined variable $screen-lg: /var/www/vhosts...`

Just like my variables.scss file is not processsed. :(

**Comment by robocoder** [comment]
The `$directory` passed  to `Server` doesn't change the working directory. You either have to tweak the themePath, or set the absolute path via `setImportPaths()`.
