### ISSUE TITLE
[RFC] Drop support for old PHP versions

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#202]
Currently, the minimum supported version is PHP 5.6.0.

With work being done to move away from the huge mess of array-based values and use dedicated object instead (see #193), I think it would make sense to be able to declare proper types in these APIs rather than relying on phpdoc alone (which is not enforced by PHP).

Interesting type-related features:

- scalar types: PHP 7.0
- return types: PHP 7.0
- nullable types: PHP 7.1
- variance for signatures: PHP 7.2 (not sure we have a need for that yet. I don't see a need for it in Value objects for instance)
- typed properties: PHP 7.4 (nice-to-have, as our properties will stay private anyway to enforce immutability)
- union types: PHP 8 (useful for numbers, as they are `int|float`, i.e. the dart `num` type)

Clearly, bumping to PHP 8 is a no-go.
Looking at our biggest dependents at https://packagist.org/packages/scssphp/scssphp/dependents?order_by=downloads, I would also exclude PHP 7.4 as most of them are requiring 7.2+ or 7.3+ in their latest version.

Given these constraints, I suggest bumping the min PHP version to either 7.1 or 7.2 to benefit from these features.

What do you think @robocoder @Cerdic ?

**Comment by robocoder** [comment]
The only reason I've avoided type declarations/hints is because of incompatibility across multiple php+phpunit versions.

**Comment by stof** [comment]
I don't see how type declarations in our own code impacts the compatibility with PHPUnit

**Comment by stof** [comment]
I would say that the reason they are avoided today is because it would be `array|Number` almost everywhere today (and that even require a union type)...

**Comment by robocoder** [comment]
I meant In terms of why our unit tests don't use setUp/tearDown. For example, this doesn't work in php 7.0:
```
public funciton setUp() : void
{
...
}
```

**Comment by Cerdic** [comment]
For me this is a sensitive point: I'm using the ScssPHP Compiler in a plugin for a CMS which is having the oposite policy, trying to keep compatibility with old PHP versions as much as possible.
I don't want to enter in this debate here, there is legit reasons for both strategies.

I can live with a minimal PHP version 7.1, maybe with a maintenance branch for PHP 5.6 on which I could fix blocking issues with BootStrap Compilation if any - especialy with the release of BS5 for instance.

But having a higher minimal version would give me a hard time for now.

**Comment by robocoder** [comment]
I'm not a fan of PHP version specific branches and packagist doesn't take into account the projects that contain a snapshot of scssphp. Wordpress still supports php 5.6 and I know there are wordpress plugins that include scssphp, so, I'm inclined to defer this issue.

**Comment by stof** [comment]
OK, then I'll look into using phpstan or psalm to enforce types through static analysis instead, relying on phpdoc for types not supported natively in PHP 5.6.

**Comment by stof** [comment]
I'm closing this as the decision is to keep support for PHP 5.6 for now

**Comment by mahagr** [comment]
Just a late comment: I would love to have PHP 7.1 as the minimum, but I do agree that unfortunately WP still supports PHP 5.6 and we just need to live with it.

**Comment by stof** [comment]
@mahagr as a user of the library, you don't really care if our minmum supported version is lower than yours (you actually cares that it is not higher than yours). the benefit of dropping old PHP versions would actually be for maintainers (as we could rely on newer features if we did).

**Comment by stof** [comment]
> For me this is a sensitive point: I'm using the ScssPHP Compiler in a plugin for a CMS which is having the oposite policy, trying to keep compatibility with old PHP versions as much as possible.

@Cerdic is this plugin open-source, allowing me to see how you extend the Compiler (basically doing the same than #214 but for your plugin) ?

**Comment by Cerdic** [comment]
Yes you can find it here
https://git.spip.net/spip-contrib-extensions/scssphp

**Comment by stof** [comment]
@Cerdic now discussed in #215 :smile:

**Comment by mahagr** [comment]
@stof As a maintainer of a framework which depends on your library, I tend to agree. :)
