### ISSUE TITLE
[RFC] Deprecate the scssphp-glob() function

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#219]
In response to https://github.com/scssphp/scssphp/issues/88, a `scssphp-glob()` function was implemented in scssphp.

To me, this function does not belong to the core (we should not provide any additional features specific to scssphp IMO). It should be registered as a custom function using `registerFunction` (which is totally usable to implement such feature today).
The root cause of #88 is that Contao does not give access to our `registerFunction` method. But that should be solved by requesting the feature to Contao instead, not by making this a scssphp built-in function.

**Comment by havutcuoglu** [comment]
@stof  what is the problem with the glob based import?
`scssphp` compiles all scss files into one file, right?
**So you can only specify the directory and you have saved a lot of time and trouble.** 

It wasn't intended for Contao either, and Contao Project isn't the only CMS that uses `scssphp`. There are other projects that use `scssphp` as well

I think it was and is a very good idea.

**Comment by havutcuoglu** [comment]
But as you say, the Contao team can also implement that. But I thought it would be better if it came straight from the source.

**Comment by stof** [comment]
@havutcuoglu the issue is that it makes the scssphp compiler provide non-standard sass features instead of leaving them to plugins.

**Comment by Cerdic** [comment]
@havutcuoglu moreover, the behaviour of this function is here and now directly linked to your usage in Contao, as the order doesn't matters and it doesn't make a difference between partials `_xxx.scss` vs complete files.

This means that embeding this function in scssphp implies that someday someone will ask for a different way of working for this function, based on his own usage, and we will have to manage that whereas none of the usage are in the scope of ScssPHP and the sass-lang itself.

This is really not our job to implement and maintain non sass-standard features and manage talks about it.
This is already a huge work to try to stick to the spec.
