### ISSUE TITLE
[RFC] Overhaul the cache API

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#237]
The library currently implements a `Cache` that can be used to speed up the compilation. But that implementation is quite limited as it forces a filesystem-based cache.

I suggest providing a pluggable cache API instead, where the underlying storage can be customized. We could keep shipping a filesystem-based implementation (the one we have today, basically) for people using the self-contained library so that they can have  an implementation with no dependency. But I would suggest that we also provide an implementation which relies on a [PSR-6](https://www.php-fig.org/psr/psr-6/) or [PSR-16](https://www.php-fig.org/psr/psr-16/) cache, so that projects can plug whatever cache storage they want there.

**Comment by Cerdic** [comment]
Seems a good idea indeed
I add the link for my own purpose :) https://www.php-fig.org/psr/psr-16/

**Comment by stof** [comment]
I updated the description to mention PSR-6 too, as I'm not sure yet which one would be the best fit here (it might depend how we implement it)

**Comment by stof** [comment]
https://github.com/scssphp/scssphp/issues/222 would help regarding caching too. Currently, if the compilation is a cache hit, `$compiler->getParsedFiles()` is not replaced with the parsed files of the cached compilation. With a stateless API, we would avoid such issues (as we could cache the CompilationResult` object)

**Comment by stof** [comment]
see #316 for a related discussion

**Comment by stof** [comment]
#728 is removing that cache entirely
