### ISSUE TITLE
Suggest armin/scssphp-bundle

### ISSUE THREAD

**Issue by a-r-m-i-n** [scssphp/scssphp#24]
Hi,
my name is Armin and I've written a bundle for Symfony 4 framework, which allows you to use your great scssphp library via framework configuration. Also it provides a Symfony command and a profiler toolbar entry.

https://github.com/a-r-m-i-n/scssphp-bundle/blob/master/README.md

I want to suggest to add my bundle in suggest section of your composer.json :) 

Thank you.

**Comment by robocoder** [comment]
I don't believe that's the intent of `suggests`, otherwise it would be referencing dozens of downstream packages.

**Comment by a-r-m-i-n** [comment]
You're welcome!
