### ISSUE TITLE
@use "sass:color" error

### ISSUE THREAD

**Issue by dilotec-2015** [scssphp/scssphp#253]
hallo,

i want to use the color module of sass. 
[https://sass-lang.com/documentation/modules/color](url)
So i do it like this:

`@use "sass:color";`

and then:

`color.scale(#DDD, $lightness: -10%); `

but i get following error:
#0 D:\.......\scssphp\src\Parser.php(196): ScssPhp\ScssPhp\Parser->throwParseError()
#1 D:\.......\scssphp\src\Compiler.php(4338): ScssPhp\ScssPhp\Parser->parse('\r\n@use "sass:color')
 
what i'm doing wrong?

**Comment by Cerdic** [comment]
sass modules are not supported (yet?) by scssphp see #55

**Comment by stof** [comment]
use the global function instead (`scale-color(#DDD, $lightness: -10%)`)

**Comment by stof** [comment]
> but i get following error:

your report here shows the stack trace, but does not show the error message (which probably came above that)

**Comment by dilotec-2015** [comment]
Yeah, i got following error:

[04-Nov-2020 13:27:43 Europe/Berlin] PHP Fatal error:  Uncaught exception 'ScssPhp\ScssPhp\Exception\ParserException' with message 'parse error: failed at `background-color: color.scale($bg-color, $lightness: -$hover-val);


Thank you for your answer.

Von: Christophe Coevoet <notifications@github.com>
Gesendet: Donnerstag, 5. November 2020 17:57
An: scssphp/scssphp <scssphp@noreply.github.com>
Cc: Waldemar Scholtyssek <W.Scholtyssek@dilotec.de>; Author <author@noreply.github.com>
Betreff: Re: [scssphp/scssphp] @use "sass:color" error (#253)


but i get following error:

your report here shows the stack trace, but does not show the error message (which probably came above that)

**Comment by stof** [comment]
hmm we might want to improve the error by failing early on `@use`

**Comment by stof** [comment]
That's weird to me. I get the parse error on `@use "sass:color";` already.
