### ISSUE TITLE
return value in compiler.php

### ISSUE THREAD

**Issue by gtbu** [scssphp/scssphp#26]
in /src/compiler.php  :
return $value !== static::$false && $value !== static::$null;  
error :
return value is expected to be an array ---- bool returned

**Comment by Cerdic** [comment]
This looks like an challenge to guess where is the bug with a minimal information.
I could also just answer "do not reproduce"!

Any context, error message with a line number, version used, a way to reproduce?

**Comment by gtbu** [comment]
Just install phpstorm trial and use as project the unpacked scssphp-folder.  The goto code -> inspect code ( i  have 20 warnings in compiler.php)

**Comment by Cerdic** [comment]
Sorry, maybe I'm a bit slow, but what's the issue with L2694?
https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L2694

The function is documented as returning a Bool and the expression in L2694 il effectively returning a bool

**Comment by gtbu** [comment]
Yes but phpstorm says : return value is expected to be an array

**Comment by Cerdic** [comment]
But I checked the 4 usages of the function and I can ensure you this a bool expected for this function. So who should we believe?
Hopefully there is a lot of unit test case on the lib, and my guess is this function is not that buggy…

**Comment by robocoder** [comment]
phpstorm's warning is a false positive.

**Comment by robocoder** [comment]
Feel free to report this issue with Jetbrains; I personally don't have the time to wade thru their issue tracker to see if this has already been reported.

**Comment by Cerdic** [comment]
@gtbu however in a more general way, automated tools for code analyzing are a good help to point where to look. But this is not a granted result and should always been double checked before considering this is a real issue. Otherwise it's just noise.

**Comment by robocoder** [comment]
Weird, I fired up the latest version of phpstorm and didn't see that warning on `isTruthy`. Anyways, I've committed some phpdoc tweaks but couldn't silence phpstorm entirely.
