### ISSUE TITLE
Compat libsass 3.6.0

### ISSUE THREAD

**Issue by Cerdic** [scssphp/scssphp#27]
Hi @robocoder,

as the compat with scss_css.rb is now almost complete, I started to integrate the libasass-3.6.0 spec in the unit tests and fixed a lot of issues around color functions.

At the moment it's in the branch https://github.com/scssphp/scssphp/tree/dev/compat-libsass-3.6.0

There is some slight impact on output compared to what we have now, which is mainly:
- unmanipulated colors stay in the original form they were written in the source
- manipulated colors can be output with their html name if any (mainly impact black and white colors)

I think this can be merged in the master as there is a lot of improvements but I let you have a check before to see if this seems acceptable.

**Comment by robocoder** [comment]
LGTM. Feel to merge to master. Will let it bake a month before I tag the next release.

**Comment by Cerdic** [comment]
This is integrated, the tests are now running against the sass-spec libsass 3.6.0
Some improvement in the implementation is still needed :)
```
$ make sass-spec
TEST_SASS_SPEC=1 vendor/bin/phpunit --colors tests 2>&1 | tee /tmp/saas-spec.log | tail -2
FAILURES!
Tests: 2377, Assertions: 1883, Errors: 135, Failures: 564, Skipped: 10.
```
