### ISSUE TITLE
setoutputstyle is missing

### ISSUE THREAD

**Issue by ahoba2002** [scssphp/scssphp#272]
Hi,
I cannot compress the output as setoutputstyle merhod is missing in latest version!

**Comment by ahoba2002** [comment]
I found the solution. I have to use this 
$scss->setFormatter("ScssPhp\\ScssPhp\\Formatter\\Compressed");

not what written in the documentation here https://scssphp.github.io/scssphp/docs/

what about the other documentation
https://scssphp.github.io/scssphp/docs/server.html
the commands there are not working!!!

Kindly check

and thanks for this helpful tool

**Comment by stof** [comment]
@ahoba2002 are you sure you are using the latest version ? The method exists: https://github.com/scssphp/scssphp/blob/v1.4.0/src/Compiler.php#L5119

**Comment by stof** [comment]
Closing this as there is no answer and the method is there in the latest version.
