### ISSUE TITLE
Compiler can't compile the sass mixin "font-size"

### ISSUE THREAD

**Issue by markocupic** [scssphp/scssphp#28]
Hi
I'm using bootstrap 4.3 wiht the font-size mixin. 
https://github.com/twbs/rfs

Unfortunately I'm getting this error:
Uncaught PHP Exception ScssPhp\ScssPhp\Exception\CompilerException: "Undefined mixin font-size: .......

**Comment by robocoder** [comment]
Sounds like your import paths aren't set correctly. Can you post an example reproducing the problem with `bin/pscss`?

**Comment by markocupic** [comment]
you're realy fast.
Which import paths do you mean?

**Comment by robocoder** [comment]
The one(s) you set with `addImportPath` or `setImportPaths`. I assume `rfs` has to be imported after `bootstrap`.

**Comment by markocupic** [comment]
That's really strange. After I've reinstalled the new version of the CMS (Contao). Now everything works fine. So it wasn't a path issue. 

I'm sorry that I've waste yourt time. 

Thank you very much!
Regards Marko
