### ISSUE TITLE
The handling of CSS custom properties is not spec compliant

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#280]

**Comment by leander-hass** [comment]
# Removal of Arguments after Custom Properties
Since there is no Description I am adding a related / specify an Issue:
```
:root {
    --my-values: 0, 230, 140;
}
.class {
    background-color: rgba(var(--my-values), 0.75);
}
```
After Compiling this (simplified) Code, the ```0.75``` are being just removed.

**Comment by stof** [comment]
Well, there is no description because this is covered by the sass-spec testsuite (when running the full testsuite to check compat rather than using our exclude list)

**Comment by stof** [comment]
Note that in your case, I'm not sure whether the culprit is the implementation of custom properties or the implementation of `rgba()` (which needs to have special handling when its arguments contain `var()` due to being both a Sass and a CSS function.

**Comment by erickyle** [comment]
It seems that introducing interpolation does result in the desired output (tested in version 1.6.0).
`background-color: rgba(#{var(--my-values), 0.75});`
However, it appears that involving mixins that generate the string does not result in the desired output.

**Comment by leander-hass** [comment]
Thanks a lot for helping me out with it :). I looked into the documentation and it seems that interpolation is not intended for such uses, but it works and I dont really bother.
Kind regards
