### ISSUE TITLE
Compiling plain css file imported into SCSS fails when using custom properties

### ISSUE THREAD

**Issue by willpower232** [scssphp/scssphp#286]
Edited stacktrace:

```
Fatal error:  Uncaught ScssPhp\ScssPhp\Exception\ParserException: Error : `--page-background:#6badff;` isn't
allowed in plain CSS (custom): failed at `--content-background:white;` ../template/public_html/color.css on
line 4, at column 2 in /vendor/scssphp/scssphp/src/Parser.php:205
Stack trace:
#0 /vendor/scssphp/scssphp/src/Parser.php(1229): ScssPhp\ScssPhp\Parser->parseError()
#1 /vendor/scssphp/scssphp/src/Parser.php(1628): ScssPhp\ScssPhp\Parser->assertPlainCssValid()
```

From messing around in the Parser class, I can see that the parsed row has already been correctly identified as a custom property so I believe the problem is that the `isPlainCssValidElement` function has no mention of `Type::T_CUSTOM_PROPERTY`.

I added it to the switch statement locally and the file appears to compile as it does if I rename the files from `.css` to `.scss`.

i.e. here
https://github.com/scssphp/scssphp/blob/c633b96209c47670bd361aaddf2a6a6965278b13/src/Parser.php#L1276-L1282

Please can you confirm if that is the correct approach, worthy of a PR, or if an alternative solution is more appropriate.

**Comment by Cerdic** [comment]
This seems fully the right way to fix this bug! You can go for a PR :)
