### ISSUE TITLE
@each is forcing unwanted type conversion

### ISSUE THREAD

**Issue by devdot** [scssphp/scssphp#29]
The types of keys are converted in a `@each` loop. 

Example (index not found for key in `@each` loop):
````SCSS
$map1: (
  "key1": 23,
  "key2": 32
);
$map2: ("key1", "key2");
@each $key, $value in $map1 {
  @debug $key; // will output as keyword, not as string
  @debug index($map2, $key); // will be null, but should be a number 
}
````

This was probably forgotten in #3 and is a simple fix.

Also, this fix makes it possible to compile Bootstrap 4 bootstrap-grid.scss without errors (I'm still having errors with bootstrap.scss but that's another issue)

**Comment by robocoder** [comment]
Fixed in 01390f285f72cbe34f431c15aa7f2bc9025efc75
