### ISSUE TITLE
type-of() returns wrong type for map keys

### ISSUE THREAD

**Issue by nd-** [scssphp/scssphp#296]
The type of keys in maps is always string, even for numbers with units.

Example:

```
$map: (
    600px: 20px
);
@each $key, $value in $map {
    @error 'value #{$key} type #{type-of($key)} -- value #{$value} type #{type-of($value)}';
}
```

Compiled with scssphp:
> value 600px type **string** -- value 20px type number

Compiled with compass:
> value 600px type **number** -- value 20px type number

The spec says:

> Numbers, which may or may not have units, like 12 or 100px.

https://sass-lang.com/documentation/values

**Comment by stof** [comment]
currently, ScssPhp does not properly represent SassScript values as strongly typed values. That makes `type-of` unreliable (and causes other weird bugs).

I have a work in progress locally to represent all values in an object-oriented way inside the ScssPhp codebase (see #265 for the discussion about that), which is expected to also solve that `type-of` issue as our values will indeed be strongly typed. but I don't know yet when I will have time to finish the work on implementing values (I still need to implement SassMap which is the tricky one) and then reworking the compiler to actually use the new value representation everywhere.

**Comment by nd-** [comment]
Thanx for your answer, I see it seems complicated :)

I should add a precision: in my example, even `600` (without 'px') is returned as a string by type-of.

**Comment by stof** [comment]
yeah, the current implementation of maps seems to be converting all keys to strings
