### ISSUE TITLE
Rethinking the handling of warning in sass-spec

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#303]
Currently, our SassSpecTest is always asserting the default `warning`, not considering alternative `warning-dart-sass`. This is not consistent with our handling of the output.

Currently, libsass renders warning without any location info (and we do it as well in most cases for now, which is how we pass warning checks for many cases) while dart-sass adds full error location as for errors. When I tried introducing the higher-level API for the logger, managing the location automatically, it broke tests as we would then not match the libsass warning anymore.

Another thing related to the matching of warnings is which version is mentioned in deprecation warnings. libsass says `in Sass 4.0` while dart-sass says `in Dart sass 2.0.0`. For now, we follow libsass. But `Sass 4.0` is not a thing anymore. The Sass language itself is not versioned anymore. It is a living spec.

Improvements to implement/discuss:
- support alternative warnings for the assertions in SassSpecTest -> done in #464 
- Remove the code snippet extract from the warning output before matching, until we have an equivalent formatting in Scssphp (which will require quite some work), keeping only the message before it and the trace (Note: this might help us move forward matching the error message too btw).
- Change the trace formatting in our errors and warnings to match the dart-sass one rather than the libsass one
- Discussion: which version should we mention in deprecation warnings ? The dart-sass one or our own version (with a rewrite of expected warnings before matching in SassSpecTest) ? I don't think we want to remove a deprecated feature before it is removed from dart-sass, so mentioning our own major version could be weird (we might need to change it if we do our own major version before dart-sass). In any case, I think we should move away from using `Sass 4.0`.

What do you think @Cerdic @robocoder ?

**Comment by robocoder** [comment]
Output multiple version numbers ala User-Agent?

**Comment by stof** [comment]
In the new compiler, I'm using `in Dart Sass 2.0.0` for now, allowing to assert the warning output in sass-spec without having to do special replacements in the runner.

**Comment by stof** [comment]
In 2.0, we have the same code snippets than dart-sass, thanks to the `scssphp/source-span` package, so we now follow the dart-sass output for warnings.
