### ISSUE TITLE
Overhaul the registration of custom variables

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#309]
the `Compiler::setVariables` API is currently quite messy in its signature. It accepts an `array<string, mixed>` with the following behavior for the mixed value depending on its type (this behavior actually happens in `Compiler::injectVariables`, as `setVariables` stores them without any transformation):

- try to parse it as a string containing a Sass value (there is a bug today where this is tried even if the value is not a string, which makes everything following it quite hard to use)
- `Scssphp\Scssphp\Node\Number`: use it as is (it is already in our value representation)
- `array`: use it as is, by assuming that it is our value representation
- `boolean`: convert to sass boolean
- `null`: convert to sass null
- numeric value: convert to `Number` (even if the input is a *string* containing a number)
- empty string: the Sass empty string
- `string` matching the color syntax: convert to sass color
- `string` (other): convert to `T_KEYWORD`, i.e. a sass unquoted string

This has several shortcomings:
- trying to parse the value as a string containing a Sass value does not even check that the value is indeed a string, which means that everything else is unlikely to work (passing a Number will *probably* work by casting it to string which gives a CSS representation of the number, but that will produce a different number when having complex units)
- this API is almost impossible to explain, and so to document (and to my knowledge, this issue is the first place which is actually trying to explain it)
- `setVariables` is actually merging the provided variables with existing registered variables, which makes it impossible to reset the list without using `unsetVariable` for each name (which is quite unexpected given its name)
- variable names are stripped from their leading `$` and normalized (dashes and underscores are equivalent in Sass variable names) only when injecting. Combined with the fact that `setVariables` merges the existing array, this can lead to weird behavior where your new variable does not work because there is another key in the array overriding it.
- the coercion of PHP values is incomplete

## Proposed changes

- add a `is_string` check before trying to parse the value as a sass source (avoids weird array-to-string casts or other weird errors as `true` casts to `1` which is then parsed as a number), which actually makes it possible to pass our sass values (`array|Number`) properly
- add a `Compiler::replaceVariables` method which accepts an array without merging it (and so resetting variables can be done with an empty array)
- maybe: add a `Compiler::addVariables` method with the existing behavior of `setVariables`, deprecating `setVariables` in favor of choosing the right method between `addVariables` or `replaceVariables`. This would help projects to discover that they actually want a `replaceVariables` behavior because they expected `setVariables` to work that way.
- add a validation against duplicate variable names in mutator methods (`setVariables`, `unsetVariable` and any new one). we would still need to store the original name though to avoid changing the keys in `getVariables`.
- introduce dedicated APIs to values. I'm explicitly documenting the return value as `mixed` because I want the return value type to be opaque to consumers of the API. For now, it would actually return `array|Number`, but would become `Value` after the migration to typed values. The only guarantee we would provide in this API return type is that the returned value is accepted by our `setVariables` API. This will also allow us to change the returned value to use our `Value` objects without it being a BC break.
    - `ValueHelper::parseValue(string $source): mixed` to parse a Sass source string into a value, triggering an exception if the source is invalid
    - `ValueHelper::fromPhp(mixed $value): mixed` which takes a PHP value and converts it to the appropriate Sass value representation
- deprecate passing anything else than a sass value in the array of variables (requiring to use the new APIs to produce values to build the array). Or maybe keep supporting sass source as a first-class citizen as well (as that's the working API today, as long as your sass source is valid). The argument type would still document it as `array<string, mixed>` the type for sass values is considered opaque.

## Questions to answer

- are you OK with that plan ?
- should we introduce `Compiler::addVariables` and deprecate `Compiler::setVariables` to force choosing which behavior (adding or replacing) you want ?
- where should the value conversion API be exposed, and under which name ?
    1. As static methods in the Compiler
    2. As instance methods in the Compiler
    3. As static methods in separate class
    4. As instance methods in a separate class
- should be allow (outside of the BC layer triggering deprecation warnings) only sass values in `setVariables` or also sass source strings ?

**Comment by stof** [comment]
Before opening this issue, I first considered deprecating custom variables, as that's an extension point that libsass and dart-sass don't expose (they only have custom functions).
But my investigation of usage in various platforms made me abandon the idea before opening the issues:

- [Spip](https://git.spip.net/spip-contrib-extensions/scssphp) allows to set variables (no idea where `pipeline('scss_variables',array());` gets them, but I assume it can get some)
- [Gantry 5](https://github.com/gantry/gantry5/blob/feature/v5.5.0/src/classes/Gantry/Component/Stylesheet/ScssCompiler.php) allows defining some variables
- [Shopware](https://github.com/shopware/platform/blob/trunk/src/Storefront/Theme/ThemeCompiler.php) does not use the feature. The allow injecting some variables, but they do that by prepending some variable declaration in the sass source before compiling it.

**Comment by stof** [comment]
My answers to the question:

> * are you OK with that plan ?

This plan is mine, so yes :smile: 

> * should we introduce `Compiler::addVariables` and deprecate `Compiler::setVariables` to force choosing which behavior (adding or replacing) you want ?

I vote for yes, as I think lots of code might have been tricked by the current (undocumented) behavior). But I don't have a strong opinion on this.

> * where should the value conversion API be exposed, and under which name ?
>   
>   1. As static methods in the Compiler
>   2. As instance methods in the Compiler
>   3. As static methods in separate class
>   4. As instance methods in a separate class

I vote for static methods in a separate class. I don't think these helpers belong to the Compiler class (using some methods of the Compiler while preparing the config of the Compiler looks weird to me, even more if they are instance methods as it creates a kind of chicken-&-egg issue). And I don't think forcing to instantiate another object for that is necessary.
Regarding the name, maybe `Scssphp\Scssphp\ValueConverter` (I intentionally avoid using the `Value` subnamespace holding typed value objects in #265 as that's quite separate)
 
> * should be allow (outside of the BC layer triggering deprecation warnings) only sass values in `setVariables` or also sass source strings ?

Keeping support for passing source strings directly will ease the migration path (assuming your strings are indeed valid source strings), but might also make it harder for projects where the string is not guaranteed to be a valid source string (in which case they should still use the `parseValue` API directly to be able to handle errors if they expect a source string). I don't have a strong opinion there.

**Comment by robocoder** [comment]
It would be a BC break but I like the idea of ValueHelper, so setVariables (or add/replace-) only gets a SassValue (which has been a recurring issue).

**Comment by stof** [comment]
@robocoder in 1.x, passing another type to `setVariables` would of course still be accepted with a deprecation warning (reusing the helper internally).
Could you provide answers for the various questions ?

**Comment by Cerdic** [comment]
As far as SPIP is concerned here is the source commit introducing the feature https://git.spip.net/spip-contrib-extensions/scssphp/commit/a05bbdda98151e3e850899dcfbc8856e9bb071e6 and I can not found a public usage of it in the shared public repositories so I guess this is mainly a one person usage (even if I could make a mistake).

Also, knowing how the ScssPHP compiler is used in the SPIP plugin, it could easy be replaced by the Shopware's way of doing, ie prepending the compiled source by  the extra variables declarations, whis is an easy way to deal over any BC break in ScssPHP.

That said 

>  are you OK with that plan ?
seems good to me

> should we introduce Compiler::addVariables and deprecate Compiler::setVariables to force choosing which behavior (adding or replacing) you want ?
I think so

>  where should the value conversion API be exposed, and under which name ?
I think as static methods and I agree in separate class

> should be allow (outside of the BC layer triggering deprecation warnings) only sass values in setVariables or also sass source strings ?

also seems preferable

**Comment by stof** [comment]
> Also, knowing how the ScssPHP compiler is used in the SPIP plugin, it could easy be replaced by the Shopware's way of doing, ie prepending the compiled source by the extra variables declarations, whis is an easy way to deal over any BC break in ScssPHP.

The shopware way has a drawback: it breaks sourcemaps (unless you take care or rebuilding the sourcemap to account for differences between the original source and the compiled source). So it depends whether you use source maps or no.
But if you support only scss source (which is what the commit documents), this is indeed producing the same CSS.

**Comment by robocoder** [comment]
LGTM

For the sass value helper? I'd lean towards a separate class with static methods.

Let's deprecate setVariables (). Until it's removed, it should continue to take either sass values or source strings to minimize surprise.

**Comment by stof** [comment]
> Let's deprecate setVariables (). Until it's removed, it should continue to take either sass values or source strings to minimize surprise.

you mean deprecating the setter in favor of new stricter ones, or deprecating the feature about registering custom global variables entirely ?

**Comment by robocoder** [comment]
Deprecate the setter. Provide add/replace.

Being able to inject variables is a typical use case dor theme plugins.
