### ISSUE TITLE
[RFC] Revised plan for 2.0

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#310]
After staring my work on #265, I realised that merging that work into 1.x is too risky regarding backward compatibility, due to #201. The existing array-based value API is less type-capable than the new API (see #296 for instance), so we need to refactor the Environment to use the `Value` objects to store variables. This will break BC for child classes messing with the internals of the Compiler.

## Suggested roadmap

> Note, when I give versions like `1.x`, it means a minor version in the series, with the exact version number depending on which this gets released. Not everything might happen in the same minor release.

### 1.x

- add a deprecation warning when a `lib*` method is detected as the implementation of a function and it comes from a child class (asking to use `registerFunction` instead)
- tag all protected functions as `@final` and `@internal` so that child classes using them or overriding them get a warning in the IDE
- do the same for public methods that should not be needed for implementing custom functions and don't need to stay public (for instance, this does not include the `Compiler::assert*` helpers as custom functions need them).
- mark public helpers as `@final` so that child classes get an IDE warning when overriding them
- tag classes as `@internal` for all classes that should not belong to the public API (this includes the `Parser` class to me)

### 2.0

- remove color math (which is already deprecated since 1.4.0 and is gone entirely in dart-sass)
- remove deprecated APIs of the Compiler
- remove deprecated formatters (this will unlock rewriting the way we produce CSS in a more modern way as we won't have to deal with these old styles)
- change all protected APIs of the Compiler to `private` (as well as public internal methods that don't need to stay public)
- change all `@final` public methods of the Compiler to actually be final

The 2.0 release is intentionally kept small in scope so that it can happen fast after the final 1.x release, to avoid maintaining 2 branches in parallel for a long time.

### 2.x

- implemented typed value objects (#265)
- rewrite the scope handling to store variables as typed values
- update `registerFunction` to support registering a function as using the modern value API (and deprecate registering functions with the old API)
- etc...

Over time in 2.x, we can rewrite parts of the library (see https://github.com/scssphp/scssphp/issues/193) freely, as almost everything will be internal and so won't impact backward compatibility.
And hopefully, after some time, we will have a 2.Y release passing sass-spec.

## Suggested process

- implement the 1.x changes
- release 1.x
- create a `1.x` branch
- change the `master` branch alias to `2.x`
- clean deprecated APIs
- do the 2.0 release
- from that point, the `1.x` branch enters maintenance mode, where only critical bugs get fixed (any sass compliance work happens in 2.x with the more modern API)
- keep working on modernizing scssphp

As such, the 2.0 release is expected to happen soon.
Projects that don't use deprecated APIs should be able to migrate quite easily.

**Comment by Cerdic** [comment]
Seems good to me. 

I will add that as far as SPIP is concerned and givien last internal talks about PHP version support I could manage that the 2.0 release would abandon the PHP5 compat - people really needing a PHP 5 support would have to use the maintenance branch of the plugin which would then rely on the maintenance branch 1.x of ScssPHP.

**Comment by stof** [comment]
@Cerdic what would be the new min version needed by SPIP ?

**Comment by Cerdic** [comment]
@stof the next 3.3 release coming soon should require at least PHP 7.1 but maybe PHP 7.3 - we are considering both options and it's more about the future (dev&maintenance) than what is still really needed right now. Then we would support the 3.2 longer (but as a maintenance version only) for people who are really stuck with PHP 5 whatever the reason

**Comment by stof** [comment]
To be honest, for the 2.x version, I would love to be able to require PHP 7.2+, to benefit from the covariance rules in signatures (I can live without it, but by giving up on native typehints in some future interfaces). but PHP 7.1+ is already quite good.

I'll open a dedicated issue to track that discussion specifically

**Comment by stof** [comment]
@Cerdic @robocoder I'm also wondering whether the introduction of `CompilationResult` should actually be done in 1.5 (as done currently as it is merged), or whether we should make that change in 2.0 (reverting part of the changes in 1.x).
Chaging the return type of `Compiler::compile()` is a BC break. The fact that object is castable to string helps, but only if such a cast actually happens before a strict string check is done (and if no cast is done before returning it from the embedded, which is likely if you don't modify the string after compilation, this leaks in the signature of the embedder).
The drawback of course would be that we either need to remove `Compiler::getParsedFiles` without deprecation in 2.0.0 (but we also won't have a deprecation warning for the migration to CompilationResult for the return type) or to keep the `Compiler::getParsedFiles` method in 2.x (as deprecated).

An alternative is to introduce a new method (but what would be its name ?) returning CompilationResult and deprecate `compile` (which would keep returning a string, using `return $this->newCompileMethod($input, $path)->getCss();`

Looking in dart-sass, they expose `compileString($input)` and `compileFile($path)` (which then reads the file).
This is a bit less flexible that our current API which allows modifying the input while still telling the compiler that it correspond to a given file (and so resolving relative imports based on that file). But I have no idea how such altering of the source code (where `$input` is not the true content of the file) affects the various caching layers.

**Comment by stof** [comment]
As I determined that the rewrite cannot be incremental (the state of 1.x is far too messy to replace the parser with a spec compliant one while keeping the next parts), I'm closing this issue.
