### ISSUE TITLE
[RFC] Min supported version for 2.0

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#314]
This is restarting the discussion of #202 based on new changes in downstream needs that blocked the decisions previously.

Note that this discussion is about the **minimum** supported version of PHP. The range of supported version will go from that minimum version up to the current PHP version. so downstream projects that already requires a higher minimum version than us are totally fine. The issue is if they want to keep support for a version *lower* than our minimum.
Also note that this change will apply only to 2.0. Our maintenance branch for 1.x will still support PHP 5.6+, but it won't receive anything else than critical bug fixes once 2.0 is out. That's still a solution for maintenance branches of downstream projects though if needed.

## Interesting features

The minimum supported PHP version will affect our ability to use these features in our own code:

- scalar types: PHP 7.0
- return types: PHP 7.0
- null-coalescing operator: PHP 7.0
- nullable types: PHP 7.1
- variance for signatures: PHP 7.2 (not needed for the Value objects, but useful if we want to port the dart-sass AST visitors later to allow using native types)
- typed properties: PHP 7.4 (nice-to-have, as our properties will stay private anyway to enforce immutability)
- union types: PHP 8 (useful for numbers, as they are `int|float`, i.e. the dart `num` type)
- enums: PHP 8.1 (could be nice to represent some parts of the AST or list separators for instance, but far too new to even consider PHP 8.1)

PHPUnit 8 is the first PHPUnit version which includes Life support, i.e. the fact that it will be made compatible with new PHP versions even after its end of maintenance. It requires PHP 7.2+. Being able to use PHPUnit 8+ would then make it much easier to maintain our tests (as we might not need to make tests compatible with a wide range of PHPUnit major versions to satisfy our PHP needs).

PHP 7.3 does not unlock any new feature by itself. So there is no reason to make it the min version (if we need to keep support for 7.3, we can keep support for 7.2 as well for the same maintenance cost).

## Downstream requirements

Top dependencies based on https://packagist.org/packages/scssphp/scssphp/dependents?order_by=downloads

- October CMS: 7.2.9
- Contao: 7.3
- Shopware: 7.2 (7.4 in their dev version)
- [Typo3 Bootstrap package](https://packagist.org/packages/bk2k/bootstrap-package): 7.2
- EZPlatform: 7.3
- OpenCart: 7.3 (taking the requirement from the master branch, as the latest tag is from 2018 instead and still uses `leafo/scssphp`)
- [Sass compiler for Typo3](https://packagist.org/packages/svewap/ws-scss): 7.2
- mediawiki/scss: 5.6  in the composer package. But Mediawiki itself now requires PHP 7.3

Extra known downstream projects:
- [SPIP](https://git.spip.net/spip-contrib-extensions/scssphp): 7.1 or 7.3 (see https://github.com/scssphp/scssphp/issues/310#issuecomment-796615476)
- Gantry 5: 5.6
- Grav (supported at least through Gantry, maybe by other themes too): 7.3
- Joomla 3 (supported at least through Gantry, maybe by other themes too): 5.3 (recommends 7.3+)
- Joomla 4: 7.2.5 (recommends 7.4+)
- Wordpress: 5.6. Recommends 7.4+

**Comment by stof** [comment]
@Cerdic based on this list of downstream requirement, I sincerely hope that SPIP chooses to drop support for PHP 7.1 as well, so that we can choose PHP 7.2 as our new min version :smile:

**Comment by mahagr** [comment]
I'd say it depends on when v2 will be out. If it's planned to come out soon, I would use PHP 7.2 as a minimum, otherwise, go for PHP 7.4.

**Comment by stof** [comment]
@mahagr would it be OK for Gantry 5 to stay on the 1.x maintenance branch ? Or do you have plans to bump your min version (and if yes, to which version) ?

**Comment by stof** [comment]
@mahagr see #310. It will come out soon.

**Comment by mahagr** [comment]
The currently released version uses an even older version of the library, but I'm basically debating raising the minimum required version to PHP 7.1/7.2 because of the used libraries anyway.

**Comment by stof** [comment]
@Cerdic do you have any estimate about when SPIP will make a decision about their min PHP version ? And about the chances that they choose to drop support for PHP 7.1 (whether they choose 7.2, 7.3 or even higher does not both me, as other projects already mean that our min version cannot go higher than 7.2 anyway) ?

**Comment by mahagr** [comment]
PS. Grav Admin plugin (which is a requirement for Gantry) already contains scssphp library. And yes, the minimum requirement is 7.3.

**Comment by stof** [comment]
@mahagr but isn't gantry supported on 3 platforms, not only on Grav ? That's why I listed things separately.

**Comment by mahagr** [comment]
Yeah, Gantry supports Joomla, WP and Grav with a minimum requirement of PHP 5.6.20 (matching WP) right now. However, it looks like Gantry will also jump to have 7.2 minimum.

**Comment by Cerdic** [comment]
@stof 7.3 will be the minimum PHP version for SPIP https://git.spip.net/spip/spip/commit/a61d29c6183d9f5d76dbe3ed36eefd20f14fabd5

**Comment by stof** [comment]
Hurray :tada: 

So this is now official: the minimum requirement for Scssphp 2.0 will be PHP 7.2.

I'm keeping this issue opened in the 2.0 milestone until this is implemented.
