### ISSUE TITLE
[RFC] Deprecate the --dump-tree option of the CLI

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#317]
the `pscss` CLI supports a `--dump-tree` flag (with a `-T` shortcut) which will parse the input file and then dumps the result.

To me, this is not really useful (nor usable):

- the output of the Parser is a mix of array-based AST (for expressions) and `Block` objects. But `--dump-tree` converts everything to associative arrays before dumping. Thus the output uses `print_r`, which is not precise about types. So this cannot actually be used to investigate what needs to be supported. this means that this flag is not really usable for contributors. Adding `var_dump` calls in the Parser or using a debugger is necessary to get useful insights.
- we make no guarantee about the structure of this AST (and the output of èprint_r` is not meant to be machine-readable). So this flag is useless for users of the library

**Comment by Cerdic** [comment]
I can agree it's hardly usable and everytime I tried I finished with a real `var_dump` indeed
