### ISSUE TITLE
[RFC] Take into account SASS files during the import resolution

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#347]
The Sass language specification requires that an import for `foo` is an error when resolving it if both `foo.scss` and `foo.sass` exist.
As we currently only look for `.scss` files, we fail at that rule, which means we would accept compiling things when official implementations would consider them as invalid.

Should we instead implement the full resolution logic (i.e. with both `.scss` and `.sass`, and `.css` at lower priority) and then trigger a parsing error if the resolved import is a `.sass` file (as we don't support that syntax) ?

**Comment by stof** [comment]
@robocoder @Cerdic what do you think about this ?

**Comment by robocoder** [comment]
I would leave it for now. The lack of SASS support makes it inherently non-compliant with the spec.

It seems contradictory to trigger an error when the importer finds both foo.scss and foo.sass, but a parse error when only foo.sass is present.

**Comment by stof** [comment]
@robocoder the only thing we document in the public API is that we throw a SassException. What would actually change when I say "a parse error" is the message.

`foo.scss` and `foo.sass`:
- dart-sass (and libsass): Error: ambiguous import
- current behavior: happily import `foo.scss`
- proposed behavior: Error: ambiguous import

`foo.sass`:
- dart-sass (and libsass): import `foo.sass`
- current behavior: try next importer (the next load path). This can end up either importing a totally different scss file orwith an error saying that the file is not found
- proposed behavior: Error: the indented sass syntax is not supported (with a trace ending in the foo.sass file)

**Comment by Cerdic** [comment]
seems better to me to have this clear situation where the importer would find the right file (ie the same as would dart-sass) but throw an error because of unsupported syntax.

We had issues in the past where people were trying to compile a sass file and no clear error to understand that this was not a supported syntax.

**Comment by stof** [comment]
and writing this, I realised that the behavior is even worse than what I thought, as we will keep trying searching the file in other locations when using only a sass file, meaning we can import something else than the official sass implementations (which could actually be abused by having `foo.sass` for dart-sass and `foo/index.scss` for scssphp if you want to go crazy...)
