### ISSUE TITLE
Bug compiling Foundation (_math.scss)

### ISSUE THREAD

**Issue by airelibre** [scssphp/scssphp#39]
Hi,

got something really weird, and I'm not sure of which functions / part of code  makes ScssPHP crash.

I'm using the 1.0.3 version with Foundation6. It works on a php7.2 / apache local install, but not on a shared hosted php7.2 with apache too. Works on another php7.0 and 7.2 ubuntu server too.

This part of code makes scss crash without any error:
`/// Handles decimal exponents by trying to convert them into a fraction and then use a nth-root-algorithm for parts of the calculation
///
/// @param {Number} $base - The base number.
/// @param {Number} $exponent - The exponent.
///
/// @returns {Number} The product of the exponentiation.
@function pow($base, $exponent, $prec: 16) {
  @if (floor($exponent) != $exponent) {
    $prec2 : pow(10, $prec);
    $exponent: round($exponent * $prec2);
    $denominator: gcd($exponent, $prec2);
    @return nth-root(pow($base, $exponent / $denominator), $prec2 / $denominator, $prec);
  }

  $value: $base;
  @if $exponent > 1 {
    @for $i from 2 through $exponent {
      $value: $value * $base;
    }
  }
  @else if $exponent < 1 {
    @for $i from 0 through -$exponent {
      $value: $value / $base;
    }
  }

  @return $value;
}

@function nth-root($num, $n: 2, $prec: 12) {
  // From: http://rosettacode.org/wiki/Nth_root#JavaScript
  $x: 1;

  @for $i from 0 through $prec {
    $x: 1 / $n * (($n - 1) * $x + ($num / pow($x, $n - 1)));
  }

  @return $x;
}

/// Calculates the height as a percentage of the width for a given ratio.
/// @param {List} $ratio - Ratio to use to calculate the height, formatted as `x by y`.
/// @return {Number} A percentage value for the height relative to the width of a responsive container.
@function ratio-to-percentage($ratio) {
  $w: nth($ratio, 1);
  $h: nth($ratio, 3);
  @return $h / $w * 100%;
}`

Commenting the "if $exponent ..." part makes the framework compile well:
`/// Handles decimal exponents by trying to convert them into a fraction and then use a nth-root-algorithm for parts of the calculation
///
/// @param {Number} $base - The base number.
/// @param {Number} $exponent - The exponent.
///
/// @returns {Number} The product of the exponentiation.
@function pow($base, $exponent, $prec: 16) {
  @if (floor($exponent) != $exponent) {
    $prec2 : pow(10, $prec);
    $exponent: round($exponent * $prec2);
    $denominator: gcd($exponent, $prec2);
    @return nth-root(pow($base, $exponent / $denominator), $prec2 / $denominator, $prec);
  }

  $value: $base;
  // @if $exponent > 1 {
  //   @for $i from 2 through $exponent {
  //     $value: $value * $base;
  //   }
  // }
  // @else if $exponent < 1 {
  //   @for $i from 0 through -$exponent {
  //     $value: $value / $base;
  //   }
  // }

  @return $value;
}

@function nth-root($num, $n: 2, $prec: 12) {
  // From: http://rosettacode.org/wiki/Nth_root#JavaScript
  $x: 1;

  @for $i from 0 through $prec {
    $x: 1 / $n * (($n - 1) * $x + ($num / pow($x, $n - 1)));
  }

  @return $x;
}

/// Calculates the height as a percentage of the width for a given ratio.
/// @param {List} $ratio - Ratio to use to calculate the height, formatted as `x by y`.
/// @return {Number} A percentage value for the height relative to the width of a responsive container.
@function ratio-to-percentage($ratio) {
  $w: nth($ratio, 1);
  $h: nth($ratio, 3);
  @return $h / $w * 100%;
}
`

This comes from util/_math.scss from the Foundation framework. I first thought it comes from the "-$exponent" but even if I change this part, it fails.

Hope this can help, and maybe other users have the same issues?

**Comment by airelibre** [comment]
One more precision: the same configuration (php7.2 / apache on shared hosting server) was working / compiling with scssPhp 0.6.3. Foundation SCSS files was the same too

**Comment by robocoder** [comment]
Sounds environmental. Can you run the unit tests on that shared server?

**Comment by robocoder** [comment]
And attach the sanitized output of phpinfo() from that environment? I'm thinking extensions and/or disabled functions to be the problem.

**Comment by robocoder** [comment]
Please update to `scssphp` 1.0.4. Make sure your shared hosting environment has the `json` and `ctype` PHP extensions.

**Comment by airelibre** [comment]
Hi,

thanks - I'm not able to run the tests on this (limited) shared hosting environment ... but I tried to upload your latest version to it. 
Unfortunately, this part of code continues to break the script.

Here's the phpinfo attached - json and ctype are here
[phpinfo.tar.gz](https://github.com/scssphp/scssphp/files/3625664/phpinfo.tar.gz)

Thanks if you can help

**Comment by robocoder** [comment]
Yup, all the required modules are there. I didn't see anything in your config that was (too) out-of-the-ordinary for shared hosting. I don't have any other ideas at the moment.
