### ISSUE TITLE
Having trouble calling the ValueConverter API

### ISSUE THREAD

**Issue by chrisblakley** [scssphp/scssphp#398]
I've been using (and loving) SCSSPHP for a long time, and I'm now updating to 1.5 and fixing up the deprecation warnings. I've got most of them fixed, but I'm having trouble with the `ValueConverter` API. I'm following [the documentation here](https://scssphp.github.io/scssphp/docs/extending/preset-variables.html) as best I can, but I must be missing a piece (and most likely though no fault of the library).

Here's how I initialize SCSSPHP (this is in WordPress):

```php
require_once get_template_directory() . '/inc/vendor/scssphp/scss.inc.php'; //Run the autoloader
$this->scss = new \ScssPhp\ScssPhp\Compiler();
```

Note: `$this` is my `Nebula` class.

Since the `ValueConverter` is its own separate class (with private functions), when I try to use it I get a `Fatal error: Uncaught Error: Call to private ScssPhp\ScssPhp\ValueConverter::__construct() from scope Nebula`.

So this (obviously) does not work:
```php
require_once get_template_directory() . '/inc/vendor/scssphp/scss.inc.php'; //Run the autoloader
$this->scss = new \ScssPhp\ScssPhp\Compiler();
$this->valueConverter = new \ScssPhp\ScssPhp\ValueConverter(); //-> Fatal error
```

Without fundamentally changing the way I'm calling SCSSPHP, what is the appropriate way for me to utilize the ValueConverter API so I can add my PHP variables?

I appreciate your time– sorry if I'm misunderstanding something.

**Comment by stof** [comment]
ValueConverter is a class exposing static methods. You should not try to instantiate it.

**Comment by stof** [comment]
btw, the example at the end of this doc page is showing the right code
