### ISSUE TITLE
Help projects to switch to scssphp/scssphp

### ISSUE THREAD

**Issue by robocoder** [scssphp/scssphp#4]
Open pull requests with the top (5-10?) projects that use leafo/scssphp to make the switch to scssphp/scssphp.

Anyone can help here. Just comment here with a link to the pull request.

Reference: https://packagist.org/packages/leafo/scssphp/dependents

* [x]  https://github.com/kriswallsmith/assetic
* [x]  https://github.com/phingofficial/phing
* [x]  https://github.com/octobercms/library
* [x]  https://github.com/contao/core-bundle
* [x]  https://github.com/anomalylabs/streams-platform
* [x]  https://github.com/ezsystems/ezplatform
* [x]  https://github.com/orocrm/platform

**Comment by Cerdic** [comment]
* [x] https://github.com/pressbooks/pressbooks https://github.com/pressbooks/pressbooks/pull/1723
* [ ] https://github.com/contao/contao

**Comment by greatislander** [comment]
- [ ] [kriswallsmith/assetic](https://github.com/kriswallsmith/assetic/): https://github.com/kriswallsmith/assetic/pull/892
- [ ] [octobercms/library](https://github.com/octobercms/library/): https://github.com/octobercms/library/pull/409

**Comment by Cerdic** [comment]
https://github.com/ezsystems/ezplatform/pull/407
https://github.com/contao/core-bundle/pull/1691

**Comment by Cerdic** [comment]
https://github.com/phingofficial/phing/pull/1078

**Comment by Cerdic** [comment]
https://github.com/markstory/asset_compress/pull/338

**Comment by robocoder** [comment]
https://github.com/anomalylabs/streams-platform/pull/663

**Comment by robocoder** [comment]
https://github.com/oroinc/platform/pull/929
