### ISSUE TITLE
ValueConverter::fromPhp() does not regognize SCSS types

### ISSUE THREAD

**Issue by mahagr** [scssphp/scssphp#409]
I am currently updating some deprecated code and I have trouble with SCSS variables which are mostly stored as strings.

I'm currently trying to replace `$variables` in here:

```php
$this->compiler->addVariables($variables);
```
with something that converts them to SCSS types: `$variable = ValueConverter::fromPhp($variable);`

Method doesn't recognize at least following types:

Colors:
* #fff
* #ffaaff
* rgb(125,200,100)
* rgba(125,200,100,0.3)
* yellow

Numbers with units:
* 1.5rem
* 10px
* 50%

**Comment by mahagr** [comment]
Also, the old code required variables to be quoted if they were strings.

**Comment by stof** [comment]
that's totally expected. If you want to parse a Sass value, you need to use the `parseValue()` method, not the `fromPhp` method.

**Comment by stof** [comment]
In 1.4, the code was doing the equivalent of `parseValue`, unless the parsing failed, in which case it would fallback to coercing the PHP value.
In practice, this was quite unreliable as it was casting values to string before parsing, so passing a boolean would probably not produce a Sass boolean for instance (`(string) true` is the string `1`, which is a valid sass value representing a number). It was quite hard to find a value that would both be castable to a string and not be a valid Sass value after casting. this means that the migration path for old code using `setVariables` should likely be to use `ValueConverter::parseValue`

**Comment by mahagr** [comment]
Thank you, the method seems to work as long as I have the strings escaped as previously.

**Comment by stof** [comment]
@mahagr yeah, that's the whole point of the new API: we are making it explicit whether the input is a string containing a SCSS value or a PHP value that we want to convert (and PHP values indeed cannot represent `10px` as a number with unit, as there is no native PHP type for "number with CSS unit")

**Comment by mahagr** [comment]
Apart from deprecated messages, the upgrade went well and without any issues. I tried the `ValueConverter::parseValue()` first, but I got confused as it didn't work without my type detection code as I tried without it first. But it was easier than I thought, I just had to keep most of the code as it was. :)

Thanks again for your help!
