### ISSUE TITLE
[RFC] Modernize the CLI executable

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#417]
Currently, the `pscss` CLI executable lives in this package. Because of that, it inherits the requirements of having no dependency that we have for the compiler to easily embed it in CMS plugins. But this also means that we have to implement our own processing of arguments, which is less powerful that what CLI frameworks implement (our current processing is similar to the common case of the common POSIX conventions, but misses lots of more advanced cases).
AFAICT, none of the CMS plugins rely on our CLI executable to perform the compilation (if they were doing that, they might as well switch to use the dart-sass native executable and get better performance and better features).

However, having a CLI executable based on scssphp is still helpful, at least for us maintainers:
- it allows to easily run a compilation to debug things
- it allows running sass-spec against the official spec runner as long as our CLI is compatible with the expected arguments (which is the case). This is not very helpful yet due to our formatting differences (our own runner applies some normalization on the output and manages the skipping of tests in a custom way as we are not an implementation supported officially in sass-spec). But this could change in the future. Achieving formatting parity with dart-sass is definitely planned for a 2.x version (the one that will rewrite the logic producing the output). And once it is the case, I plan to start a discussion with the Sass team to become a semi-official implementation and managing the skipped specs with the official runner system (this point is out of scope of this RFC).

I see 4 alternatives for the CLI executable:

1. status quo
2. create a new `scssphp/cli` package shipping the `pscss` executable (removing it from the `scssphp/scssphp` package). The `scssphp/cli` package would be free to use other composer dependencies (it would also depend on `scssphp/scssphp` of course), and so could use `symfony/console` for the CLI implementation (or another alternative, but `symfony/console` is obviously the one *I* know well as I'm part of the core team). To preserve the maintainer workflow, `scssphp/scssphp` could have a dev requirement on `scssphp/cli` (this would create a circular dependency with the root package, which might require setting `COMPOSER_ROOT_VERSION` for things to work, but `make vendor` could set it automatically so that would not be a big issue IMO)
3. keep the `pscss` script in the `scssphp/scssphp` package but make it rely on composer dependencies for the CLI framework. CMS plugins vendoring the package without needing the CLI could omit the `bin/pscss` file and the `src/Console` folder (or whatever we name it) to avoid issues with missing dependencies. We have several sub-alternatives about the way we manage those dependencies:
    1. add `require` rules on the package we use
    2. add `suggest` rules to document the optional dependencies we have for the CLI, with `conflict` rules preventing incompatible versions
    3. add `suggest` rules to document the optional dependencies we have for the CLI, without `conflict` rules. This alternative has the benefit that projects using `scssphp/scssphp` programmatically won't face any version conflict with our CLI dependencies if they use different versions for their own CLI. The drawback is that using the `pscss` CLI would not only need to validate that the necessary packages are installed, but also that they are compatible.
4. turn the `pscss` into a maintenance tool only, by unexposing it from the composer package (which then makes it free to rely on our dev requirements to be implemented)

A change from the status quo needs to happen in the 2.0 release, because any option other than the 3.1 one implies a BC break for projects using `pscss` from an install of scssphp in their vendor folder (as they would need to change their requirements to add either the `scssphp/cli` package or the `symfony/console` package depending on the alternative) and all options imply breaking the CLI when downloading the source code from another source than composer (our website links to the github archive of the source code, it does not produce its own archive which could embed dependencies)

@robocoder @Cerdic what is your preference here ?

**Comment by stof** [comment]
For me, the preference depends on whether we consider that `pscss` is useful to others than maintainers. I personally never used it outside my maintenance work here. All my usages of scssphp are through the programmatic API, as that's the reason why I would use scssphp (if using a non-customized CLI tool to compile is an option for a use case, I would use the official sass executable as it is faster and more spec compliant).

If useful only for maintenance work, go for the solution 4
If we need to keep shipping a `pscss` executable, I would go for either 2 (if restricting that executable to projects using composer is an on option) or for the status quo (accepting that our parsing of argument is not on par with POSIX conventions, as I don't want to reimplement a full parsing library just to avoid dependencies)

**Comment by robocoder** [comment]
I'm not too concerned with where the CLI executable lives but I would still like to have one.

Our app's assetic config uses the ruby-sass integration. However, in my dev environment, sass is a bash script that wraps bin/pscss, ruby sass, or dart-sass, so I can easily switch implementations without changing the app configuration.

**Comment by stof** [comment]
@robocoder would it be OK for you if the CLI executable is available only through composer and not when downloading the source code from the website ?
If yes, that would allow the option 2, where your project would only need to require `scssphp/cli` when migrating to scssphp 2.

**Comment by robocoder** [comment]
Our app doesn't have a composer dependency on scssphp. We can adapt our bash script since scssphp/sass/dart-sass sit outside our app.

In the short term, I'd say go with option 4, and provide option 2 later on.

**Comment by mahagr** [comment]
I'd say 4, too, as I cannot see any benefit of using PHP compiler instead of the official ruby-sass implementation from CLI.

We use PHP compiler to be able to dynamically change colors, fonts, and some other basic styling from admin.

**Comment by stof** [comment]
> instead of the official ruby-sass implementation from CLI.

I hope you meant the official dart-sass one. ruby-sass is dead since years now.

**Comment by mahagr** [comment]
Hah, yes, I just read the response from @robocoder and somehow ended typing dart.
