### ISSUE TITLE
Support for math:sass => "math.div()" instead "/"?

### ISSUE THREAD

**Issue by Daijobou** [scssphp/scssphp#419]
Since dart-sass 1.33.0 

> Deprecate the use of / for division. The new math.div() function should be used instead. See [this page](https://sass-lang.com/documentation/breaking-changes/slash-div) for details.

Is it planned (and possible) to support [@use "sass:math";](https://sass-lang.com/documentation/modules/math) and his variables and functions? I stay with version dart-sass 1.32.x.

**Comment by stof** [comment]
To be able to use the math module, we first need to implement support for modules (see #55, but we have other work to do before that). Implementing modules is something that we want in the long term (and this deprecation of the `/` as division tends to make it more important to stay relevant) but work on scssphp is only done durng our free time, so we cannot commit on any schedule for when it will happen.

The new `math.div()` function does not have an equivalent global function that we could already implement (which is totally expected, as new Sass features are not meant to introduce new global functions, as those global functions can conflict with CSS functions).

**Comment by stof** [comment]
I'm closing this issue as support for modules is already tracked in its dedicated issue.
