### ISSUE TITLE
Embedded @imports

### ISSUE THREAD

**Issue by X25guru** [scssphp/scssphp#422]
Is there a way to pass css files to the output rather than including an @import statement in the output result? For Example

@import "foo.scss";
@import "bar.css";

The compiler I've been using will put bar.css into the output (as if it was named bar.scss); effectively allowing the SCSS compiler to act as a combiner, while this compiler just puts an import line in the result. I *could* rename the css files to scss, but I have a lot of projects. It's very useful if there isn't a way to do it that I just can't find.

**Comment by stof** [comment]
If you import it without the extension, sass will import a `bar.css` file if there is no `bar.scss` or `bar.sass` file next to it (that would be imported otherwàse).
And import with a `.css` extension is always a CSS import rather than a Sass import. That's part of the Sass language specification, and scssphp implements it according to the spec. See https://sass-lang.com/documentation/at-rules/import#importing-css for the doc about it.

**Comment by X25guru** [comment]
Any robot can mimic the "language spec". Why not aspire to create something better?

**Comment by stof** [comment]
Because scssphp is meant to provide an implementation of the Sass language in PHP, not creating a different language that diverges from Sass in custom ways (and that is then incompatible with Sass).

**Comment by stof** [comment]
Thus, the Sass language itself already provides a way to import a CSS file, as described in the doc I linked.

**Comment by stof** [comment]
Also, regarding innovation being a bad thing, this repo is not the place where innovation for the Sass language happens. such innovation happens upstream in https://github.com/sass/ (and our implementation is actually quite outdated compared to the innovations of the past few years, which are are trying to catch up)

**Comment by X25guru** [comment]
Innovation is when someone with vision implements something and everyone else in the community sees it and says "Hey, thats really useful, lets do that too".

SASS is a tool to generate CSS. Would adding an option to expand imports change the language or make it incompatible with CSS? No it would not. 

Anyway, I created a new language with 3 lines of code that is now much more useful. Have a nice day.

**Comment by stof** [comment]
Sass is not a tool to generated CSS. It is a language that compile to CSS. This language has a clear spec about how the language work.
If we implement such option in scssphp, it means that what we implement won't be the Sass language anymore, but out own language that looks like Sass today (and good luck keeping it compatible in the future). And creating a separate language that compile to CSS is not our goal at all in the scssphp project.

Thus, as I said, the option to import a CSS file **already exists in Sass**.

**Comment by X25guru** [comment]
"Sass is not a tool to generated CSS. It is a language that compile to CSS"

What I meant is that a Sass COMPILER is a tool to generate CSS. The "language" doesnt change because the compiler has options that can do other things with the code. I can generate assembly source with a C compiler or I can generate preprocessor code or executable code or optimized executable code. Adding options to the compiler doesn't change or dilute the "language". It just adds usefulness to the user; to do things that users might want to do with the code. A compiler is not a rote program that does 1 thing. Or at least it doesnt have to be.

The fact that there's a way to add css files is nice but I don't want to have to change 300 files because I was using a more innovative "compiler" before this one. It's very easy to add the "feature" to the compiler.

As I said, I have it working the way I want, which is the point of open source.
