### ISSUE TITLE
Bug: Save Source Map as file no longer works

### ISSUE THREAD

**Issue by dleffler** [scssphp/scssphp#423]
Somewhere around commit dee07002e72884b5e220003b164c4e869dad887e the 'saveMap' function was dropped from both Compiler.php AND CompilationResult.php. Documentation/Issues seem to point to where it would now be in CompilationResult, the end result is that the map file is not saved/written to the .map file.

**Comment by stof** [comment]
The CompilationResult gives you the content of the source map, just like it gives you the content of the CSS without writing it to disk.

**Comment by dleffler** [comment]
So does that mean that File Compiler Maps are now handled by the calling application and NOT by scssphp?

**Comment by stof** [comment]
Well, the content of the sourcemap is generated by scssphp. but saving it to disk is indeed expected to be handled by the caller, like for writing the CSS to disk.
