### ISSUE TITLE
Implement the Sass indented syntax

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#425]
Once #424 is complete, implementing the indented syntax won't be a lot of work (I kept the separation between `StylesheetParser` and `ScssParser` on purpose to make it possible to port the `SassParser` from dart-sass).

**Comment by stof** [comment]
Once this is done, our FrameworkTest should probably also include the Bulma framework, to be consistent with the list used by dart-sass.

**Comment by Bizarrus** [comment]
Any updates?

**Comment by stof** [comment]
The v2 is not yet ready. This will either be part of it or of a following minor version (the new parser is not part of 1.x)
