### ISSUE TITLE
Alternative for setVariables?

### ISSUE THREAD

**Issue by STV11C** [scssphp/scssphp#426]
Hi there, I am updating from v1.1.1 to the latest v1.5.2 and got an error regarding setVariables.
Looking at the changelog, it appears setVariables was deprecated.
Is there an alternative way to use variables?

`$compiler->setVariables($variables);`

Thank you and regards
Stephan

**Comment by stof** [comment]
The deprecation message mentions those alternatives: `addVariables` (which is the direct replacement for the *behavior* of `setVariables` but with a better name describing it) or `replaceVariables` (which is doing what the old name was suggesting)

**Comment by STV11C** [comment]
Thank you for the quick reply and hoping you can please assist with the following.
After changing to `addVariables` I got the next error:
`Fatal error: Uncaught InvalidArgumentException: Passing raw values to as custom variables to the Compiler is deprecated. Use "\ScssPhp\ScssPhp\ValueConverter::parseValue" or "\ScssPhp\ScssPhp\ValueConverter::fromPhp" to convert them instead.`

I then added something like this:
`$compiler = ScssPhp\ScssPhp\ValueConverter::fromPhp($variables);`
and got error:
`Fatal error: Uncaught InvalidArgumentException: Cannot convert the value of type "array" to a Sass value.`

Note that my variable $variables is an array. Any ideas how to get working? Thank you :)

Regards
Stephan

**Comment by stof** [comment]
you must apply it on the values of your variables, not on the associate araay itself.

**Comment by stof** [comment]
Btw, the `Uncaught InvalidArgumentException: Passing raw values to as custom variables to the Compiler is deprecated.` seems weird to me. Are you using an error handler turning *silenced deprecations warnings* into `InvalidArgumentException` ?

**Comment by stof** [comment]
Side note: if you want to get the same behavior than in 1.1 for your variables, use `parseValue` rather than `fromPhp`

**Comment by STV11C** [comment]
Oh ok. Something like this?
```
$variables=array(
  "my-variable" => ScssPhp\ScssPhp\ValueConverter::fromPhp( $my-variable-value ),
  ...
}
```

BTW - I am using SCSSPHP with Redux Framework for WordPress. The errors are visible from within WordPress after clicking Save on Redux Framework theme options.

**Comment by stof** [comment]
Alternatively, getting an actual InvalidArgumentException could be because you use the master branch (which is 2.0-dev now) rather than the 1.5.2 release.

**Comment by STV11C** [comment]
> Alternatively, getting an actual InvalidArgumentException could be because you use the master branch (which is 2.0-dev now) rather than the 1.5.2 release.

Yes you are correct. Sorry about that and I have replaced it with the official 1.5.2 release :)

**Comment by stof** [comment]
this will also make your life simpler, as you will now get deprecation warnings for deprecated features, instead of having to deal with removed features.
but it at least allowed me to realise that our error message was wrong in the master branch (still talking about being deprecated)

**Comment by STV11C** [comment]
> this will also make your life simpler, as you will now get deprecation warnings for deprecated features, instead of having to deal with removed features.
> but it at least allowed me to realise that our error message was wrong in the master branch (still talking about being deprecated)

Glad I helped you in some way :) 
Ok I have the SCSS compiling now, but I had to use a combo of `fromPhp` and `parseValue.` 
I am compiling a modified version of Bootstrap 4.6.0 and most of it looking correct.

**Comment by STV11C** [comment]
Looks like this latest version doesn't like empty variables... which makes sense, but I wrote some If statements in my SCSS based on empty value.
`Fatal error: Uncaught InvalidArgumentException: Invalid value source "".`
I'll refactor my code for this.

**Comment by stof** [comment]
Well, depends what it is. for `parseValue`, an empty string indeed cannot be parsed.

**Comment by STV11C** [comment]
Hi again. I have had a chance to become familiar with `fromPhp` and `parseValue` now.
In my Redux Framework theme options their Typography settings (see attached) allow empty fields, so to make it work with the latest v1.5.2 I used `fromPhp ` however the values end up with inverted commas making the CSS invalid (see image attached).
The values work as expected with `parseValue`, however it does not allow the SCSS variable to be empty/null anymore.

Any suggestions?

![image](https://user-images.githubusercontent.com/5532744/120302703-7e8d9380-c311-11eb-9213-b986a2024dd6.png)

![image](https://user-images.githubusercontent.com/5532744/120302871-a3820680-c311-11eb-90d7-4946a4a8cafb.png)

**Comment by stof** [comment]
Well, if you pass a PHP string to `fromPhp`, it will provide a Sass string, not a Sass number (with unit or no) or a Sass color. That's totally expected. Parsing a string as Sass source code is what `parseValue` does.
And the empty string or `null` are indeed not valid source code for a Sass value. If you allow empty fields, I suggest that you handle the case of empty fields in your code (deciding how those empty fields should appear in Sass)

**Comment by STV11C** [comment]
Thanks for quick reply. With SCSSPHP v1.1.1, I check for empty in my SCSS file like so:
```
@if $opt-bs4-display1-line-height != "" {
  line-height: $opt-bs4-display1-line-height;
}
```
Basically, I am only using the optional typography values if they are not empty.

Do you have any suggestions how I could combine the `ValueConverter` and If !empty ?

**Comment by stof** [comment]
well, if your input is empty, use `ValueConverter::fromPhp('')` to produce a sass empty string.
Or even better: use `ValueConverter::fromPhp(null)` to produce a Sass `null` (changing your condition), which then makes it compatible with using `!default` in Sass to provide a default value for the variable.

**Comment by STV11C** [comment]
I understand what you are saying, but in this case I am not overriding an existing Bootstrap variable, but instead adding a CSS override if the user selects any of the optional typography options. Otherwise if they are empty, if inherits the value.

It would be cool if the ValueConverter had an option to set it to empty/null as you described above if it didn't exist.

I'll have a think about my implementation in more detail. Thanks for your help :)

**Comment by robocoder** [comment]
You use setVariables to preload values before the scss is evaluated (ie before any of the scss cars exist).

**Comment by stof** [comment]
> I understand what you are saying, but in this case I am not overriding an existing Bootstrap variable

you cannot use `setVariables` to override any variable. You can only use it to configure things (Bootstrap uses `!default` on all its variable declarations to make them configurable), because `setVariables` declares variables before evaluating the source. In practice, these 2 codes are producing the same result (not taking the sourcemap into account, as the second one would of course require adjusting the sourcemap to account for the modified input):

```php
$compiler = new Compiler();
$compiler->replaceVariables([
    'my-var1'  => ValueConverter::parseValue('12px'),
    'my-var2'  => ValueConverter::parseValue('"Roboto Slab"'),
    'my-var3'  => ValueConverter::parseValue('true'),
]);
$scss = file_get_content('input.scss');
$result = $compiler->compileString($scss, 'input.scss');
$css = $result->getCss();
```


```php
$compiler = new Compiler();
$scss = file_get_content('input.scss');
$scssWithVariables = <<<SCSS
\$my-var1: 12px;
\$my-var2: "Roboto Slab";
\$my-var3: true;

$scss
SCSS;
$result = $compiler->compileString($scssWithVariables, 'input.scss');
$css = $result->getCss();
```

**Comment by STV11C** [comment]
Would you consider having third Preset variable that handles empty? E.g. `replaceNotEmptyVariables($vars)`
OR
having `replaceVariables` handle nulls/empty by not replacing the initial value?

In my case as I am using Redux Framework theme options to collect user inputs (the variable values), and as some are optional (and can be null), I cannot control if they are set or not. I've tried both `addVariables` and `replaceVariables`, including setting the initial value of the variable in my SCSS, but it fails while saving.
`Fatal error: Uncaught InvalidArgumentException: Invalid value source "". in /var/www/html/wp-content/themes/gutenize/vendor/scssphp-1.5.2/src/ValueConverter.php:41`

 If no simple solution, I may just stick with v1.1.1 for now, but ideally would like to be on the latest version.

Once again, thank you for your efforts to assist me. I really appreciate it.

**Comment by stof** [comment]
@STV11C I don't think it makes sense to introduce that behavior. If you want to skip defining the variables entirely (which is not the same than setting them to an empty string as their Sass value), you could use `array_filter` to remove the variables you don't want to define (before converting them)
