### ISSUE TITLE
When updating to the latest version in WP I get this error.

### ISSUE THREAD

**Issue by VibeTank** [scssphp/scssphp#431]
Hi, 

When updating the plugin on WordPress I get this issue and I have to delete the complete plugin

>Warning: Undefined array key "compiling_options" in F:\Xamp\htdocs\Website\wp-content\plugins\wp-scss\wp-scss.php on line 114
Fatal error: Uncaught Error: Class "" not found in F:\Xamp\htdocs\Website\wp-content\plugins\wp-scss\scssphp\src\Compiler.php:243 Stack trace: #0 F:\Xamp\htdocs\Website\wp-content\plugins\wp-scss\class\class-wp-scss.php(80): ScssPhp\ScssPhp\Compiler->compile('// @import 'imp...', 'F:\\Xamp\\htdocs\\...') #1 F:\Xamp\htdocs\Website\wp-content\plugins\wp-scss\class\class-wp-scss.php(113): compiler('F:\\Xamp\\htdocs\\...', 'F:\\Xamp\\htdocs\\...', Object(Wp_Scss)) #2 F:\Xamp\htdocs\Website\wp-content\plugins\wp-scss\wp-scss.php(209): Wp_Scss->compile() #3 F:\Xamp\htdocs\Website\wp-content\plugins\wp-scss\wp-scss.php(193): wp_scss_compile() #4 F:\Xamp\htdocs\Website\wp-includes\class-wp-hook.php(292): wp_scss_needs_compiling('') #5 F:\Xamp\htdocs\Website\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #6 F:\Xamp\htdocs\Website\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #7 F:\Xamp\htdocs\Website\wp-settings.php(582): do_action('wp_loaded') #8 F:\Xamp\htdocs\Website\wp-config.php(90): require_once('F:\\Xamp\\htdocs\\...') #9 F:\Xamp\htdocs\Website\wp-load.php(37): require_once('F:\\Xamp\\htdocs\\...') #10 F:\Xamp\htdocs\Website\wp-admin\admin.php(34): require_once('F:\\Xamp\\htdocs\\...') #11 F:\Xamp\htdocs\Website\wp-admin\index.php(10): require_once('F:\\Xamp\\htdocs\\...') #12 {main} thrown in F:\Xamp\htdocs\Website\wp-content\plugins\wp-scss\scssphp\src\Compiler.php on line 243
There has been a critical error on this website. Please check your site admin email inbox for instructions.
Learn more about troubleshooting WordPress.

What is causing this issue and how do I fix this?

Kind Regards

Louie

**Comment by stof** [comment]
This should be reported to the WordPress plugin, not to the library.
