### ISSUE TITLE
Source Map pointing to wrong file

### ISSUE THREAD

**Issue by RickR2H** [scssphp/scssphp#432]
I tried to compile the Joomla 4 source code. The compiler works, but the generated sourcemap points to the wrong file/place in the file when I try to debug the CSS.

Maybe this is due to the fact that there are a lot of SCSS files to compile. The SCSS files can be found in the Joomla 4 Branch.
https://github.com/joomla/joomla-cms/tree/4.0-dev/templates/cassiopeia/scss

I hope you can fix this!

Thanks in advance!

**Comment by stof** [comment]
Can you provide more details about what you expect, what you get instead and how the compiler is configured ? I never used joomla, so I have no idea how scssphp is configured in it exactly (and I don't know either how to reproduce the issue based only on that link)

**Comment by stof** [comment]
thus, AFAICT, Joomla uses the official Sass implementation (through their npm package for the JS version of dart-sass), not scssphp.

**Comment by RickR2H** [comment]
Thanks @stof for your reply. I'll clarify a bit. I've create a new template based on the new Joomla 4 Cassiopeia template. For customization purposes it would be really helpful if we can do small adjustment online an compile the code. But for debugging the SCSS files it would be helpful if the source map is correct. I created a plugin to help with the compiling process.

The only way I can think of is on online example, which is a lot of work to do. But if you are willing to take a look it is worth the effort. Could you provide me with your e-mail address so I can sent you a working example and access to the files?

Thanks in advance!

**Comment by Hackwar** [comment]
Joomla does use the official Sass implementation right now, but we are looking into adopting SCSSPHP as well as a second option/feature for future versions.

**Comment by RickR2H** [comment]
@Hackwar I was looking into creating a plugin which compiles SASS when the site is online. Sometimes small changes are needed when a new component is installed. Using such a plugin eliminates the work on setting up a whole dev environment for a small change. The SCSSPHP compiles like it should, Only problem is that the source map is not correct. That's why it is not practical to use as dev tool. @stof As Joomla 4 is now stable, I can setup a test environment for you to check why the source map are not in sync with the SASS files. Let me know is you are willing to take a look.

**Comment by stof** [comment]
@RickR2H Well, the first thing that would be helpful is being able to see the code that uses Scssphp (to be able to detect any misconfiguration in that code) and getting more details about *what* is wrong in the sourcemap (which kind of mismatch).

**Comment by stof** [comment]
Closing this as no answer has been provided

**Comment by Hackwar** [comment]
Joomla will unfortunately not adopt SCSSPHP.
