### ISSUE TITLE
Does the Server branch still work with 1.5?

### ISSUE THREAD

**Issue by jljr222** [scssphp/scssphp#433]
I've noticed the server repo has not been updated in a long time and I would imagine it needs to be updated to work with 1.5? Are there any plans to do this? That repo is a big part of a few projects I do.

**Comment by robocoder** [comment]
No, it hasn't been updated to work with `scssphp/scssphp` 1.5 yet. There is an outstanding PR which I plan to review and merge.
* https://github.com/scssphp/server/pull/5

Discussion here on whether or not to continue maintaining it:
* https://github.com/scssphp/server/issues/4

**Comment by stof** [comment]
Well, it probably works with 1.5 but with lots of deprecation warnings.

but anyway, discussing that on the server repo would be a better place.

**Comment by stof** [comment]
I'm closing this in favor of the issue on the server repository.
