### ISSUE TITLE
Help - How to use Formatter

### ISSUE THREAD

**Issue by STV11C** [scssphp/scssphp#44]
Hi, amazing job on this project!
I have a question relating to how to use the Formatter (Compressed) in my implementation below. I just can't work it out. Thanks in advanced!

```
$inputFilename=get_template_directory() . '/css/XXX.scss';
$outputFilename='XXX.css';
$inputPath=get_template_directory() . '/css/';
$outputPath=get_stylesheet_directory() . '/css/';
	
$compiler = new ScssPhp\ScssPhp\Compiler();
$compiler->addImportPath($inputPath);
$compiler->setVariables($variables);
$input = file_get_contents($inputFilename);
$compiler->setVariables($variables);
$output = $compiler->compile($input);
file_put_contents($outputPath.$outputFilename, $output);
```

**Comment by robocoder** [comment]
You have to use `setFormatter()`.

Please refer to the "Output Formatting" section of the docs:
* https://scssphp.github.io/scssphp/docs/

**Comment by STV11C** [comment]
Thanks for reply. I tried this but doesn't work:
Any help would be very appreciated. Thanks

![image](https://user-images.githubusercontent.com/5532744/64659241-0072c480-d47e-11e9-83aa-92cb9481d488.png)

**Comment by allejo** [comment]
You need to use the class for the formatter.

```php
setFormatter(ScssPhp\ScssPhp\Formatter\Compressed::class)
```

**Comment by STV11C** [comment]
Thank you @allejo. That worked!!! All the best.
