### ISSUE TITLE
Caching Options Documentation

### ISSUE THREAD

**Issue by noknokcody** [scssphp/scssphp#446]
I see from intellisence that scssphp has support for caching options. I might be blind but, I can't seem to find documentation for these arguments anywhere. 

Any chance you have a link handy or could add to the doco? 

Cheers,

**Comment by Cerdic** [comment]
Hi,

could be that Cache layer is refactored in the future or even removed, this is an open point (see #316 ) but for now it works this way: 

1/ define your cache options
```
$cacheOptions = [
'cacheDir' => 'dir/to/cache/',
'prefix' => 'context_dependant_prefix_ensuring_non_colliding_cache',
'forceRefresh' => false
];
```

2/ Pass it to the constructor:
```
$scss = new ScssPhp\ScssPhp\Compiler($cacheOptions);
```

the `forceRefresh` option can take the values `false`, `'once'` and `true` as  explained here
https://github.com/scssphp/scssphp/blob/master/src/Cache.php#L53

You can find an example of usage in the SPIP Plugin here

https://git.spip.net/spip-contrib-extensions/scssphp/src/branch/master/scssphp_fonctions.php#L37
https://git.spip.net/spip-contrib-extensions/scssphp/src/branch/master/inc/scssphp_compiler.php#L81

**Comment by noknokcody** [comment]
Cheers!

I do hope that the cache isn't removed entirely. I ran some tests and I'm honestly quite impressed with how efficient it is.
