### ISSUE TITLE
Vendor prefix advice

### ISSUE THREAD

**Issue by STV11C** [scssphp/scssphp#449]
Hi guys. What would be your recommendation to compile the scss with vendor prefixes? 

Any tips or advice for something that works with this library would be helpful.

Cheers
Stephan

**Comment by stof** [comment]
The sass compiler does not have any feature to add vendor prefixes for properties.

I know 2 approaches to handle vendor prefixes (not counting the fact of writing them manually all the time, which is probably not the answer you expect):
- the old approach (used by Bootstrap until their 3.2 version for instance): define Sass mixins that set both the vendor-prefixed properties and the standard property (and take care manually of cleaning useless prefixed properties based on your target browsers)
- the modern approach: use autoprefixer (requires node.js) by applying it on the CSS generated by the Sass compiler.

I'm closing this ticket as it is not an issue in the scssphp library (and not a feature we will ever add as porting autoprefixer to PHP would be a totally separate project and we don't have resources for it, though I found an old [implementation of that on Packagist](https://packagist.org/packages/padaliyajay/php-autoprefixer) that I never tested).
