### ISSUE TITLE
support import once 

### ISSUE THREAD

**Issue by philoSurfer** [scssphp/scssphp#45]
Feature request: 
Support @import once. =)

Currently: scssphp  throws @import loop error when trying to compile a complex theme that would have potentially multiple imports of the same file. 

For reference: **node-sass-import-once** is a typical tool that helps resolve this issue in  bower/gulp compilers.

**Comment by robocoder** [comment]
Use `@scssphp-import-once`.

**Comment by philoSurfer** [comment]
Ideally this would **not** require refactoring a ton of source, when this should be handled at the compiler configuration level as an option switch. As it is with nearly every other SASS compiler environment.

**Comment by robocoder** [comment]
What's the dart-sass compiler option?

**Comment by philoSurfer** [comment]
Here is the topic in Sass language documentation:
<img width="750" alt="Sass___import" src="https://user-images.githubusercontent.com/1044479/64914835-80af5900-d70e-11e9-9de9-d29ebf525be3.png">

**Comment by robocoder** [comment]
Sorry, to be clear, I'm asking what is the dart-sass compiler option that enables "import once"?

**Comment by philoSurfer** [comment]
Why don't you re-open the ticket and we can hash this out publicly? 

As for Dart-sass I do not know, I don't use it.   Maybe it does not need it as an option as this might be its default behavior considering the documentation page explicitly calls out the ability to @import multiple times.  see: above

**Comment by robocoder** [comment]
AFAIK neither dart sass or ruby sass support "import once"  as a compiler option because it's a fundamental change to "import" behaviour. `scssphp` tries to follow the reference implementation; as such, "import once" is a vendor prefixed directive.
