### ISSUE TITLE
Would AddVariables fail if the value starts with a ' ' space character

### ISSUE THREAD

**Issue by shadoath** [scssphp/scssphp#456]
In the WP-SCSS plugin we are calling:

`$this->scssc->addVariables(array_map('ScssPhp\ScssPhp\ValueConverter::parseValue', $variables));`

With the values of:
```
$variables = array(
  'colors' => ' primary #333, secondary #666',
);
```

**Comment by stof** [comment]
To be honest, I don't know whether `ScssPhp\ScssPhp\ValueConverter::parseValue` will work or fail in such case. I suggest you to try.
