### ISSUE TITLE
Release 1.7 breaks things...

### ISSUE THREAD

**Issue by bertrandgorge** [scssphp/scssphp#476]
Hello,

I've updated my setup with the latest version today, and the new release breaks the compiling of my chameleon skin on mediawiki.

Downgrading to 1.6.0 repairs it. I can't find any error message, the CSS is just blank. I'd be happy to debug online if needs be !

**Comment by malberts** [comment]
@bertrandgorge There is a Chameleon bug and I'm doing a fix for the SCSS:
https://github.com/ProfessionalWiki/chameleon/issues/288

**Comment by malberts** [comment]
@bertrandgorge Can you try the newly released Chameleon 3.4.1? It should fix all the percent units used within Chameleon itself. If you have any such usages in your own additional SCSS then you need to fix that manually.

**Comment by stof** [comment]
Closing this as this was an issue in chameleon that relied on non-standard scss, and they fixed it.

**Comment by bertrandgorge** [comment]
Hello @stof and @malberts - thanks a lot - awesome. I confirm all is good now.
