### ISSUE TITLE
Formatter + includes

### ISSUE THREAD

**Issue by RawMajkel** [scssphp/scssphp#48]
I've created my style.php file and it looks like this

```
<?php

    require_once "scss/scssphp/scss.inc.php";
    require_once "scss/scssphp/example/Server.php";

    use ScssPhp\ScssPhp\Compiler;
    use ScssPhp\ScssPhp\Server;

    $scss = new Compiler();
    $scss->setFormatter('ScssPhp\ScssPhp\Formatter\Crunched');

    $server = new Server('scss', null, $scss);
    $server->serve();

?>
```

and then used it in my _head_ section (Wordpress)

`<link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/style.php/style.scss">`

Unfortunately for me the output looks like this:

```
/* compiled by scssphp v1.0.4 on Mon, 23 Sep 2019 12:49:18 +0000 (0.0296s) */
@import 'global/normalize';
@import 'global/bootstrap-grid-v.4.3.1/bootstrap-grid';
@import 'global/fonts';
@import 'global/mixins';
@import 'global/majkelFramework';
@import 'frameworks/glightbox';
@import 'views/cookies';
@import 'views/header';
@import 'views/footer';
@import 'views/index';
p {
    color: red
}
```

So it "works" (color:red is my quick check if the scss is parsed), but all the @imports were ignored. Also I do see that it isn't "Crunched" at all.

All of the included files names, for example "normalize" are "_normalize.scss".

What am I doing wrong?

**EDIT**: I do see 404 errors now for this files, but I just want to make style.css from style.scss -> with all the imported stuff inside. How do I achieve this?

**Comment by robocoder** [comment]
If your imports aren't working as you expected, make sure you have called
```
$scss->setImportPaths('scss');
```
where 'scss' is your root directory to .scss files.

I don't know why your check isn't crunched though.

**Comment by STV11C** [comment]
@RawMajkel Try this instead: 
`$scss->setFormatter('ScssPhp\ScssPhp\Formatter\Crunched::class');`

**Comment by robocoder** [comment]
@STV11C That only works without the single quotes.

**Comment by STV11C** [comment]
@robocoder Yes true. Thanks for the correction. I've updated the comment. Cheers

**Comment by RawMajkel** [comment]
Thanks for your help. I've made some improvements to the style.php file

```
<?php

    require_once "php-functions/scssphp/scss.inc.php";
    require_once "php-functions/scssphp/example/Server.php";

    use ScssPhp\ScssPhp\Compiler;
    use ScssPhp\ScssPhp\Server;

    $scss = new Compiler();
    $scss->setImportPaths('scss/');
    $scss->setFormatter('ScssPhp\ScssPhp\Formatter\Crunched');

    $server = new Server('scss', null, $scss);
    $server->serve();

?>
```

and all is working well with my head stylesheet addition

`<link rel="stylesheet" href="<?php echo get_template_directory_uri(); ?>/style.php/style.scss">`

I have my final question: is there a way to save my compiled file to for example "**style.css**" and load this instead of "**style.php/style.scss**"? I see that "scss_cache" folder is there and it contains some files, but it looks like it's not really used.

I'd be better for me if the browser downloaded only .css files, not .scss ones

![scss](https://user-images.githubusercontent.com/19634548/65488795-264e8f00-deaa-11e9-9998-214474a1eca0.jpg)

Thanks in advance!

**Comment by robocoder** [comment]
style.php should be serving css from cache; you won't see these server side accesses in the browser's network tab.

You can use `bin/pscss` to compile your scss offline into a single file that you serve statically via apache/nginx/etc.
