### ISSUE TITLE
Improve speed of compiler

### ISSUE THREAD

**Issue by RdeWilde** [scssphp/scssphp#49]
We are using scssphp to compile our custom scss and the bootstrap scss altogether. Currently it takes about 5 seconds, which is a bit long for a nice development flow for our frontend developers.

Is there a way to speed up the compiling besides playing with `forceCompilation`?

**Comment by RdeWilde** [comment]
Then the issue should stay open. Because it is an issue. It is 800% slower than node's sass-compiler module.

**Comment by robocoder** [comment]
What does 800% slower mean?

node sass uses libsass. If you want a fair comparison, then use https://github.com/absalomedia/sassphp or starting with Ubuntu bionic, the  php-sass package.

Otherwise there's no way scssphp is going to squeeze out an order of magnitude speed increase.

**Comment by RdeWilde** [comment]
Thank you both, i will look into it
