### ISSUE TITLE
Test on Sass-spec

### ISSUE THREAD

**Issue by Cerdic** [scssphp/scssphp#5]
I pushed on the branch https://github.com/scssphp/scssphp/tree/tests/sass-spec the ability to test the full officiel Sass Specification from https://github.com/sass/sass-spec
(this is not fully finished, it needs to manage @import files in the tests)

At the moment it needs to manualy checkout the sass-spec repo in vendor/sass/sass-spec

I wonder what's the best:
* make a PR to the repo to get a Composer package (but they are not in the composer world and I don't know if this will work super fine on the long term)
* fork the repo, add a composer package declaration an publish the package with scssphp vendor (which means maintain and update in the future, merging with the source repo)
* checkout and integrate the sass-spec in the `test/` directory of this repo

This is not super urgent as it looks like we already have some fixes to do on the cases from the old `scss_test.rb` but I think this is the right direction about testing the sass compliance.

Any opinion about that @robocoder ?

**Comment by robocoder** [comment]
+1 for testing with sass-spec.

Option 4 might be to create a meta package where the `composer.json` utilizes "repositories" to pull in the sass-spec repo, e.g.,
```
{
...
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/sass/sass-spec.git"
        }
    ],
...
}
```

Option 5 would be to remove `tests/sass_test.rb`, and instead use a script to download `sass_test.rb`, `sass-spec`, and other scss frameworks (e.g., `bourbon`, `susy`) for compatibility testing.

**Comment by Cerdic** [comment]
Option 5 seems the easier and simplier at the moment, just added a command 'install-test' in the Makefile for that. Thanks!

**Comment by Cerdic** [comment]
It's in the master now: `make sass-spec` to run this tests
