### ISSUE TITLE
Calculations using 'rem' not working as expected for border-radius after v1.0.4

### ISSUE THREAD

**Issue by joakipe** [scssphp/scssphp#50]
**Code to reproduce issue**
`$scss = new \ScssPhp\ScssPhp\Compiler();`
`echo $scss->compile(file_get_contents('test.scss'));`

**Contents of test.scss**

`$width: 1rem;`
`button {`
`  width: $width/2;`
`  border-radius: $width/2;`
`}`

**Results:**
@1.0.3 (working as expected)
`button { width: 0.5rem; border-radius: 0.5rem; }`

@1.0.4
`button { width: 0.5rem; border-radius: 1rem/2; }`

@1.0.5
`button { width: 0.5rem; border-radius: 1rem/2; }`

**Comment by Cerdic** [comment]
This is because of 4b2afc831c4cf0978342ed27acac92c652c6bf9a
I guess we should add some condition on the testing to discriminate if this is a shorthand or a real calculation :/

**Comment by Cerdic** [comment]
As a temporary fix I think you can add a `* 1` in the calculation (didn't check right now)

**Comment by joakipe** [comment]
The only reason I even noticed this issue was because Bootstrap uses 1rem/2 for their switches https://getbootstrap.com/docs/4.3/components/forms/#switches

The `* 1` fix does work, but if this will be fixed in a future release we will just keep using 1.0.3 until then and keep the Bootstrap defaults untouched.

**Comment by Cerdic** [comment]
This is solved with ee2b052b :)
