### ISSUE TITLE
[RFC] Relying on existing open-source packages

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#505]
Currently, the scssphp package is dependency-free. This discussion is about allowing to change that fact.

## Background

In Sass, modules are identified by a URI (following RFC3986). As part of rewriting the library as a port of dart-sass, I would like to do the same in scssphp. This requires having a way to represent URIs. Storing them as string would imply parsing them over and over to manipulate them, which is a bad idea. So this means we need to use an object representation of URIs. This leaves us 2 choices:
- use an existing implementation, i.e. https://packagist.org/packages/league/uri
- maintain our own implementation

Given our limited resources, my choice is clear here: I strongly prefer focusing the scssphp resources on implementing a Sass compiler than using them to maintain copies of existing packages for more generic features.

## Impact

For contributors and maintainers, the impact is that we can benefit from the existing Packagist ecosystem, which makes it a net win IMO.
For users of the library, the impact relates to the way they install the library. As such, the various installation modes are investigated previously.

### Using composer

Projects installing scssphp through composer will not notice any impact, as composer is precisely meant to take care of installing the required dependencies.

### Vendoring scssphp inside CMS plugins

Many CMS plugins integrating scssphp are vendoring the library (due to CMS not using composer to manage plugins in general). These plugins will need to vendor the appropriate dependencies as well.
However, most plugins I checked are actually using composer to manage their vendored libraries (committing the installed packages), which means that they should be fine as well (as composer will installs the necessary packages in their vendoring folder, and so their vendoring process is covered by the previous section).
The notable exception to this is the SPIP plugin maintained by @Cerdic, which currently seems to use the direct download as the source for the vendoring (see next section for the impact, then).
Plugins that currently download libraries without composer to vendor them will need to start taking care of dependencies (the most maintainable implementation being to use composer to update the vendored packages, as it avoids having to maintain manually the dependency list and checking it at each update, but other choices are still possible).

### Downloading the library directly

Our website currently features a download button, that downloads the source archive provided by GitHub. Thanks to the `scss.inc.php` containing an autoloader and the absence of dependencies, this archive is usable directly, without needing Composer. This won't be the case anymore if we add dependencies.
There is 2 possible ways here:

- remove the download button, making composer the only officially supported installation method
- generate a custom archive containing both scssphp and its dependencies and attaching it as an artifact on the GitHub release. The download link would then point to that archive instead of the GitHub source archive

The generation of the custom archive can probably be automated, with a GitHub Actions workflow triggered when we create a new release, that would do a `composer require scssphp/scssphp $RELEASED_VERSION` and then build an archive containing that folder (and the `scss.inc.php` file in that archive would require the generated composer autoloader).

## Target version

This change is targetted at the 2.0 version (there is no reason to use `league/uri` in 1.x), meaning that plugins performing vendoring in a way impacted by the change will only be impacted when upgrading to a new major version.

## Course of actions

2 questions to answer:
- do you agree on using dependencies ?
- if yes, do you think we need to implement a direct download archive bundling dependencies or can we require using composer as the official method ?

@Cerdic @robocoder what is your opinion on those ?

**Comment by mahagr** [comment]
I was first wondering why not just use PSR-7 and let the users decide which library to rely on -- but it looks like the library does have some useful features. The question is which extra features do you need from this library? The library also looks a lot like guzzle, but I guess it was excluded because it is really not meant just to manipulate URLs?

Regarding the second question (direct download), I personally do not care as I use composer.

**Comment by robocoder** [comment]
I delayed adding external dependencies as long as I could but I think it's inevitable.

dart-sass and ruby-sass both leveraged other vendor packages.

For example, to implement the `--watch` option, why reinvent the wheel when you can use something like phpactor/amp-fswatch.

**Comment by robocoder** [comment]
direct downloads only make sense for .phar releases.

I wouldn't bother with tarballs that contain dependencies if there's a chance of version conflicts.

**Comment by stof** [comment]
@mahagr choosing the library does not really make sense. The objects need to be instantiated by scssphp, not received from the outside. And we really need support for URI, not only URL. For instance `sass:math` is not a valid URL, but is a valid URI. The PSR-7 standard does not require supporting other schemes than `https` and `http`, while we definitely need that.

**Comment by Cerdic** [comment]
I fully understand the benefit of relying on Composer ecosystem and requiring external dependencies. This seems sensible to make this move to spare time and development effort.

FYI in the SPIP plugin I generaly use a git checkout of the scssphp repo to update the source in the plugin. I can in the future use a composer install to vendor the required component and disttribute a dependency free plugin. 

We already have the same issue with other libs in more and more plugins development in the SPIP ecosystem, and planning to try to support Composer components at the CMS level to avoid all the plugins to do complicated tricks but this is a long way.

**Comment by stof** [comment]
> For example, to implement the `--watch` option, why reinvent the wheel when you can use something like phpactor/amp-fswatch.

given that the CLI is considered a maintenance tool only (#417), we won't implement `--watch`. But otherwise, that would have been a good example indeed.

> FYI in the SPIP plugin I generaly use a git checkout of the scssphp repo to update the source in the plugin. I can in the future use a composer install to vendor the required component and disttribute a dependency free plugin.

Good. Then I consider this RFC as accepted.
