### ISSUE TITLE
Import the files in the folder.

### ISSUE THREAD

**Issue by devbranch-vitaliy** [scssphp/scssphp#506]
It would be very useful to be able to import not only the target *.scss file, but also the *.scss files in the folder.
An example of a similar solution via the npm package is https://www.npmjs.com/package/gulp-sass-glob.

**Comment by stof** [comment]
Well, the feature of `gulp-sass-glob` is not a feature implemented by the sass compiler. It is a gulp plugin that transforms `@import 'vars/**/*.scss'` into `@import 'vars/foo/bar.scss';@import 'vars/bar/baz.scss';@import 'vars/bar/foobaz.scss';` *before* passing it to the sass compiler (which also means it works only in the entrypoint, not in imported files as they are not processed by that gulp plugin).
You can do the same in PHP by processing the input before giving it to the scssphp Compiler.

But this feature won't be added in scssphp until it becomes a feature available in the Sass language (for which we are not responsible). We explicitly deprecated features that were added in scssphp in the past that were not part of the Sass language, to keep the focus of the project as being a pure PHP implementation of the Sass language (which is already enough work consider the available resources of the team).
