### ISSUE TITLE
Download of master

### ISSUE THREAD

**Issue by gtbu** [scssphp/scssphp#507]
If i download the scssphp-master, it get a 283 kb - file which contains only the src-directory. Is that intended ?
P.S I try to adapt Scssphp1.81. to [Typesetter 5.2 php8](https://github.com/gtbu/Typesetter-5.2-p8/tree/main/include/thirdparty/ScssPhp)  and get (different from 1.2.1) the error : [message] => (string)Class gp\tool\Output\Scss may not inherit from final class (ScssPhp\ScssPhp\Compiler) --- do You support such questions (any guesses?)

**Comment by gtbu** [comment]
No - with 1.2.1 it functions! But i want to update to 1.8.1.

**Comment by robocoder** [comment]
@gtbu It looks like Github ignores the project's `.gitattributes` file when it creates the git archive (.zip or .tar.gz). As you can see, the project's `.gitattributes` file does not contain any `export-ignore` lines that would exclude `bin`, `tests`, etc. So what we're all seeing in the .zip file is github's interpretation.

The best way to get 1.8.1 is to use `git`, i.e.,
```
git clone git@github.com:scssphp/scssphp.git
git checkout v1.8.1
```

**Comment by stof** [comment]
Well, if I take the github download link for `master`, the zip file contains exactly what we specify it to include (inside the `scssphp-master` top-level folder, as github wraps the repo content inside a folder named `reponame-ref`)

@robocoder in the master branch, our gitattributes file definitely exclude those: https://github.com/scssphp/scssphp/blob/fd4fc9edc49f5a4465e11e03b7d6198404adbc22/.gitattributes#L8

**Comment by robocoder** [comment]
@stof Thanks for the correction. I don't know how I managed to see an old (cached?) version of the file.

**Comment by gtbu** [comment]
use ScssPhp\ScssPhp\Compiler\CachedResult;
use ScssPhp\ScssPhp\Compiler\Environment;
But where does the "final" come from ?

**Comment by stof** [comment]
try to put such `var_dump` before the definition of the `gp\tool\Output\Scss` class (so that it executes before the error)

**Comment by gtbu** [comment]
I have dumped the $value and others : In 1.8.1 the compiler.php has so many changes ( compileChild..case Type::T_FUNCTION::  --- cssValidArg ---  getTypeOf ----also public function compileValue  are different. 
As i am not an experienced progrmmer it will take some time. 1.2.1 is running with php8.  I think i better wait for the next version. 
(Another question : what is about dart-sass-php  for bootstrap 5 ?, and a proposal : Integrate a not-node autoprefixer like css-crush (with switch) )
