### ISSUE TITLE
CSS rule filter: invert() creates error message

### ISSUE THREAD

**Issue by MJH1000** [scssphp/scssphp#508]
```
Sass Compiling Error

style.scss
"Missing argument $color: style.scss on line 931, at column 1"
```

SOLUTION:
Make the SASS compiler case sensitive to process only lowercase so filter: INVERT() gets ignored by sass and can be used as css

MORE INFO:
[When Sass and New CSS Features Collide](https://css-tricks.com/when-sass-and-new-css-features-collide/)

**Comment by stof** [comment]
Closing as there is no feedback.
