### ISSUE TITLE
wrong 'parent' (&) when using @at-root with nested selectors

### ISSUE THREAD

**Issue by rnonhebel** [scssphp/scssphp#512]
Example:
```
div {
    span {
        @at-root {
            & {
                color: red;
            }
        }
    }
}
```
should produce (tested using https://www.sassmeister.com/, https://beautifytools.com/scss-compiler.php and https://sass.js.org/):
```
div span {
  color: red;
}
```
but using scssphp the result is:
```
span {
  color: red;
}
```

**Comment by stof** [comment]
I'm adding that to the 2.0 milestone, as I fear it will be hard to fix it in the 1.x codebase.
