### ISSUE TITLE
Formatter for nested properties removes semicolon

### ISSUE THREAD

**Issue by Mythos07** [scssphp/scssphp#52]
After v1.0 (v1.0.1+) when using Crunched or Compressed formatter ($this->keepSemicolons = false;) removes last semicolon for nested property's parent.
Example: `div { border:1px solid red {radius: 10px;} }` compiles to `div {border:1px solid redborder-radius:10px}` instead of `div {border:1px solid red;border-radius:10px}`

**Comment by robocoder** [comment]
For your test case:
```
div { border:1px solid red {radius: 10px;} } 
```

In 1.0.0 and earlier, the crunched output is wrong in other ways:
```
div border:1px solid red{radius:10px}
```

**Comment by Mythos07** [comment]
I've tried the code like this:
div {
    border: 1px solid red
    {
        radius:10px
    }
}
and it compiles into:
div{border:1px solid redborder-radius:10px;}

I think it's a little bit wrong semicolon position and should be:
div{border:1px solid red;border-radius:10px}

Can you, please, check this out?

**Comment by ehasaranga** [comment]
> I've tried the code like this:
> div {
> border: 1px solid red
> {
> radius:10px
> }
> }
> and it compiles into:
> div{border:1px solid redborder-radius:10px;}
> 
> I think it's a little bit wrong semicolon position and should be:
> div{border:1px solid red;border-radius:10px}
> 
> Can you, please, check this out?

You are using the syntax wrong that's why, you need to use & {} on inner curly braces

**Comment by ehasaranga** [comment]
> I've tried the code like this:
> div {
> border: 1px solid red
> {
> radius:10px
> }
> }
> and it compiles into:
> div{border:1px solid redborder-radius:10px;}
> 
> I think it's a little bit wrong semicolon position and should be:
> div{border:1px solid red;border-radius:10px}
> 
> Can you, please, check this out?

Try this , you need add the semicolon 
div {
border: 1px solid red
{
radius:10px
};
}

**Comment by Mythos07** [comment]
That's not realy correct.
SCSS/SASS has rules for nesting properties
https://sass-lang.com/documentation/style-rules/declarations#nesting

Example
.info-page {
  margin: auto {
    bottom: 10px;
    top: 2px;
  }
}
that will be converted into:
.info-page {
  margin: auto;
  margin-bottom: 10px;
  margin-top: 2px;
}
and it works right with other then Crunched or Compressed formatter (that has $this->keepSemicolons = true; parameter).
but with current Crunched or Compressed formatter I'll get this:
.info-page{margin:automargin-bottom:10px;margin-top:2px;}

**Comment by Paragin** [comment]
This also breaks css-rules when using CSS for paged media. For example:

```css
@page specification {
  margin:25mm 10mm;
  @top {
    border-bottom:10mm solid #8cc63f;
  }
  @bottom {
    border-bottom:10mm solid #8cc63f;
  }
}
```

This results in the following (using the Crunshed formatter):

```css
@page specification{margin:25mm 10mm@top{border-bottom:10mm solid #8cc63f}
@bottom{border-bottom:10mm solid #8cc63f}
}
```

Note that the semicolon after the 'margin' rule is removed.

**Comment by Cerdic** [comment]
I think the fix is working, tested on
```
.info-page {
  margin: auto {
    bottom: 10px;
    top: 2px;
  }
  padding:auto;
}
.info-page {
  margin: auto {
    bottom: 10px;
    top: 2px;
  }
}
.info-page {
  margin: auto;
}
div {
    border: 1px solid red
    {
        radius:10px
    }
}
@page specification {
  margin:25mm 10mm;
  @top {
    border-bottom:10mm solid #8cc63f;
  }
  @bottom {
    border-bottom:10mm solid #8cc63f;
  }
}
```

giving with the `compressed` or  `crunched`:
```
.info-page{margin:auto;margin-bottom:10px;margin-top:2px;padding:auto}.info-page{margin:auto;margin-bottom:10px;margin-top:2px}.info-page{margin:auto}div{border:1px solid red;border-radius:10px}@page specification{margin:25mm 10mm;@top{border-bottom:10mm solid #8cc63f}@bottom{border-bottom:10mm solid #8cc63f}}
```
