### ISSUE TITLE
Alternative to dynamic manipulating import path

### ISSUE THREAD

**Issue by shyim** [scssphp/scssphp#526]
Hey,

we currently use `addImportPath` to rewrite `~vendor/bootstrap/scss/bootstrap` to a specific vendor folder. It looks like passing a callable to `addImportPath` is now deprecated. How could we do this without triggering a deprecations? 😓

**Comment by stof** [comment]
Passing a callable is **not** deprecated.

The only deprecated thing is passing a callable that returns a non-null values for an input for which `Compiler::isCssImport($url)` returns `true`

**Comment by shyim** [comment]
I have excactly that purpose 🤔 .

SCSS
```
@import '~vendor/flatpickr/dist/flatpickr.min.css';
```

and I want to manipulate the link to `src/Storefront/Resources/app/storefront/vendor/flatpickr/dist/flatpickr.min.css` on the fly because it has at starting `~vendor`.

isCssImport is true for that file name, so I can't implement this approach

**Comment by stof** [comment]
you need to import it as `@import '~vendor/flatpickr/dist/flatpickr.min';`, without the explicit extension.

The Sass language spec defines that a `@import` for something ending in `.css` must be rendered as a CSS `@import` directive rather than being processed as a Sass import.

**Comment by shyim** [comment]
Ahh. Thanks :)
