### ISSUE TITLE
Replacing a declared variable's value

### ISSUE THREAD

**Issue by matteo-greco** [scssphp/scssphp#537]
Hey all. I'm trying to get scssphp to replace a declared variable's value. I'm using this code:

```scss
// scss-php-test.scss
$test: 10rem;

body {
  font-size: $test;
}
```

```php
// scss-php-test.php
use ScssPhp\ScssPhp\Compiler;
use ScssPhp\ScssPhp\ValueConverter;

$variables = array(
	'test' => ValueConverter::parseValue( '30rem' ),
);

$compiler = new Compiler();
$compiler->setSourceMapOptions( Compiler::SOURCE_MAP_NONE );
$source_scss = './scss-php-test.scss';
$scss_contents = file_get_contents( $source_scss );
$compiler->addVariables( array_map( 'ScssPhp\ScssPhp\ValueConverter::parseValue', $variables ) );
$css = $compiler->compileString( $scss_contents )->getCss();
echo $css;
```

I'd expect the output to be `body { font-size: 30rem; }`, but I get `body { font-size: 10rem; }` instead.
I tried using `replaceVariables()` as well, but to no avail.
Digging in the library's code, it seems like the `Compiler::set()` method is called on my `$variables['test']` item first, and then on the value from the scss file, effectively overwriting it.

Am I misunderstanding what `addVariables()` and `replaceVariables()` are for? Is there any way of achieving this, other than not declaring the variables in the SCSS files?

**Comment by mahagr** [comment]
You need to use `$test: 10rem !default;`, otherwise the previously declared value gets overridden.

**Comment by stof** [comment]
See https://scssphp.github.io/scssphp/docs/extending/preset-variables.html for the documentation about that feature.

@mahagr is right. The variables declared from PHP code are semantically equivalent to prepending some variable declarations to the input code. This means that if the source also declares that variable without `!default`, the previous declaration gets overridden.

**Comment by matteo-greco** [comment]
Damn. I read the documentation, but I completely reversed the meaning. I though you had to add `!default` if you did NOT want the SCSS variable to be overwritable. I'm a little rusty on SCSS basics. Sorry, my bad.

Thank you, I see my code working now!

**Comment by stof** [comment]
Well, `!default` is about making that variable declaration not overriding an already defined value (i.e. making it declare a default value if the variable is not defined yet, hence its naming), which is exactly what your declaration in the source is achieving in your case.
