### ISSUE TITLE
expecting color, function received

### ISSUE THREAD

**Issue by PrestaSafe** [scssphp/scssphp#54]
Hello, 

i'm trying to compile my template, but i've this issue, 
all of my path seems ok. 

I think it came from bootstrap 4.0.0

**Comment by robocoder** [comment]
Please provide a minimal testcase.

**Comment by jpyrat** [comment]
Hi, same case with _variables.scss from boostrap 4.3.1.

Minimal test case : 
```
$blue:    #007bff !default;

$theme-colors: () !default;
// stylelint-disable-next-line scss/dollar-variable-default
$theme-colors: map-merge(
  (
    "primary":    $blue
  ),
  $theme-colors
);

$link-color:                              theme-color("primary") !default;
$link-hover-color:                        darken($link-color, 15%) !default;
```

https://codepen.io/jpyrat/pen/rNNJdqe

**Comment by jpyrat** [comment]
Just found that this syntax works as expected : 
`$link-color:                              map-get($theme-colors, "primary") !default;`

So, why Bootstrap is writing : `theme-color("primary")` ?
And why https://sass-lang.com/documentation/values/maps is writing `map.get` with a dot, and not a minus sign ?

**Comment by Cerdic** [comment]
Your test-case is missing the `theme-color` function from bootstrap you can find in the `_functions.scss` file:

```
@function theme-color($key: "primary") {
  @return map-get($theme-colors, $key);
}
```

**Comment by PrestaSafe** [comment]
Sorry guys, it came from me, my server haven't sync files correctly. 
It's seems to work fine now.
