### ISSUE TITLE
UTF-8 representations encoded (not escaped ?)

### ISSUE THREAD

**Issue by ryssbowh** [scssphp/scssphp#542]
Hi,

I'm trying to compile the fontawesome library (https://www.npmjs.com/package/@fortawesome/fontawesome-free) 5.15.4.
I see all utf-8 representations are replaced with actual utf-8 characters that can't be read by browsers, example :

Scss :
```
$fa-var-adjust: \f042;
$fa-css-prefix: fa !default;
@function fa-content($fa-var) {
  @return unquote("\"#{ $fa-var }\"");
}

.#{$fa-css-prefix}-adjust:before { content: fa-content($fa-var-adjust); }
```
Css
```
@charset "UTF-8";
.fa-adjust:before {
  content: "\";
}
```
If I compile this with webpack + sass-loader it gives me this :
```
.fa-adjust:before {
  content: "\f042";
}
```
Would that be an issue with the unquote function ?
Or an issue with fontawesome ? A issue that seems related : https://github.com/FortAwesome/Font-Awesome/issues/17644#issue-810564592
Thanks

**Comment by stof** [comment]
which version of scssphp are you using ?

With the latest version, I get this output:

```css
@charset "UTF-8";
.fa-adjust:before {
  content: "";
}
```

And this is correct CSS (it does not escape the UTF-8 character, but that's equivalent CSS). I don't have the extra `\` in my output.

**Comment by ryssbowh** [comment]
Using 1.10.0. And I don't have the extra `\` either actually, must have copied the wrong line.

Redone a couple of tests and seems to be working properly, just strange that my text editor would transform the utf-8 representation from the css file when it doesn't with the webpack css file.
As you said it's valid css and the browser does read them.

Thank you
