### ISSUE TITLE
Compiling to (un)compressed at the same time

### ISSUE THREAD

**Issue by Hackwar** [scssphp/scssphp#543]
I'm trying to use this in a project where I would need to compile both an uncompressed and a compressed version of the CSS at the same time. Compiling the uncompressed version together with a map file already takes a long time. Compiling everything again for the compressed version might even run into script timeouts. Would it be possible to generate the compressed version from the uncompressed without recompiling?

**Comment by stof** [comment]
> Would it be possible to generate the compressed version from the uncompressed without recompiling?

that would be the job for a CSS minifier, which is a different kind of tool, and is out of the scope of scssphp.

**Comment by Hackwar** [comment]
I was thinking this would be possible, since you already provide a minified output.

**Comment by stof** [comment]
Changing the output we generate while we generate it (not generating newlines or spaces, etc...) is a totally different kind of work than talking the expanded CSS file as input and generating a compressed one from it.

**Comment by Hackwar** [comment]
ok. In that case this issue has been solved. 😃
