### ISSUE TITLE
Undefined offset: 1 in Compiler.php (line 6365)

### ISSUE THREAD

**Issue by denis-g** [scssphp/scssphp#545]
Hi,
I'm added on my empty project [MDB](https://github.com/mdbootstrap/mdb-ui-kit/tree/master/src/scss) and after deploy gives the error message.

```shell
Compilation from source: /var/www/html/app/css/mdb.free.scss
Notice: Undefined offset: 1 in /var/www/html/vendor/scssphp/scssphp/src/Compiler.php on line 6365
```

Error on [this line](https://github.com/scssphp/scssphp/blob/v1.10.0/src/Compiler.php#L6365):

```php
        // specific cases ?
        if (\in_array($functionName, ['libRgb', 'libRgba', 'libHsl', 'libHsla'])) {
            // notation 100 127 255 / 0 is in fact a simple list of 4 values
            foreach ($args as $k => $arg) {
>               if ($arg[1][0] === Type::T_LIST && \count($arg[1][2]) === 3) {
                    $args[$k][1][2] = $this->extractSlashAlphaInColorFunction($arg[1][2]);
                }
            }
        }
```

`$args` return `null`.

What is the cause of the problem?

---

scssphp 1.10.0
PHP 7.4.22

**Comment by stof** [comment]
Looks like our logic to handle the `/`-separate alpha channel has a bug when using trailing commas in the arguments (also due to the weird way we represent those internally). I'll try to fix that

**Comment by stof** [comment]
And this is now released
