### ISSUE TITLE
Compiling foundation 6.7.3 ...

### ISSUE THREAD

**Issue by ghwaldo** [scssphp/scssphp#546]

**Comment by ghwaldo** [comment]
... gives error.
What i see at the end is:

ScssPhp\ScssPhp\Compiler::evalSelectors on l
      ine 1, at column 12: typo3conf/ext/apartment_sparding/Resources/Private/Scss
      /foundation/xy-grid/_cla..


Something in xy-grid/_classes.scss

Cannot get further infos on that for now.
Anyone can help ?

**Comment by stof** [comment]
Can you provide the full error instead of only part of it ?

**Comment by stof** [comment]
And also a reproducing case, if possible.

**Comment by stof** [comment]
I tried reproducing this, but I failed (btw, our testsuite includes a test compiling foundation, currently using the 6.7.4 latest release).

I suspect that this either implies a custom foundation setup not described in the issue, or an older version of scssphp.

**Comment by stof** [comment]
Closing as there is no answer
