### ISSUE TITLE
v1.10.1 assert errors

### ISSUE THREAD

**Issue by axllent** [scssphp/scssphp#553]
It appears that the 1.10.1 release contains several [assert functions](https://github.com/scssphp/scssphp/blob/v1.10.1/src/Formatter.php#L352) that is causing `Uncaught AssertionError: assert($this->currentBlock->sourceLine !== null)`. This appears to have already changed on `master` so I'm guessing it got overlooked when the release was created?

**Comment by stof** [comment]
Can you share a reproducer for the issue ?

**Comment by axllent** [comment]
Sorry, I should have provided that info (and thanks for the branch clarification - I had only taken a quick peak before going to bed). It appears to be happening when compiling Bootstrap (v5.1.3) with sourcemaps (either inline or file). Excluding sourcemap generation "fixes" the issue. Does that answer your question?

**Comment by stof** [comment]
Can you share a full reproducer of how you run this compilation ? I am able to compile Bootstrap 5 with sourcemaps without any assertion errors, so there must be something different in the way you use scssphp.

**Comment by cedric-anne** [comment]
Hi,

I have a similar issue.

I added the `$lastLine` value to asserter params, in order to identify which line fails, and it shows that the related line is `/* rtl:begin:remove */` (seems to be this one: https://github.com/twbs/bootstrap/blob/main/scss/mixins/_utilities.scss#L53).

You should be able to reproduce with this. Just run `php test.php` on PHP 8.1.
[scsstest.zip](https://github.com/scssphp/scssphp/files/8162294/scsstest.zip)

Regards

**Comment by axllent** [comment]
@cedric-anne At first I wasn't able to replicate an error your test either, so I went about trying to replicate mine in the most simplistic manner possible. Then I could not replicate my own locally using my ubuntu-installed PHP (version 8.0.16).

I then tried my test on my development server (which ironically also runs PHP 8.0.16, but a self-compiled version on Alpine Linux inside Docker) which did reproduce the error. So I tested the official PHP docker images for both 8.0 and 8.1 (Ubuntu & Alpine containers) and can reproduce it there too.

@stof - I'm hoping you have docker as I've put together a very simplistic test which will replicate the error. Extract and run the `./run.sh` - it requires a local `composer` to install phpscss & bootstrap, but will run the test using docker and the official `php:8.0-cli` image. You can modify the `IMAGE` variable in `run.sh` to try other docker versions (8.1 also fails, but 7.4 does not). Note that I also get the same error on my own self-compiled PHP version which has nothing to do with these official docker images.

I hope this helps debug the issue! [scsstest.zip](https://github.com/scssphp/scssphp/files/8166154/scsstest.zip)

**Comment by stof** [comment]
> I then tried my test on my development server (which ironically also runs PHP 8.0.16, but a self-compiled version on Alpine Linux inside Docker) which did reproduce the error.

check whether your development server has assertions enabled or disabled (for a development server, it is recommended to enable them).

**Comment by stof** [comment]
OK, I found the reason why the AssertionError was not always shown. Our Formatter leaks an output buffer. If I properly clean it on exceptions, the error is displayed.

The reason why the docker image shows it is because it has `display_errors` enabled.

I fixed that in #556

**Comment by axllent** [comment]
Awesome, thanks @stof - I can confirm that I no longer get an error with the latest 1.10.2 release. Thanks again!
