### ISSUE TITLE
.php-error #adminmenuback

### ISSUE THREAD

**Issue by marcokumanaku** [scssphp/scssphp#562]
In wordpress, with php> 8 I see this div error caused by the library, how can I fix it?
There are no error messages but an empty space in the top dashboard bar.
I don't have any plugins installed and I'm sure it's the library because when i disable the library the empty space disappear.
Please, help me!

![Immagine](https://user-images.githubusercontent.com/37437087/158769624-fc0a75ee-7298-45ce-a5b6-639cff9d1212.jpg)

**Comment by stof** [comment]
You will need to debug where this div comes from. But scssphp does not add any div anywhere. It might be a bug of the wordpress plugin you use rather than of this library.

**Comment by marcokumanaku** [comment]
I just found the error, my compilation is wrong, I replaced the following line:

`$cssOut = $scss->compile($scssIn);`

with the following:

`$cssOut = $scss->compileString($scssIn)->getCss();`

Now everything works correctly and without errors.
Thank you.
