### ISSUE TITLE
Cannot get compression to work

### ISSUE THREAD

**Issue by gcwebsites** [scssphp/scssphp#563]
Here is my code and for some reason I cannot get compression to work....

```
require 'scssphp/scss.inc.php';

use ScssPhp\ScssPhp\Compiler;

$compiler = new Compiler();
// $scss->setLineNumberStyle(Compiler::LINE_COMMENTS);
// $compiler->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
$compiler->setImportPaths('./');

$result = $compiler->compileString('@import "style.scss";');

file_put_contents('my-style.css', $result->getCss());
```

Any guidance would be great.

**Comment by stof** [comment]
What error are you getting exactly ?

**Comment by gcwebsites** [comment]
```Fatal error: Uncaught Error: Call to undefined method ScssPhp\ScssPhp\Compiler::setFormatter() in /home/xxx/public_html/wp-content/themes/xxx/scss-master/serve.php:22 Stack trace: #0 {main} thrown in /home/xxx/public_html/wp-content/themes/xxx/scss-master/serve.php on line 22```

**Comment by gcwebsites** [comment]
With this code.
```<?php
require 'scssphp/scss.inc.php';

use ScssPhp\ScssPhp\Compiler;

$compiler = new Compiler();
// $scss->setLineNumberStyle(Compiler::LINE_COMMENTS);
$compiler->setFormatter('Leafo\ScssPhp\Formatter\Compressed');
$compiler->setImportPaths('./');

$result = $compiler->compileString('@import "style.scss";');

file_put_contents('my-style.css', $result->getCss());```

**Comment by stof** [comment]
I see that your path contains a folder named `scss-master`. Is this referring to the master branch of this repo ? If yes, this is expected because the master branch now contains the upcoming  version of the library where we have BC breaks. Please use a released version instead.

Side note: `Leafo\ScssPhp\Formatter\Compressed` is an invalid value for `setFormatter`. You cannot mix `scssphp/scssphp` and the older `leafo/scssphp`.
And if you use scssphp 1.4+ (which I hope you do as  1.4.0 is already quite old), the `setFormatter` method is deprecated in favor of `setOutputStyle`.

**Comment by gcwebsites** [comment]
Okay, so I have made sure I am running the latest version. ```scss-master``` is where I am running the serve.php compiler within my Wordpress theme.

What is the correct code of the setOutputStyle then?

I've tried ```$compiler->setOutputStyle('OutputStyle::COMPRESSED');```

But I get errors:
```Fatal error: Uncaught InvalidArgumentException: Invalid output style "OutputStyle::COMPRESSED". in /home/xxx/public_html/wp-content/themes/xxx/scss-master/scssphp/src/Compiler.php:5196 Stack trace: #0 /home/xxx/public_html/wp-content/themes/xxx/scss-master/serve.php(22): ScssPhp\ScssPhp\Compiler->setOutputStyle() #1 {main} thrown in /home/xxx/public_html/wp-content/themes/xxx/scss-master/scssphp/src/Compiler.php on line 5196```

**Comment by stof** [comment]
it is $compiler->setOutputStyle(OutputStyle::COMPRESSED);` (with the proper use statement). It is not a string being passed

**Comment by Micemade** [comment]
@stof provided the correct code, and the use statement is this:
`use ScssPhp\ScssPhp\OutputStyle;`

**Comment by gcwebsites** [comment]
Thanks guys! I've got it working!

Thank you to you both!
