### ISSUE TITLE
grid-area: 1/2; does not work

### ISSUE THREAD

**Issue by a-r-m-i-n** [scssphp/scssphp#564]
Hi,
when I am using this in SCSS:

```
.whatever {
  grid-area: 1/2; 
}
```

It will be compiled to:
```
  grid-area: 0.5; 
```

which is is not a valid value, for this property.

I tried to put quotes around, but it did not work. In the end I used the long notation:
```
grid-row-start: 1;
grid-column-start: 2;
```
But I think, this value should not get calculated.

**Comment by stof** [comment]
Related to https://github.com/scssphp/scssphp/issues/146
scssphp currently does not implement the official heuristic regarding `/` but a custom one. This will be solved by the upcoming version 2 of scssphp.

If you want to generate the separator, a workaround is to use `unquote('1/2')`, to avoid parsing it as a division.

**Comment by stof** [comment]
I'm closing this issue as this is tracked in #146
