### ISSUE TITLE
map.get() doesn't work.

### ISSUE THREAD

**Issue by noskill24** [scssphp/scssphp#584]
This construction doesn't work for me as described here:
https://sass-lang.com/documentation/values/maps
```
$fw: ("regular": 400, "medium": 500, "bold": 700);

p {
  font-weight: get($fw, "bold");
}
```
The resulting css is:
```
p {
  font-weight: get(("regular": 400, "medium": 500, "bold": 700), "bold");
}
```

**Comment by stof** [comment]
The function name is `map-get`, not `get`. See https://sass-lang.com/documentation/modules/map#get
