### ISSUE TITLE
PHP 8.2: Deprecate ${} string interpolation

### ISSUE THREAD

**Issue by Daijobou** [scssphp/scssphp#587]
See https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L3401
Line `if (\is_callable([$this, $fn = "op${ucOpName}${ucLType}${ucRType}"])) {`

this type of `string interpolation` is [deprecated in PHP 8.2](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation)

This variants still works:
```
"Hello {$world}";
"Hello $world";
```

**Comment by TimWolla** [comment]
Already fixed with #582, but apparently not merged into master (also not released yet).
