### ISSUE TITLE
 handling the scss event returned with error code 127

### ISSUE THREAD

**Issue by joneldiablo** [scssphp/scssphp#59]
I trying to use this project with composer script: `composer scss`

this is the composer file:
```
{
...
  "require": {
    "scssphp/scssphp": "^1.0"
  },
  "scripts": {
    "scss": "bin/pscss -f compressed < ./style.scss"
  }
}
```

but it returns 

`Script bin/pscss -f compressed < ./style.scss handling the scss event returned with error code 127`

**Comment by allejo** [comment]
`<` means you're feeding the contents of the file into the command. Just give `pscss` the path to the SCSS file.

```
bin/pscss -f compressed ./style.scss
```
