### ISSUE TITLE
Problems to use an ID in SCSS

### ISSUE THREAD

**Issue by janstieler** [scssphp/scssphp#604]
Problems to use an ID in scss.
I got this error `parse error: failed at `#38fdae8d-9ee2-46e3-8046-3d6de96a2b7c {` (stdin) on line 73, at column 1`
The ID I try to use is `#38fdae8d-9ee2-46e3-8046-3d6de96a2b7c` with `#b66cf5d0-9783-4b73-bbcb-94338e1ff3c6` it works.
I can't change something on the ID generation because its a generic ID from a CMS module.

Have someone any idea whats happend with this ID?

**Comment by stof** [comment]
CSS identifiers are not allowed to start with a digit. So if your identifier starts with a digit, you need to write it as an escape sequence to have a valid CSS selector.

**Comment by robocoder** [comment]
If I understand the EBNF correctly, it would seem `#38fdae8d-9ee2-46e3-8046-3d6de96a2b7c` is a valid selector.

https://www.w3.org/TR/CSS21/grammar.html

```
simple_selector
  : element_name [ HASH | class | attrib | pseudo ]*
  | [ HASH | class | attrib | pseudo ]+
  ;

"#"{name}		{return HASH;}

name		{nmchar}+

nmchar		[_a-z0-9-]|{nonascii}|{escape}
```

**Comment by stof** [comment]
The up-to-date CSS spec is at https://www.w3.org/TR/selectors-3/#id-selectors

And here, it clearly says:

> An ID selector contains a "number sign" (U+0023, #) immediately followed by the ID value, which must be an CSS [identifiers](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier).

So `#38fdae8d-9ee2-46e3-8046-3d6de96a2b7c` is *not* a valid selector.
