### ISSUE TITLE
Variable bug

### ISSUE THREAD

**Issue by wilecoyte78** [scssphp/scssphp#61]
@function add($value1, $value2, $return-calc: true) {
      @if $value1 == null {
        @return $value2;
      }

      @if $value2 == null {
        @return $value1;
      }

      @if type-of($value1) == number and type-of($value2) == number and comparable($value1, $value2) {
        @return $value1 + $value2;
      }

      @return if($return-calc == true, calc(#{$value1} + #{$value2}), #{$value1} + #{$value2});
    }
    
    $input-height:                          add($input-line-height * 1em, add($input-padding-y * 2, $input-height-border, false)) !default;
    
    .form-control {
      height: $input-height;
    }

Expected output:

    .form-control {
      height: calc(1.5em + 0.75rem + 2px);
    }

Generated output:

    .form-control {
      height: calc(1.5em + 0.7708333333rem);
    }

**Comment by Cerdic** [comment]
The complete test case is neither working on Sass-meister:
```
@function add($value1, $value2, $return-calc: true) {
  @if $value1 == null {
    @return $value2;
  }

  @if $value2 == null {
    @return $value1;
  }

  @if type-of($value1) == number and type-of($value2) == number and comparable($value1, $value2) {
    @return $value1 + $value2;
  }

  @return if($return-calc == true, calc(#{$value1} + #{$value2}), #{$value1} + #{$value2});
}

$input-line-height: 1.5;
$input-padding-y: 0.375rem;
$input-height-border: 2px;

$input-height: add($input-line-height * 1em, add($input-padding-y * 2, $input-height-border, false)) !default;

.form-control {
  width:add($input-padding-y * 2, $input-height-border, false);
  height: $input-height;
}
```

gives with SassMeister:

```
.form-control {
  width: 0.75rem2px;
  height: calc(1.5em + 0.75rem2px);
}
```

and with ScssPHP:
```
.form-control {
  width: 0.7708333333rem;
  height: calc(1.5em + 0.7708333333rem); }
```

Changing the 3rd argument to true in `add($input-padding-y * 2, $input-height-border, false);` make it works on SassMeister:

```
.form-control {
  width: calc(0.75rem + 2px);
  height: calc(1.5em + calc(0.75rem + 2px));
}
```

as well as on ScssPHP:
```
.form-control {
  width: calc(0.75rem + 2px);
  height: calc(1.5em + calc(0.75rem + 2px)); }
```

Even if this is not the expected result in both case, I don't think there is a bug in ScssPHP here :)

**Comment by wilecoyte78** [comment]
Ok I think it is because SassMeister is at dart version 1.18.0 and Sass itself is at dart version 1.23.7

**Comment by wilecoyte78** [comment]
I found when I change the option to Sass v3.5.6 it works on SassMeister
