### ISSUE TITLE
Error compiling $color is not a color

### ISSUE THREAD

**Issue by mrelliot69** [scssphp/scssphp#625]
I'm trying to compile my files ( using bootstrap 5.0.2) and allways get this error
 "Error compiling SASS -> $color: #3d78e3 is not a color.: assets//scss/admin\components/_ribbons.scss on line 153
 
 The error line is this one:
   ` border-color: darken(($value), 10%) transparent transparent;`
   
   from what i checked this seems to be caused by the bootstrap !default on the theme colors, any ideia how to bypass this error without messing on the bootstrap core file?
   
   `$primary:       $blue !default;
$secondary:     $gray-600 !default;
$success:       $green !default;
$info:          $cyan !default;
$warning:       $yellow !default;
$danger:        $red !default;
$light:         $gray-100 !default;
$dark:          $gray-900 !default;`

**Comment by mahagr** [comment]
You need to define the color variables, it looks like those aren't defined in your scss files or variables.

**Comment by stof** [comment]
I think this issue is similar to #504 where the extra parentheses around your `$value` variable gets parsed (wrongly) as a list containing a single value. Using `darken($value, 10%)` should work.
