### ISSUE TITLE
Problème à la mise à jour

### ISSUE THREAD

**Issue by Hypaepa** [scssphp/scssphp#629]
La dernière mise à jour entraine une coupure du site 
`Fatal error: Uncaught Error: Class 'ScssPhp\ScssPhp\Block\MediaBlock' not found in /home/clients/abfd5d56efa825a61b8c5888a8a77915/sites/le-cera/wp-content/plugins/wp-scss/scssphp/src/Parser.php:477 Stack trace: #0 /home/clients/abfd5d56efa825a61b8c5888a8a77915/sites/le-cera/wp-content/plugins/wp-scss/scssphp/src/Parser.php(287): ScssPhp\ScssPhp\Parser->parseChunk() #1 /home/clients/abfd5d56efa825a61b8c5888a8a77915/sites/le-cera/wp-content/plugins/wp-scss/scssphp/src/Compiler.php(502): ScssPhp\ScssPhp\Parser->parse('@import "scratc...') #2 /home/clients/abfd5d56efa825a61b8c5888a8a77915/sites/le-cera/wp-content/plugins/wp-scss/class/class-wp-scss.php(152): ScssPhp\ScssPhp\Compiler->compileString('@import "scratc...', '/home/clients/a...') #3 /home/clients/abfd5d56efa825a61b8c5888a8a77915/sites/le-cera/wp-content/plugins/wp-scss/class/class-wp-scss.php(100): Wp_Scss->compiler('/home/clients/a...', '/home/clients/a...') #4 /home/clients/abfd5d56efa825a61b8c5888a8a77915/sites/le-cera/wp-content/plugins/wp-scss/wp-scss.php(245) in /home/clients/abfd5d56efa825a61b8c5888a8a77915/sites/le-cera/wp-content/plugins/wp-scss/scssphp/src/Parser.php on line 477`

**Comment by pixelkunst-net** [comment]
Same issue with a customer's website, which is down due to this. Any way to downgrade?

**Comment by robocoder** [comment]
This isn't the support site for the WordPress plugin `wp-scss`

**Comment by robocoder** [comment]
Here's their support forum:
* https://wordpress.org/support/plugin/wp-scss/
