### ISSUE TITLE
Version 2: Compiler::getCompileOptions() is private 

### ISSUE THREAD

**Issue by perrelet** [scssphp/scssphp#631]
In version 2,

Compiler::getCompileOptions() is a protected method.

Its handy to have an api to access these parameters and it would be a shame to lose this functionality.

Any thoughts?

Cheers, J

**Comment by stof** [comment]
What is your use case for accessing those ?

**Comment by stof** [comment]
Btw, note that extending the Compiler class is deprecated anyway. So anything that is protected in 1.x would still be inaccessible in 2.x anyway (for a final class, protected or private makes no difference).

**Comment by perrelet** [comment]
@stof Thanks for the reply.

Our use case has been to get access to the source map url, however looking at this I see we actually provide this with `sourceMapURL`. Thus consider my point void. Thanks.
