### ISSUE TITLE
Issue on Bootstrap 5.2

### ISSUE THREAD

**Issue by phuclh** [scssphp/scssphp#632]
I am getting this error on the `_bootstrap_variables.scss` of Bootstrap 5.2

`$map1: map-loop(("primary": #0d6efd, "secondary": #6c757d, "success": #198754, "info": #0dcaf0, "warning": #ffc107, "danger": #dc3545, "light": #f8f9fa, "dark": #212529), to-rgb, "$value") is not a map`

Is this because the compiler doesn't support the Bootstrap 5.2 syntax?

Thank you!

**Comment by stof** [comment]
I don't see any file named `_bootstrap_variables.scss` in the bootstrap 5.2 codebase.
