### ISSUE TITLE
PHP 8.2 - Possible problem with string interpolation in Exception class

### ISSUE THREAD

**Issue by moseleyi** [scssphp/scssphp#633]
I see that in `SassScriptException` in line 28 we have this

```
$varDisplay = !\is_null($name) ? "\${$name}: " : '';
```

which could cause problems in PHP 8.2 due to deprecation of `${}` string interpolation

**Comment by stof** [comment]
This is *not* using a `${}` interpolation. This is rendering a `$` character (see the escaping applied on that `$`) followed by a non-deprecated interpolation syntax.
