### ISSUE TITLE
How to compile multiple sass entry files into a single css file

### ISSUE THREAD

**Issue by kossahl** [scssphp/scssphp#636]
First of all sorry if this is the wrong place to ask about how to use scssphp but I did not find a better place.
If there is any please feel free to close this issue and point me into the right direction.

consider the following structure

```
mainproject\sass\main.scss
mainproject\sass\modules\_importA.scss
mainproject\sass\vendor\bootstrap.scss

subprojectA\sass\main.scss
subprojectA\sass\modules\_importA.scss
subprojectA\sass\modules\_importB.scss

subprojectB\sass\main.scss
subprojectB\sass\modules\_importA.scss
subprojectB\sass\modules\_importB.scss
subprojectB\sass\modules\_importC.scss
```

where main.scss files act as entrypoint for there specific projects. Files in the modules folder are @imported in their respective projects main.scss file. Additionally the subprojects rely on bootstrap being @imported in the mainproject.

How would I use scssphp to compile all main.scss files into a single css file?

**Comment by stof** [comment]
You will need to create a scss file that import the various main.scss files and compile that file as the entrypoint if you want to combine everything.
Alternatively, you can compile the 3 entrypoints separately and then combine the outputs together into a single CSS file (outside of scssphp)

**Comment by stof** [comment]
@noskill24 you would have to use a concatenation utility that supports source maps (not sure whether this exists in PHP though)
