### ISSUE TITLE
How we can minify compiled version of CSS?

### ISSUE THREAD

**Issue by AmentoTech** [scssphp/scssphp#637]
Hello @Community

How we can minify compiled version of CSS? We are using this library in our projects and we are facing issue to compile as minified version

Thank you

**Comment by stof** [comment]
"we are facing issues" is not a report that is actionable by us.

**Comment by AmentoTech** [comment]
Thank you @stof 

Maybe you can let me know which parameter to pass to compile as minified version

`$css = $compiler->compile($scssContents);`

![3](https://user-images.githubusercontent.com/108173755/210342691-8c76705d-5833-4971-8961-ba370f2e3cb2.png)


Thank you

**Comment by stof** [comment]
See https://scssphp.github.io/scssphp/docs/#output-formatting for the doc about output formatting
