### ISSUE TITLE
@extend from one scss file to another

### ISSUE THREAD

**Issue by STV11C** [scssphp/scssphp#639]
Is it possible to have references to `@extend` a class from one scss file to a different scss file during the compilation, where the files are set to be generated as separate CSS files?

For example - I am compiling a **main.css** (from a bunch of Bootstrap scss files), but I am also compiling a separate (optional) css file. In the optional css file, there are several `@extend` references to the **main.css** file that need to be included.

Referencing variables is fine in the optional CSS file as they are referenced from a partial scss and not compiled, but I cannot work out how to @extend without re-including the main.css file in my optional.css file. Hope that all makes since :)

Note, the purpose for the file separation is purely for performance purposes, as when all the total SCSS is compiled, it is nearing 1MB. Google PageSpeed Insights complains about large css files, so am trying to generate several smaller CSS files.

Cheers!

**Comment by STV11C** [comment]
Alternatively, being able to split the compiled output into separate CSS files where desired during the file creation process is probably more what I'm after. Is this possible with SCSSPHP?

**Comment by stof** [comment]
You cannot extend selectors that are not part of the imported files, as the compiler would not know about them.

> Alternatively, being able to split the compiled output into separate CSS files where desired during the file creation process is probably more what I'm after. Is this possible with SCSSPHP?

This is not possible with scssphp and it is out of its scope (the official sass implementation does not support it either). However, there are other tools able to do that (not sure whether there is such a tool implemented in PHP though)

**Comment by STV11C** [comment]
Thanks for replying back and I fully understand it's not a common request. Thanks again for your great work on SCSSPHP.
