### ISSUE TITLE
Using @extend creates invalid output with nested classnames in some cases in 0.7.5

### ISSUE THREAD

**Issue by bmbrands** [scssphp/scssphp#64]
Compiling this scss:

```
.btn-block {
  + .btn-block {
    margin-top: 1.5rem;
  }
}
.a {
    .b {
        @extend .btn-block;
        margin: auto;
    }
}
```

generates this css

```
.btn-block + .btn-blocks, .a .b + .btn-blocks {
  margin-top: 1.5rem; }
```
Which is not valid because of a selector ending with +

I know this is not the way @extend is advised to be used. I just want to report it as the issue did not exist in earlier versions of scssphp.

**Comment by Cerdic** [comment]
The 0.7.5 is super old and you should defintely update :)
However this is still an issue in the current version, producing this:
```
.btn-block + .btn-block, .a .b + .btn-block, .a .b +, .a .btn-block + .b {
  margin-top: 1.5rem; }

.a .b {
  margin: auto; }
```

**Comment by Cerdic** [comment]
So this is fixed in the master
