### ISSUE TITLE
Separate styles by breakpoints

### ISSUE THREAD

**Issue by dennismetz** [scssphp/scssphp#640]
Is there a way to split the generated css into 2 or more files?
What I want to achieve:
I would like to have all styles up to a certain breakpoint (e.g. 768px) in one file and everything above in an extra file. So we could shorten the loading time of the css again because we don't need the breakpoints here.
On desktop you can then include both files or you pack again the general css together and the larger breakpoints, but leave out the small ones.

**Comment by stof** [comment]
This is not a feature supported by the Sass compiler, so it is out of scope of the scssphp project.

However, I know that some postcss plugins exist to do that (running on the CSS generated by the scss compilation) if you can afford to use a JS-based tool (I'm not sure such a tool exists in PHP)
