### ISSUE TITLE
Custom variables: list or map from php

### ISSUE THREAD

**Issue by uuf6429** [scssphp/scssphp#641]
First of all, I don't understand why `ScssPhp\ValueConverter::fromPhp` assumes scalar types are purely from PHP (correct) but array types are potentially Scss values (unexpected for me, bordering to wrong). Especially when one has to look at the code to figure that out.
https://github.com/scssphp/scssphp/blob/957888e3779f2ddce922a0c41e736c45b6686b3c/src/ValueConverter.php#L65

----

Secondly, the function signature takes in "mixed" type - nowhere does it say anything about objects or arrays not being supported.

----

Thirdly, this functionality is a very common use case (when it comes to custom variables), so it really should be implemented. 😅 

I tried the following approach but it didn't work:

```php
class MyClass {
    // ....

    private function scssFromPhp(mixed $value): mixed
    {
        if ($value === null || is_scalar($value)) {
            return ScssPhp\ValueConverter::fromPhp($value);
        }

        if (is_array($value) && array_is_list($value)) {
            return [ScssPhp\Type::T_LIST, '', array_map($this->scssFromPhp(...), $value)];
        }

        if (is_array($value) || $value instanceof stdClass) {
            $value = (array)$value;
            return [
                ScssPhp\Type::T_MAP,
                array_map($this->scssFromPhp(...), array_keys($value)),
                array_map($this->scssFromPhp(...), array_values($value))
            ];
        }

        throw new InvalidArgumentException('...'); // error message should detail exactly where the conversion failed and why
    }
}
```

~I don't have much knowledge about these types' structure to be sure about that code, would be nice if someone could figure out what's wrong.~

Seems the code does work 🤔 maybe it could be added to the implementation though..

**Comment by stof** [comment]
The hard part is that we already support passing an already converted value there (due to some legacy behavior in the library), and those are represented as an array.

**Comment by uuf6429** [comment]
Right, I ended up write a value translator class (scss <-> php, both directions).

Maybe I'll open a PR later to add it, then we can consider deprecating `ValueConverter::fromPhp`. Wdyt?

**Comment by stof** [comment]
Well, actually, support converted values in that one is something I want to keep, because it will make it simpler when releasing 2.0 that will introduce the modern representation of values. When passed with a legacy value (the current ones), it will convert it to modern ones. So we cannot deprecate it.

**Comment by uuf6429** [comment]
I see... I'll give the v2 a look then, if it's available.

**Comment by stof** [comment]
not yet
