### ISSUE TITLE
CSS custom properties and SASS variables don't work

### ISSUE THREAD

**Issue by PinguTS** [scssphp/scssphp#642]

**Comment by PinguTS** [comment]
Wenn a CSS custom property is defined from a variable, than the content of the variable is not assign to the CSS custom property. In the final generated CSS is still `$variable`.

SCSS
``
$variable: "content";

:root {
  --variable: $variable;
}
``

Generated CSS
``
:root {
  --variable: $variable;
}
``

Correct CSS
``
:root {
  --variable: "content";
}
``

**Comment by stof** [comment]
This is not a bug in scssphp. In Sass, custom properties require using interpolation to allow using Sass variables: https://sass-lang.com/documentation/style-rules/declarations#custom-properties
