### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by gtbu** [scssphp/scssphp#646]
I work at a Typesetter CMS - fork wherein css.php i have $scss_files = $compiler->getParsedFiles();  which is deprecated since 1.5.0  : _The method "getParsedFiles" of the Compiler is deprecated. Use the "getIncludedFiles" method on the CompilationResult instance returned by compileString() instead. Be careful that the signature of the method is different._

At https://scssphp.github.io/scssphp/docs/ You say :  A list of the included files can be retrieved using the getIncludedFiles method of the CompilationResult. The input file is not included in this list. 

**Can You please give a more detailled example** in the documentation of how to get the variables for code like : $result = new CompilationResult($out, $sourceMap, array_values($includedFiles));  All wordpress plugins i found just avoid "getIncludedFiles" --- this would make it easier for many developers

**Comment by stof** [comment]
You don't instantiate the CompilationResult. As said in the deprecation message that you provided in your issue, the CompilationResult instance is returned by the `compileString` method of the Compiler.

So it looks like this:

```php
$result = $compiler->compilerString($input, înputPath);

$css = $result->getCss();
$includedFiles = $result->getIncludedFiles();
$sourceMap = $result->getSourceMap();
```

**Comment by gtbu** [comment]
I got i finally running at [my fork](https://github.com/gtbu/Typesetter-5.3-p8/blob/main/include/tool/Output/Css.php#L212). 
The main advantage is for me that i can drop  array_keys   in   $scss_files = array_keys($scss_files);  
Just Bootswatch Scss 3 has now problems....it is old anyway....

**Comment by stof** [comment]
@gtbu you should not compile the string twice. that's non-sense from a performance point of view. Instead, you should store the compilation result in a variable (as shown in my previous comment) to be able to use it multiple times to call getters on it.

**Comment by gtbu** [comment]
You mean  :   $result = $compiler->compileString(implode("\n", $combined));  ?  -- and after 
 $result->getCss();	$result->getIncludedFiles();  and  $result->getSourceMap();

**Comment by stof** [comment]
Of course it is. What takes time is compiling. Doing it once instead of 3 times will indeed cut time.
