### ISSUE TITLE
no following symlink

### ISSUE THREAD

**Issue by MarcoHaase** [scssphp/scssphp#650]
Hey,

I am wondering, if you like this code in Compiler.php::tryImportPath for --no-follow option to import symlinked folders like "/var/www/public/extension_a/assets/scss/../../../extension_b/assets/scss" 

in public folder:
.
..
extension_a -> ../private/packages/extension_a/
extension_b

if you try to import from symlinked folder, it always endup in file not found error message, because it will switch to private nonsymlinked folder. 

```php
      $parts = explode('/', $path);
        $resolvedPath = [];
        foreach ($parts as $part) {
            if ($part === '..') {
                array_pop($resolvedPath);
            } else {
                $resolvedPath[] = $part;
            }
        }
        $path = implode('/', $resolvedPath);

        $parts = explode('/', $partial);
        $resolvedPath = [];
        foreach ($parts as $part) {
            if ($part === '..') {
                array_pop($resolvedPath);
            } else {
                $resolvedPath[] = $part;
            }
        }
        $partial = implode('/', $resolvedPath);
```

**Comment by stof** [comment]
2.0 is now released, and it does not use `realpath` on path, so this should be working.
