### ISSUE TITLE
Feature Request: Support for OKLab and OKLCH Color Spaces

### ISSUE THREAD

**Issue by milengg** [scssphp/scssphp#662]
**Issue description:**

Hello scssphp/scssphp maintainers and contributors,

First of all, I'd like to express my gratitude for your efforts in creating and maintaining this wonderful library. It has been instrumental for many of my projects.

**Feature Request:**
I'd like to suggest adding support for newer color spaces, specifically OKLab and OKLCH. As these color spaces are becoming increasingly popular due to their perceptual uniformity and ability to represent colors in a more intuitive manner for humans, it would be immensely beneficial for developers using scssphp/scssphp to have the option to use these spaces in their styles.

**Benefits:**

* Perceptual Uniformity: OKLab and OKLCH offer better perceptual uniformity compared to many traditional color spaces. This can lead to more consistent and visually pleasing color manipulations and gradients.
* Keeping Up with Modern Practices: Major design tools and browsers are gradually adopting these color spaces. By supporting them, scssphp/scssphp ensures that it remains cutting-edge and relevant for modern web development.
* Enhanced Color Control: These spaces can provide developers with enhanced control, especially when dealing with nuanced color manipulations.

**Possible Challenges:**
I understand that incorporating new color spaces might introduce challenges, both in terms of implementation and backward compatibility. However, given the increasing prominence of OKLab and OKLCH, I believe the benefits will outweigh potential difficulties.

**Conclusion:**
Thank you for considering this feature request. I genuinely believe that by supporting OKLab and OKLCH, scssphp/scssphp can offer even more to its users, enabling them to create visually stunning and modern web designs. If there's any way I can assist or if you'd like more information on these color spaces, please don't hesitate to reach out.

Best Regards,
Milen Georgiev

**Comment by stof** [comment]
We won't be inventing a feature on our own for those as we intent to implement the Sass language. See https://github.com/sass/sass/issues?q=is%3Aissue+label%3A%22proposal%3A+color+spaces%22+is%3Aopen for the in-progress work on adding support for color spaces in the Sass language specification.

Thus, our handling of color values in the 1.x branch is quite messy (and not entirely spec compliant AFAICT). And the new APIs dealing with color spaces rely on modules, which are not supported in the 1.x branch either. So I doubt we will be able to implement color spaces in 1.x.
However, the plan is that our 2.x version will support those once it is done (I'm working on it on my free time, so I have no idea when it will be ready) and once the official Sass version supports color spaces (i.e. we won't try to implement it in scssphp before the reference implementation, as implementation in the reference compiler often allows discovering some needed spec changes)

**Comment by stof** [comment]
As support for color spaces has been merged in dart-sass (the Sass website is not updated yet. They will probably merge the PR only when tagging the dart-sass release), I opened https://github.com/scssphp/scssphp/issues/763 to track the state of implementing it in scssphp 2.x.

I'm closing this issue in favor of https://github.com/scssphp/scssphp/issues/763
