### ISSUE TITLE
[RFC][2.0] Revised plan for the min PHP version

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#669]
As the work on implementing 2.0 has stalled for a while, I'd like to reconsider the decision taken 2 years ago in #314 to use PHP 7.2 as the min requirement.

Note that this discussion is about the **minimum** supported version of PHP. The range of supported version will go from that minimum version up to the current PHP version. So downstream projects that already requires a higher minimum version than us are totally fine. The issue is if they want to keep support for a version *lower* than our minimum.
Also note that this change will apply only to 2.0. Our maintenance branch for 1.x will still support PHP 5.6+, but it won't receive anything else than critical bug fixes once 2.0 is out. That's still a solution for maintenance branches of downstream projects though if needed.

## Interesting features

The minimum supported PHP version will affect our ability to use these features in our own code:

- **partial variance** (when the upper type is the implicit `mixed` type): PHP 7.2
- **arrow function**: PHP 7.4 (dart-sass has lots of callbacks in its code. The lack of arrow function makes it much more tedious when porting code. For my initial work on the parser, I replaced many usages of callbacks with alternative code, but I changed my mind for following porting work as it made the maintenance harder when having to update the code)
- full support for variance rules: PHP 7.4 (nice to use native types in places that require variance, but phpstan can still analyze phpdoc types with full variance)
- typed properties: PHP 7.4 (nice-to-have, as our properties will stay private anyway to enforce immutability and we have phpstan)
- Null coalescing assignment operator: PHP 7.4 (nice to have, but a few places would benefit from it)
- union types: PHP 8.0
- **match expressions**: PHP 8.0 (would help porting code from dart-sass as dart has a switch expression rather than a swich statement)
- Nullsafe operator: PHP 8.0
- Constructor promotion: PHP 8.0 (nice to have as this is syntactic sugar
- **enums**: PHP 8.1 (dart-sass has *lots* of enums. Having support for enums in PHP would simplify a lot the porting of the code)

PHPUnit 9 requires PHP 7.3+. Dropping PHP 7.2 would simplify our test setup by allowing to use PHPunit 9.6 for all our versions.
PHPUnit 8 (the oldest version having life support) requires PHP 7.2+, so going back lower than PHP 7.2 is not an option in this discussion as having a testsuite is not negotiable.

## Downstream requirements

Top dependencies based on https://packagist.org/packages/scssphp/scssphp/dependents?order_by=downloads&requires=require

- Typo3 CMS: 8.1
- Shopware: 8.1
- October CMS: 8.0.2
- Contao: 8.1
- [Typo3 Bootstrap package](https://packagist.org/packages/bk2k/bootstrap-package): 7.4 (though this requires using an older version of Typo 3 itself)
- Winter CMS: 8.0.2
- Concrete CMS: 7.3
- [Sass compiler for Typo3](https://packagist.org/packages/wapplersystems/ws-scss): 8.0
- mediawiki/scss: 7.4.3

From the list from 2 years ago, EZPlatform is gone as their version 3 removed the dependency on scssphp

Extra known downstream projects:
- [SPIP](https://git.spip.net/spip-contrib-extensions/scssphp): 7.4
- Gantry 5: 7.1.3
- Grav: 7.3.6 (supported at least through Gantry, maybe by other themes too)
- Joomla 3: 5.3. Recommends 8.0+ (supported at least through Gantry, maybe by other themes too)
- Joomla 4: 7.2.5. Recommends 8.2+
- Wordpress: 5.6. Recommends 7.4+

**Comment by stof** [comment]
As the main implementer of this version 2 (currently the only implementer), my dream would be targeting PHP 8.1 (enums :heart:). But I would be satisfied with at least 7.4, with 8.0 being nice.

Based on the list of downstream projects, I would say PHP 7.4 is a safe bet for now.

**Comment by stof** [comment]
Another argument: the PHP requirement of `league/uri` which is a dependency in 2.0 to represent URIs:

- `league/uri` 6.8.0 and 7.x require PHP 8.1+
- `league/uri` 6.7.x requires PHP 7.4+
- Support for PHP 7.3 requires going back to 6.5.0
- Support for PHP 7.2 requires going back to 6.4.0

**Comment by Cerdic** [comment]
As you said @stof, things are moving, and from SPIP side the last stable version is indeed PHP 7.4 mini.
But I would not bother to target PHP 8.1 as a minimal PHP version for ScssPHP, because it's now acceptable to put this constraint for people wanting to use it with SPIP, and the next major SPIP version will target PHP 8.1 mini

https://git.spip.net/spip/spip/src/branch/master/composer.json

Also reading the interest of having `enum` for easing the dart-saas port, I think it would be a good move to make things easier and choosing PHP 8.1 as a minimal requirement.

The main risk would be that the port become too easy and a v2.0 would be available too fast :p 

More seriously, I think it would be however better to be able to reach a full port, even if the minimal PHP version is a bit high at first, than making choices that are going to make the developpement way longer or having less chance to succeed (because who cares it can run with PHP 7.4, if it's not usefull?)

But you decide, you're the one involved in that port

**Comment by Cerdic** [comment]
I also wish I could help: my dart skills are near zero, so I don't feel helpful on the dart port, but If you thing of something I could do to support your effort feel free to ask!

**Comment by stof** [comment]
> and the next major SPIP version will target PHP 8.1 mini

Great. I checked the website but I missed the section about 5.0.

> I also wish I could help: my dart skills are near zero, so I don't feel helpful on the dart port, but If you thing of something I could do to support your effort feel free to ask!

to be honest, for now, I have several in-progress things locally so sharing the porting work itself would require extra coordination. Especially if you don't know dart at all, this might not help much.
However, one thing that could help could be working on https://github.com/scssphp/scssphp/issues/670. I'm not yet at the point where I'm running our functional tests with the new codebase (that requires the port to be more complete than it is right now) but progress on that work would help me when I reach that point.

**Comment by stof** [comment]
I decided that the argument of @Cerdic in https://github.com/scssphp/scssphp/issues/669#issuecomment-1738664124 is very good.
After all, I'm doing all that work on my free time. And as my own projects are running on PHP 8.2 now, I don't have any personal need for making the port harder. Someone being mad at me for that decision is free to write their own spec-compliant implementation of Sass in pure PHP if they want...
