### ISSUE TITLE
 Not working for Laravel > 6 version

### ISSUE THREAD

**Issue by mayanksdudakiya** [scssphp/scssphp#67]
I have installed and tested this. I am not able to generate compile css for Laravel 6+ version. I would like to dynamic the variable by using registerFunction() of scssphp into the controller. Would you please tell me is it support for Laravel 6+ version to dynamic the saas variables from controller/model.
Thanks :)

**Comment by robocoder** [comment]
Please refer to:

https://scssphp.github.io/scssphp/docs/

It sounds like you should be using setVariable() instead of a custom function.
