### ISSUE TITLE
Import of invalid scss files fails silently

### ISSUE THREAD

**Issue by oyejorge** [scssphp/scssphp#68]
If an scss import fails, it seems like the compiler should throw an error. [Looking at the code](https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L2242), the compiler appears to add the `@import file.scss` back to the result. I can see how this would be helpful if it's a css file (eg `@import file.css`), but not for scss.

**Comment by Linrasis** [comment]
Same issue.. you have found problem ?

**Comment by Cerdic** [comment]
This is now fixed
