### ISSUE TITLE
Cache reads a wrong entry

### ISSUE THREAD

**Issue by SeriousOne** [scssphp/scssphp#699]
Here's a part of my code:
```php
$compiler = new ScssPhpCompiler([
    'cacheDir'               => 'path/to/cache/dir',
    'checkImportResolutions' => true,
]);
$compiler->setOutputStyle(OutputStyle::COMPRESSED);
$compiler->addVariables($vars);
$compiler->compileString($scss);
```

All `$vars` are processed by the `parseValue` SCSS compiler method.

One of those `$vars` contains a length (`2rem`, `10px`, `0`), which can have different values. The first time it is cached and saved correctly into cache, but when I change it and pass the same variable with a new value, it reads the previous cache entry (the variable contains the same name, but a different value).

Any thoughts on how to fix that behavior except disabling caching or using `'forceRefresh' => 'once'` for the cache configuration.

I can provide more details.

**Comment by SeriousOne** [comment]
Thank you for the explanation. Is it planned for the next release? If not, I'll just disable caching for now (it is not critical) and wait for you fix.

**Comment by stof** [comment]
The fix is available in the 1.12.1 release.

**Comment by SeriousOne** [comment]
Thank you, I'll test it.

**Comment by SeriousOne** [comment]
Seems like it works like expected now, thanks again for the quick fix.
