### ISSUE TITLE
unexpected '|', expecting ';' or '{' in /.../scssphp/src/Util.php on line 243

### ISSUE THREAD

**Issue by ogiusek** [scssphp/scssphp#705]
Parse error: syntax error, unexpected '|', expecting ';' or '{' in /.../scssphp/src/Util.php on line 243

```php
$scss_compiler = new ScssPhp\ScssPhp\Compiler();
function compileScss($scss) {
  global $scss_compiler;
  $css = $scss_compiler->compileString("body{background-color: red;}")->getCss(); # <-- this line throws error
 }
 ```
 am i dumb or is something wrong with this ?
 this works locally but not on hosting.
 other php works perfectly fine

**Comment by mlocati** [comment]
Which PHP version are you using? And which version of scssphp are you using?
