### ISSUE TITLE
Load files from array?

### ISSUE THREAD

**Issue by supun-io** [scssphp/scssphp#707]
Currently, the library reads from the file system. The idea here is to load `@import` files from a predefined set of strings.

```php
$compiler = new ScssPhp\ScssPhp\Compiler();
$compiler->registerFiles([
     'index.scss' => '...',
     'page.scss' => '...',
]);

$compiled = $compiler->compileFile('index.scss');
```

This is useful in cases where the SCSS files are loaded from an external source like a database.

We already have this implemented in a fork (https://github.com/hyvor/scssphp), which we use in production. If this sounds like something worth adding to the library, I'd be happy to send a PR.

**Comment by stof** [comment]
I don't want to add this in the 1.x branch (I don't want to add more new features there, especially introducing new APIs that I would have to deprecate later).

For 2.x (currently in progress and not available yet), the importer API should allow implementing such use case by using a custom importer.

**Comment by supun-io** [comment]
Thanks! That makes sense. I'll be waiting for 2.x. Do you have a rough timeline? (no rush :))

**Comment by stof** [comment]
I don't have any as I'm working on that on my free time (and these days, most of my free time is not dedicated to open-source)

**Comment by stof** [comment]
2.0 is now released with its Importer API.
