### ISSUE TITLE
value of type null for Compiler.php

### ISSUE THREAD

**Issue by Skip75** [scssphp/scssphp#73]
Hello

Getting following error :
`Error	PHP	Trying to access array offset on value of type null at /var/www/nextcloud/3rdparty/leafo/scssphp/src/Compiler.php#5230`

On a fresh install of nextcloud 18. Any idea ?

> [root@SRV]# php -v
> PHP 7.4.1 (cli) (built: Dec 17 2019 16:35:58) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies

**Comment by Cerdic** [comment]
leafo/scssphp makes me think you’re having a super old version...

**Comment by robocoder** [comment]
This version of scssphp is unsupported.
