### ISSUE TITLE
Absolute URLs get truncated when used in setVariable

### ISSUE THREAD

**Issue by jeremyvii** [scssphp/scssphp#74]
Using absolute URLs within `setVariables()` truncates the value to just the URL scheme.

For example, the following snippet:
``` php
$scss = new Compiler();
$scss->setVariables([
  'font-url' => 'https://fonts.googleapis.com/css?family=Open+Sans&display=swap'
]);
$scss->compile('@import url("#{$font-url}");')
```
Will render just the URL scheme.

``` css
@import url("https");
```

I would like to note that I tried changing the URL scheme to various values, which yielded the same result.

For example:
``` php
$scss->setVariables([
  'font-url' => 'p://fonts.googleapis.com/css?family=Open+Sans&display=swap'
]);
```
Will render what ever character(s) that proceed the colon.
``` css
@import url("p");
```

**Comment by robocoder** [comment]
See docs.

Note: the value is the scss source to be parsed. If you want to parse a string, you have to represent it as a string, e.g,, 'var' => '"string"'.
