### ISSUE TITLE
[RFC] Considering dropping support for PHP 8.1

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#746]
As I'm approaching the end of the work on the dart-sass port, I'm facing an issue in #728: the CI job triggers a PHP segfault when running on PHP 8.1.

I will **not** release version 2 claiming support for PHP 8.1 if I cannot have a CI setup ensuring this is actually the case (no need to try to convince me to change my mind on this, I won't). That segfault seems specific to GitHub Actions apparently (I installed back PHP 8.1 on my machine and was able to run the testsuite, but that's not a viable solution for a CI setup).

I don't have a personal need for the support of PHP 8.1 as all my own projects are already running on PHP 8.2 or 8.3. Because of that, I don't have a personal interest on debugging that segfault before being able to merge #728. I would rather spend time on implement Sass modules after merging the new compiler.

So I'm proposing 2 outcomes:

1. Bumping the min version to PHP 8.2 for the 2.0 version
2. Someone contributing by helping with the CI job on PHP 8.1 so that the CI job in #728 passes

Note that to unblock me, I will likely drop the PHP 8.1 CI job for now (so that I can merge #728 and move forward) while providing a separate draft PR re-enabling to allow for that debugging to happen if someone is interested. However, for at least a few weeks, I will keep writing code based on the PHP 8.1 feature set to make that effort possible.

## Downstream requirements

This analysis is meant to provide additional context to help the decision. However, it does not represent a goal of keeping support for all their minimum versions (we won't go below 8.1 anyway as that decision was already taken).

Top dependents based on https://packagist.org/packages/scssphp/scssphp/dependents?order_by=downloads&requires=require

- Shopware: 8.2
- October CMS: 8.0.2
- Contao: 8.1
- [Typo3 Bootstrap package](https://packagist.org/packages/bk2k/bootstrap-package): 7.4 (but Typo3 now requires PHP 8.2)
- Winter CMS: 8.0.2
- Concrete CMS: 7.3
- [Sass compiler for Typo3](https://packagist.org/packages/wapplersystems/ws-scss): 8.0 (but requires Typo3 12+, which requires PHP 8.1)
- mediawiki/scss: 8.0

Extra known downstream projects:
- [SPIP](https://git.spip.net/spip-contrib-extensions/scssphp): 7.4. The next major version of SPIP requires PHP 8.2
- Gantry 5: 7.1.3
- Grav: 7.3.6 (supported at least through Gantry, maybe by other themes too)
- Joomla 3: 5.3. Recommends 8.0+ (supported at least through Gantry, maybe by other themes too)
- Joomla 4: 7.2.5. Recommends 8.2+
- Joomla 5: 8.1. Recommends 8.3+
- Wordpress: 7.2. Recommends 7.4+

**Comment by Cerdic** [comment]
congrats and thanks for all the work you already did @stof ! I would like to have time to try to solve this, but I know this is not going to happen in a forseable future, so I can only agree with your proposal to move forward on PHP 8.2+
