### ISSUE TITLE
Attempted to load class "Compiler" from namespace "Leafo\ScssPhp". 

### ISSUE THREAD

**Issue by abelardolg** [scssphp/scssphp#77]
Hi there,

I am using the package:
`"scssphp/scssphp": "^1.0.6"`

When I delete vendor, var/cache and clear cache of composer, I run:
`composer install`
then this message outputs:

```
Attempted to load class "Compiler" from namespace "Leafo\ScssPhp".           
  Did you forget a "use" statement for e.g. "Twig_Compiler", "Twig\Compiler",  
   "Symfony\Component\ExpressionLanguage\Compiler", "Symfony\Component\Depend  
  encyInjection\Compiler\Compiler" or "ScssPhp\ScssPhp\Compiler"?  
```
```
Operating System: Ubuntu 18.04.3 LTS
            Kernel: Linux 5.3.0-26-generic
```
```
PHP 7.2.24-0ubuntu0.18.04.2 (cli) (built: Jan 13 2020 18:39:59) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.24-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
```
What's wrong?
Best regards.

**Comment by robocoder** [comment]
That error isn't coming from this package. It looks like you still have a dependency on `leafo/scssphp` somewhere. Try searching in your `vendors/` folder, e.g.,

`fgrep -R "use Leafo" vendors/`

**Comment by abelardolg** [comment]
Yes, this file was this reference. 

vendor/kriswallsmith/assetic/src/Assetic/Filter/ScssphpFilter.php:use Leafo\ScssPhp\Compiler;
