### ISSUE TITLE
Release with PHP 8.4 updates?

### ISSUE THREAD

**Issue by rbro** [scssphp/scssphp#773]
Would it be possible to do a release with the updates made for the deprecations in PHP 8.4?  I see they were made in August, but haven't yet been released, such as [66f0b67045e4147ed9182de5de8a9e19318ae136](https://github.com/scssphp/scssphp/commit/66f0b67045e4147ed9182de5de8a9e19318ae136).

Thanks for your help and maintaining this library.

**Comment by stof** [comment]
Those commits done in August have fixed one deprecation for PHP 8.4. However, the PR adding a CI job for it (#769) made me discover that we are impacted by another deprecation.

I have a fix for it locally, but I need to make it pass static analysis, for which I need to be able to have the `fpow` polyfill for phpstan to know about the function. I created this polyfill at https://github.com/symfony/polyfill/pull/509 so I should be able to finish the work soon.

Note that the release that will support PHP 8.4 will be the 2.0 release. The 1.x branch works with PHP 8.4 but triggers deprecations, and we cannot fix them while keeping the supported version range of 1.x. Fortunately, the 2.0 version is ready to be released (once my patch for the PHP 8.4 deprecation will be merged)

**Comment by rbro** [comment]
That'd be great.  Thanks for keeping the library up to date.  I'm happy to help test once you have it ready.

**Comment by stof** [comment]
2.0.0 has been released
