### ISSUE TITLE
Unable to pass .ext into SCSS variables array

### ISSUE THREAD

**Issue by jljr222** [scssphp/scssphp#78]
Hi Guys,

I am running against an odd use case where I am passing an image name "login-background.jpg" by variable ($sm-login-bg). The variable is being printed out, but the extension is being clipped.

I am passing the scss variables via an array. For testing purposes here is the array spit out after compile completed to ensure it's not being clipped prior to my compile request:

`Array ( [sm-google-font] => //fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i [sm-primary-font] => "Open Sans", sans serif [sm-primary] => #2ca1c3 [sm-secondary] => #94bd31 [sm-blue] => #2ca1c3 [sm-red] => #d9534f [sm-orange] => #f0ad4e [sm-green] => #94bd31 [sm-lightgray] => #eeeeee [sm-medgray] => #888888 [sm-gray] => #3f3f3f [sm-darkgray] => #222222 [sm-login-bg] => login-background.png [sm-nav-type] => side [sm-header-style] => dark [sm-nav-style] => dark [sm-login-style] => classic )`

The array looks good and the data is there with the correct extension. An example of how it looks in my SCSS file:

```
body {
		background: url("#{$sm-img-path}#{$sm-login-bg}") no-repeat top center;
		background-size: cover;
		min-height: 100vh;
	}
```

The path is being set in another scss file import, it's not being dynamically inserted. Its value is "../images/". Unfortunately, here is what is being spat out:

```
body{background:url("../images/login-background") no-repeat top center;background-size:cover;min-height:100vh}
```

Kind of at a loss to figuring out why it's compiling this way. I wanted to bring this up to ensure it's not a bug. I've tried .jpg, .png, and for kicks, I've used spaces and .whatever. Any extension gets removed. I even tried "login-background.backup.jpg" and it removed everything from the first "." on.

Any ideas? Oh, I am using 1.0.7 and your latest server release.

**Comment by robocoder** [comment]
```
$scss->setVariables(array(
    'sm-login-bg' => '"login-background.png"',
));
```

**Comment by jljr222** [comment]
Thank you!
