### ISSUE TITLE
Always have (stdin) in source map

### ISSUE THREAD

**Issue by AdamPerkins** [scssphp/scssphp#8]
This is a follow up to this issue: https://github.com/leafo/scssphp/issues/677

And to answer the question of @robocoder: 

This is an example of my code:
```
use ScssPhp\ScssPhp\Compiler;
$scss = new Compiler();
$scss->addImportPath('/mnt/www/myproject/www/themes/default/css/');
$scss->setFormatter('ScssPhp\ScssPhp\Formatter\Expanded');
$scss->setSourceMap(Compiler::SOURCE_MAP_FILE);

$scss->setSourceMapOptions([
	'sourceMapWriteTo'  => '/mnt/www/myproject/www/themes/default/css/cms.css.map',
	'sourceMapURL'      => 'cms.css.map',
	'sourceMapFilename' => 'cms.css',
	'sourceMapBasepath' => '/mnt/www/myproject/www/themes/default/css/',
]);

$scss->compile('@import "cms";');
```

It outputs something like this:
```
{"version":3,"file":"cms.css","sources":["(stdin)","_cms_test.scss"],"names":[],"mappings":"AAAA,AAAA;;;GCAA,GAAA,UAAA,AAAA"}
```

**Comment by stof** [comment]
This is expected, as you don't pass the path of your source file (the one from which you pass the content to `$scss->compile`) as the second argument of `$scss->compile`, and so it assumes that this content is from STDIN (it could use `unknown` instead, but that would force to provide a separate way to support STDIN)

**Comment by robocoder** [comment]
As stof explained, you would use:
```
$scss->compile('@import "CMS";', $sourcePathName);
```
