### ISSUE TITLE
@import "module" not working correctly

### ISSUE THREAD

**Issue by paqstd** [scssphp/scssphp#83]
Recently I encountered such a problem: I have two main files from different modules vendor/bootstrap /_bootstrap.scss, vendor/font-awesome/_font-awesome.scss. Each module has _variables.scss files and, accordingly, @import "variables".

If i process these two files separately, everything works. But when two files are connected in a row during compilation, it turns out that the first variables.scss is connected, and the second is ignored.

**Comment by robocoder** [comment]
Does dart-sass handle this the way you expect?

**Comment by Cerdic** [comment]
Not reproducing:

```
$ cat test.scss
@import "module1/module";
@import "module2/module";

$ cat module1/module.scss
@import "variables";

.module1 {
  color: $color1;
}

$ cat module1/_variables.scss
/*
Variables module1
 */
$color1: red;

$ cat module2/module.scss
@import "variables";

.module2 {
  color: $color1;
}

$ cat module2/_variables.scss
/*
Variables module2
 */
$color1: green;

$ ../bin/pscss test.scss
/*
 Variables module1
 */
.module1 {
  color: red; }

/*
 Variables module2
 */
.module2 {
  color: green; }
```

So it depends what you call "when two files are connected in a row during compilation".

One possibility to maybe have this bug, according to code, is 
* to instanciate the Compiler once only, 
* chdir in `module1`, compile `module.scss`
* chdir in `module2`, compile `module.scss`

Then there might be some mistake with the `_variables.scss` that match an already known path.
Not according to the code:
* here https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L4597 there is a `realpathcache()` call, 
* and after that in the parse function there is a `md5` on the content to avoid any confusion https://github.com/scssphp/scssphp/blob/master/src/Parser.php#L165

So I guess this would need to use some agressive file caching somewhere in the php configuration?

If you can give us a minimal test case to reproduce it we could try to fix this borderline use case, but I would say this is not really a bug from scssphp here (except if I am missing something)

**Comment by robocoder** [comment]
ping @paqstd paqstd
