### ISSUE TITLE
Bootstrap 4.4.1 empty breadcrumb font-size 

### ISSUE THREAD

**Issue by fuzegit** [scssphp/scssphp#85]
After compilation
`./pscss /path-to/scss/bootstrap.scss > bs.css`

![Выделение_009](https://user-images.githubusercontent.com/13233234/75245482-db310300-57de-11ea-82a2-707d9a9b6bed.png)

**Comment by Cerdic** [comment]
This was not super critical as the empty property is just ignored but this is now fixed

**Comment by fuzegit** [comment]
thanks!
