### ISSUE TITLE
Compiling a scss file containing cyrillic characters in php starting v7.2.0 + throws an exception.

### ISSUE THREAD

**Issue by KryukovDS** [scssphp/scssphp#87]
Hello.

On the project developer, they upgraded the php version to 7.3 and now scssphp has thrown an exception if there are some Cyrillic characters in the compiled scss files.

The project is on Bitrix and we are forced to set the value of "mbstring.func_overload" to "2". So far, this CMS has not reacted to the fact that this setting is designated as "deprecated" since php 7.2. I perfectly understand that this is terrible, but I can’t do anything - such a project.

Earlier, in the scssphp parser code to solve this problem, a check was installed in the method `\ScssPhp\ScssPhp\Parser::saveEncoding();`, but now because of the condition `if (version_compare (PHP_VERSION, '7.2.0')> = 0) { return; }` it does not work out and further checks `if ($this->count !== strlen ($this->buffer)) { $this->throwParseError(); }` throws an exception.

It is not entirely clear why you made the decision to refuse support for projects with "mbstring.func_overload" equal to "2" starting already with php 7.2. The tribute to the setup has only been marked as "deprecated" so far, but it has not been deleted at all and there are projects that will live until the last moment with its current value of "2" until it is completely removed in some of the new php versions.

Please remove this version check in the "saveEncoding" method until the "mbstring.func_overload" is completely removed from the php settings.

Thanks for your work and sorry for Google Translate.

* php v7.3.9
* scssphp v1.0.8
* CMS 1C Bitrix
* mbstring.internal_encoding = "utf-8"
* mbstring.func_overload = "2"

**Comment by Cerdic** [comment]
This was deactivated for PHP 7.2+ with the commit f79f49b9aebf7c1885a27f1152f2d58d1ba4b05a
I'm not sure why indeed. 

Maybe with b3ec9ba2d66384d64bd906fe102aff8e1afaae54 we can now keep this feature active unti the setting is really removed from PHP?

I will let @robocoder have a check an see if he can remember

**Comment by robocoder** [comment]
Thanks for the feedback. I'll review the proposed change.

As a library, scssphp should not introduce side effects to the consuming application. That's the purpose of the check.

CodeSniffer looks for the text `mbstring.func_overload` ...that's why the test looks weird (ie to avoid detection by the code sniff).
