### ISSUE TITLE
Support glob-based imports for scss files in a directory

### ISSUE THREAD

**Issue by havutcuoglu** [scssphp/scssphp#88]
Hi there

My concern is, if you have several CSS files within one directory, it is laborious to list them all individually in order to import them. Sometimes you forget to import a file. It would be very helpful to apply a glob-based import. Then you would only have to write one line and all files would be imported. e.g. as stated here [https://github.com/chriseppstein/sass-globbing](url)

Is it possible to integrate this function or is it already included in this package?

e.g. I'm currently doing it like this:
```
@import "modules/colorbox";
@import "modules/accordions";
@import "modules/navigation";
@import "modules/ ...";
...
```

It would be better with:
`@import "modules/*";`
or from sub directory
`@import "modules/**/*";`

**It would be great if this possibility existed.**

Thanks a lot.

**Comment by Cerdic** [comment]
The goal of this lib is to implement the sass-lang spec, and this is not a feature of the sass-lang spec (cf https://sass-lang.com/documentation/at-rules/import)

But you can use the custom importer feature that let you provide a function as an import path and then implement the glob based import in that function.

At the moment it is not in the plan to append extra features and plugin to this package, there is still a lot to do to fully fit the sass-lang spec :)

**Comment by havutcuoglu** [comment]
I get it.

**scssphp** is available in the CMS used and here it is not intended to implement your own logic for import. I also do not want to manipulate the core files of the CMS, as it would then no longer be safe to update. Then I just have to do it differently.

Thanks anyway.

I would be happy if this possibility would be available in the future.

**Comment by mahagr** [comment]
I have a single file with all the imports I need. It works great as you only need to add the files once.

**Comment by havutcuoglu** [comment]
@mahagr thanks for your idea, but i have a element generator, who create also the js and css files for this specific element. The extension but css files in a css directory. I don't want write every single file in the import.scss file. @import ".../css/*"; will include all files from directory an i don't need to touch any file.

**Comment by Cerdic** [comment]
Then maybe the feature you need is the `@import 'dir';` which in fact will automaticaly import `dir/index.scss` if existing, and I guess your generator can generate an index.scss file that import all the other files ?

This `@import` feature is not yet supported, but this is definitely at the top of the list of the fix todo.
So if it can help I can have a quick look

**Comment by havutcuoglu** [comment]
> Then maybe the feature you need is the @import 'dir'; which in fact will automaticaly import dir/index.scss if existing, and I guess your generator can generate an index.scss file that import all the other files ?

Yes, it was my next step to generate a single file with @import lines to include the other files.
My problem here is the file must generated or updated every time again, if I generate a new element.  This is not what I want. What I realy need is the **glob based** import to import all files from a directory automatically with @import '.../css/*

**Comment by robocoder** [comment]
In addition to not being part of the spec, another problem with globbing is that there's no specified order. It could be implied to be alphabetical but that means your file names become unnatural. You also can't specify whether the globbing is recursive or not.

**Comment by havutcuoglu** [comment]
@robocoder the implementation of the files are not important. The order doesn't matter how they are loaded. It is important that all css files are loaded from the folder without having to address them again.

Attached is the structure as a png file
![file-structur](https://user-images.githubusercontent.com/11348417/75783527-ffea2500-5d60-11ea-8f56-f8220e382dd8.png)

**Comment by robocoder** [comment]
This may not be your use case, but when there are dependencies, order matters.

Looking at the code, it might be easier to use a custom function, e.g., a  `glob()` function which returns a list, that can can be passed to `@import.`.

**Comment by havutcuoglu** [comment]
[https://github.com/scssphp/scssphp/issues/88#issuecomment-593355697](url)

As already mentioned, scssphp is supplied with the CMS Contao and there is no hook with which you can implement your own logic. I do not want to manipulate the core files of the CMS, otherwise it would not be update safe.

**Comment by mahagr** [comment]
I am actually overriding @import with my own logic...

https://github.com/gantry/gantry5/blob/develop/src/classes/Gantry/Component/Stylesheet/Scss/Compiler.php#L402-L428

Maybe there's a way to make it to import all the files at once?

**Comment by havutcuoglu** [comment]
@mahagr thank you ver much, but as I said, the scssphp is supplied with the CMS Contao and there is no hook with which you can implement your own logic. I do not want to manipulate the core files of the CMS.
If there is a hook for a own logic in CMS, than i will implement the `glob()` function ;)

**Comment by stof** [comment]
Rather than adding a `scssphp-glob` function in Scssphp itself, which adds a non-standard (and untested) feature for all users of the library, a better solution would have been to rely on the existing support for custom function, by requesting Contao to let you register custom functions in the compiler they use.
