### ISSUE TITLE
Variables are ignored

### ISSUE THREAD

**Issue by deadlyw1re** [scssphp/scssphp#90]
```
use ScssPhp\ScssPhp\Compiler;
-
$scss = new Compiler();
$scss->setVariables(array(
    'var' => 'false',
));

echo $scss->compile('$var: true !default;');
```

Output: ""

**Comment by deadlyw1re** [comment]
Also when you use root property declarations like `--primary` the variable after it gets ignored.

Input:
```
use ScssPhp\ScssPhp\Compiler;
-
$scss = new Compiler();
$scss->setVariables(array(
    'primary' => '#000000',
));

echo $scss->compile(':root { --primary: $primary }');
```

Output:
```
:root { --primary: $primary }
```

When changing `--primary` to something like `color:` it works, output will be:
```
:root { color: #000000 }
```

**Comment by robocoder** [comment]
Tested your examples on sassmeister. Looks good to me.

For example, there's no output expected when simply compiling a variable.
