### ISSUE TITLE
Compile error with bootstrap 4.4.1

### ISSUE THREAD

**Issue by flip111** [scssphp/scssphp#95]
https://github.com/twbs/bootstrap/blob/v4.4.1/scss/mixins/_badge.scss#L5

```
"parse error: failed at `&} {` /var/www/website/scss/bootstrap/mixins/_badge.scss on line 5"
```

**Comment by robocoder** [comment]
What version of `scssphp` are you using?

**Comment by flip111** [comment]
https://github.com/ConnectThink/WP-SCSS/tree/master/scssphp

sorry this is probably a bit old. Can close this issue if it's fixed in latest release
