### ISSUE TITLE
Null checks are a performance bottleneck of this library

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#96]
<details>
<summary>Some context about how I went there and what the profiles are about</summary>

At Incenteev, I have a use-case where I need to render some scss code at runtime (based on some values configurable by admin users). I first implemented this with scssphp (well, actually, the first one used lessphp as we migrated from less to scss). Due to the slowness of scssphp, I once decided to implemented an alternative way, which would use symfony/process to call a node.js script which would compile things and return the output. That was worth it, as even with the overhead of launching a separate process, things got significantly faster. For some reasons, I had to keep the PHP-based implementation available even though the prod was using the node-based renderer. And while refactoring the node code to use `sass` rather than `node-sass` (loosing some performance there, but in favor of other benefits), I decided to compare the performance of the PHP-based renderer again.
The blackflire profiles I'm sharing are about using this endpoint, running on my local machine, with Symfony in the prod environment and an optimized composer autoloader.

<small>Note that my controller actually involves some caching to return the cached CSS in a few ms when the config has not change. I disabled this caching layer while profiling</small>
</details>

While profiling the code rendering scss with Scssphp 1.0.8, here is what appeared in blackfire:

![image](https://user-images.githubusercontent.com/439401/79604544-93e43600-80ee-11ea-9788-38c614fb0ffc.png)

Having `is_null` as the second most expansive function looked surprising to me. Among these 3.6 millions calls, more than 2.8 million calls correspond to a single place in the source code (inside a loop obviously): the check in `Compiler::callStackMessage`:

![image](https://user-images.githubusercontent.com/439401/79604731-eb82a180-80ee-11ea-87ca-211394835ebf.png)

I tried a simple 1-char patch in this method:

```diff
     protected function callStackMessage($all = false, $limit = null)
     {
         $callStackMsg = [];
         $ncall = 0;

         if ($this->callStack) {
             foreach (array_reverse($this->callStack) as $call) {
                 if ($all || (isset($call['n']) && $call['n'])) {
                     $msg = "#" . $ncall++ . " " . $call['n'] . " ";
                     $msg .= (isset($this->sourceNames[$call[Parser::SOURCE_INDEX]])
                           ? $this->sourceNames[$call[Parser::SOURCE_INDEX]]
                           : '(unknown file)');
                     $msg .= " on line " . $call[Parser::SOURCE_LINE];

                     $callStackMsg[] = $msg;

-                    if (! is_null($limit) && $ncall > $limit) {
+                    if (! \is_null($limit) && $ncall > $limit) {
                         break;
                     }
                 }
             }
         }

         return implode("\n", $callStackMsg);
     }
```

And here is the result of this patch: 
![image](https://user-images.githubusercontent.com/439401/79604972-5f24ae80-80ef-11ea-979d-4e2b95a9f934.png)

The reason is that null-checks can be optimized by the PHP compiler when it knows about them. There is 3 ways to do this check in namespaced code:

- a strict comparison (`$limit === null`)
- a qualified function call (`\is_null($limit)`)
- a non-qualified function call, relying on the global function fallback (`is_null($limit)`).

The compiler cannot resolve function fallbacks (that must happen at runtime, after checking whether a `Scssphp\Scssphp\is_null` function exists), and so we end up with a function call rather than a very optimized opcode.

Given the massive optimization opportunity (bigger than this 28% as I changed a single place in the code, and other null checks still make `is_null` be ranked 6th for now. It goes to 31% when qualifying all `is_null` in the Compiler class), I suggest changing the way null-checks are performed in the codebase.

There is 2 solutions, and I will let the maintainers make a choice. **Both solutions can be automated with PHP-CS-Fixer**.

- use comparisons (use the `is_null` fixer)
- qualify the function calls which are optimized by PHP (use the `native_function_invocation` with the `@compiler_optimized` set of functions included)

> Note that both fixers are considered risky. That's because they will remove the fallback behavior and so will break code when you actually have a namespaced `is_null` function. But that's not an issue in this project.

Note that whatever decision you make for the way to check for `null` in the project, I suggest adding the `native_function_invocation` fixer with `@compiler_optimized` in the config, because `is_null` is not the only function being optimized.

**Comment by robocoder** [comment]
👍

**Comment by stof** [comment]
@robocoder which of the 2 solutions do you prefer ? The comparison or the qualified function call ?

**Comment by Cerdic** [comment]
wow! and wtf?
* wow! because this is just opening my eyes on a serious potential perf issue and I feel I have now to re-read a lot of code with brand new eyes
* wtf? because the `callStackMessage()` is a trace debug function only called in two place in the basecode, each time before throwing an exception for an error. I can not just see how this could be called more than 1 time (and definitely not 700times!) on a normal use of the lib...

**Comment by Cerdic** [comment]
(to be clear the fix is definitely legitimate and needed, and well done! but my guess is the final impact will be much lower in real life)

**Comment by robocoder** [comment]
It was a while back that I changed the null comparisons to is_null. I did it for consistency rather than optimizing.

I'm ok with qualifying all the native function calls and changing is_null calls back to comparisons.

**Comment by stof** [comment]
@Cerdic see #97 for the case of `callStackMessage` being the biggest bottleneck.

**Comment by Cerdic** [comment]
ok my bad! you are definitely right and I totally missed this point… /o\

**Comment by stof** [comment]
@Cerdic my profile is done on a real-life use case.

**Comment by stof** [comment]
@robocoder if you want to keep `is_null` for consistency, that's totally fine, as long as it is qualified. `null === $limit` and `\is_null($limit)` are both generating a single opcode (and maybe the `TYPE_CHECK` opcode of `is_null` is even better then the `IS_NOT_IDENTICAL` opcode of the null check, but I haven't checked that far).

**Comment by robocoder** [comment]
Thanks @stof.

TIL https://github.com/php/php-src/blob/master/Zend/zend_compile.c#L3963

**Comment by stof** [comment]
yeah, this is the main list, but not the complete one. There is a second list of function which are optimized by OPCache rather than by the Zend compiler. PHP-CS-Fixer sourced both of them.

**Comment by Girgias** [comment]
I shall point out that ``$var === null`` is NOT optimised by PHP prior to PHP 8 so the only choice here is to use the qualified call to ``\is_null()``

**Comment by stof** [comment]
@Girgias but even the PHP 7.4 opcodes for a null check are faster than going through a function call, even though PHP 8 optimizes it more.

**Comment by Girgias** [comment]
> 
> 
> @Girgias but even the PHP 7.4 opcodes for a null check are faster than going through a function call, even though PHP 8 optimizes it more.

Just to clarify, you mean a null check is faster than an unqualified function call, right? In this case we agree.
The ``\is_null()`` function which gets optimized to the ``TYPE_CHECK `` opcode is faster than the ``$a === null`` which gets converted to a normal ``IS_NOT_IDENTICAL`` opcode.
That's what the commit I linked does, it optimizes it to a ``TYPE_CHECK`` opcode.

So if you want to squeeze out the maximum from opcache using ``is_null()`` is better, however not to the extend of going from unqualified to a strict comparison.

Hope this clarifies what I was trying to say. :)
