### ISSUE TITLE
Computing the callstack message for catched errors is the main performance bottleneck

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#97]
Currently, compiling a *valid* scss file (which won't throw any exception for us to catch), `Compiler::callStackMessage()` is still called hundreds times (from `throwError` calls in `applyArguments`). And `Compiler::callStackMessage()` is the most expansive function call by far in my profiling.

This seems relative to `Compiler::sortNativeFunctionArgs` catching exceptions (and potentially rethrowing them later).
I'm wondering whether generating the callstack in the message could be delayed for these cases (to do it only if `sortNativeFunctionArgs` actually rethrow it) to reduce the cost (I'm not sure about the impact of delaying the computation on the actual value).

**Comment by Cerdic** [comment]
you are right, I think it would be totally fine to compute the `callStackMessage()` only when throwing the error in the `Compiler::sortNativeFunctionArgs`, and thus to deactivate it when in the try/catch

**Comment by stof** [comment]
I just discovered another reason to avoid this call: we *already* have a delayed computation. Meaning that if we actually trigger an error there, the error message current contains the call stack twice.

**Comment by stof** [comment]
I found a way to avoid that. If I apply it on top of the null-check fix, I only win 3% of performance in my profiling (of course, if I compare this to the 1.0.8 version, this will also take most of the improvements measured on null checks as 80% of null checks happened inside the `callStackMessage` calls, which get dropped).

**Comment by stof** [comment]
hmm, wrong profiles selected for the comparison. That's actually a 22% improvement compared to the patched version using qualifying null checks. I guess a PR is coming :smile:
